#pragma once

#include "OloEngine/Audio/SoundGraph/NodeProcessor.h"

namespace OloEngine::Audio::SoundGraph
{
	//==============================================================================
	/// Example Add node that demonstrates the endpoint registration system
	template<typename T>
	class AddNode : public NodeProcessor
	{
	private:
		// Endpoint identifiers
		const Identifier InputA_ID = OLO_IDENTIFIER("InputA");
		const Identifier InputB_ID = OLO_IDENTIFIER("InputB");
		const Identifier Output_ID = OLO_IDENTIFIER("Output");

	public:
		AddNode()
		{
			// Register parameters directly
			AddParameter<T>(InputA_ID, "InputA", T{});
			AddParameter<T>(InputB_ID, "InputB", T{});
			AddParameter<T>(Output_ID, "Output", T{});
		}

		void Process(f32** inputs, f32** outputs, u32 numSamples) override
		{
			// Get current parameter values
			T inputA = GetParameterValue<T>(InputA_ID);
			T inputB = GetParameterValue<T>(InputB_ID);
			
			// Perform addition
			T result = inputA + inputB;
			
			// Set output parameter
			SetParameterValue(Output_ID, result);
		}

		void Initialize(f64 sampleRate, u32 maxBufferSize) override
		{
			m_SampleRate = sampleRate;
		}

		Identifier GetTypeID() const override
		{
			if constexpr (std::is_same_v<T, f32>)
				return OLO_IDENTIFIER("AddNode_f32");
			else if constexpr (std::is_same_v<T, i32>)
				return OLO_IDENTIFIER("AddNode_i32");
			else
				return OLO_IDENTIFIER("AddNode_unknown");
		}

		const char* GetDisplayName() const override
		{
			if constexpr (std::is_same_v<T, f32>)
				return "Add (f32)";
			else if constexpr (std::is_same_v<T, i32>)
				return "Add (i32)";
			else
				return "Add (unknown)";
		}

	private:
		// Parameter IDs are automatically generated by the macros
		// InputA_ID, InputB_ID, Output_ID are available here
	};

	// Common type aliases
	using AddNodeF32 = AddNode<f32>;
	using AddNodeI32 = AddNode<i32>;

} // namespace OloEngine::Audio::SoundGraph