// Pure rules for which files may be edited, and which guide must be read first.
// CLAUDE.md states each of these as prose; this makes them hold.

export type Gate =
  | { kind: 'deny'; reason: string }
  | { kind: 'requires-read'; doc: string; why: string }
  | { kind: 'none' }

const SHADER = /\.(?:glsl|vert|frag|comp|geom|tesc|tese|mesh|task|rgen|rchit|rahit|rmiss|rint|rcall)$/i
const COMPONENT_DECL = /^\s*struct\s+(?:alignas\([^)]*\)\s+)?\w+Component\b(?!\s*;)/m

export const DOCS = {
  shaders: 'docs/agent-rules/glsl-shaders.md',
  components: 'docs/agent-rules/component-serializer-codegen.md',
  tests: 'docs/agent-rules/testing-architecture.md',
} as const

/**
 * Forward slashes and `.` / `..` segments resolved, case kept: `<root>/OloEngine/src/../vendor/x`
 * is the vendor file it names, whatever the spelling.
 */
export function resolvePath(p: string): string {
  const slashed = p.replace(/\\/g, '/')
  const drive = /^[A-Za-z]:/.exec(slashed)?.[0] ?? ''
  const rest = slashed.slice(drive.length)
  const isAbsolute = rest.startsWith('/')
  const out: string[] = []
  for (const part of rest.split('/')) {
    if (part === '' || part === '.') {
      continue
    }
    if (part === '..') {
      if (out.length > 0 && out[out.length - 1] !== '..') {
        out.pop()
      } else if (!isAbsolute) {
        out.push('..')
      }
      continue
    }
    out.push(part)
  }
  return `${drive}${isAbsolute ? '/' : ''}${out.join('/')}`
}

/** Resolved and lower case: how paths are compared here (Windows is case-insensitive). */
export function normPath(p: string): string {
  return resolvePath(p).toLowerCase()
}

/** Every directory above a file, nearest first: where to look for the checkout's `.git`. */
export function ancestors(path: string): string[] {
  const parts = resolvePath(path).split('/')
  const out: string[] = []
  for (let i = parts.length - 1; i > 0; i -= 1) {
    const dir = parts.slice(0, i).join('/')
    if (dir.length > 0 && !/^[A-Za-z]:$/.test(dir)) {
      out.push(dir)
    }
  }
  return out
}

/**
 * A fallback root, for when the file system cannot be asked: the directory above the first
 * top-level directory this repo has. The engine's own answer is the nearest `.git` (see
 * register), which also places a nested checkout (`.claude/worktrees/<name>`) right.
 */
export function guessRoot(path: string): string | undefined {
  const m = /^(.*?)\/(?:OloEngine|OloEditor|OloRuntime|OloServer|OloEngine-ScriptCore|docs|tools|cmake|scripts|build[\w-]*|\.github)\//.exec(resolvePath(path))
  return m?.[1]
}

/** The path relative to `root`, lower case; undefined when it lies outside. */
export function relativeTo(path: string, root: string): string | undefined {
  const p = normPath(path)
  const r = normPath(root).replace(/\/$/, '')
  return p.startsWith(`${r}/`) ? p.slice(r.length + 1) : undefined
}

/**
 * What an edit of `path` in the checkout at `root` needs. `text` is the file's current text
 * where it matters (a header that may declare a component), `incoming` the text written.
 */
export function gateFor(path: string, root: string, opts: { isNew: boolean; text?: string; incoming?: string }): Gate {
  const rel = relativeTo(path, root)
  if (rel === undefined) {
    return { kind: 'none' }
  }

  if (rel.startsWith('oloengine/vendor/') || rel.includes('/vcpkg_installed/') || rel.startsWith('vcpkg_installed/')) {
    return {
      kind: 'deny',
      reason:
        'This is a FetchContent download or a vcpkg port: a reconfigure wipes it, and the build never sees the edit for long. ' +
        'Patch a vcpkg port through cmake/overlay-ports/, and a FetchContent dependency through its CMake fetch (CLAUDE.md, Architecture).',
    }
  }

  if (/(?:^|\/)generated\//.test(rel) || /\.generated\.[a-z]+$/.test(rel)) {
    return {
      kind: 'deny',
      reason:
        'This file is generated by tools/OloHeaderTool (the GenerateBindings target) and is rewritten on the next build. ' +
        'Change the source it reads (OloEngine/src) or the generator, build GenerateBindings, and re-stage the output (CLAUDE.md, OloHeaderTool). ' +
        'A hand-broken generated file is also rewritten green by CI codegen, so it is no negative control either.',
    }
  }

  if (/^docs\/test-catalogue\.[^/]*\.md$/.test(rel)) {
    return {
      kind: 'deny',
      reason: 'docs/test-catalogue.*.md is generated and git-ignored: classify a test with `// OLO_TEST_LAYER:` or test_catalogue.json instead (CLAUDE.md, Definition of done).',
    }
  }

  if (SHADER.test(rel)) {
    return {
      kind: 'requires-read',
      doc: DOCS.shaders,
      why: 'what makes a shader fail SPIR-V compile (CLAUDE.md names it a guide to read regardless of subsystem)',
    }
  }

  if (rel.startsWith('oloengine/tests/') && rel.endsWith('.cpp') && opts.isNew) {
    return {
      kind: 'requires-read',
      doc: DOCS.tests,
      why: 'where a new test belongs; pick its classification before writing it (CLAUDE.md, Tests)',
    }
  }

  const isHeader = /\.(?:h|hpp)$/.test(rel)
  const declaresComponent = COMPONENT_DECL.test(opts.text ?? '') || COMPONENT_DECL.test(opts.incoming ?? '')
  if (isHeader && (rel.startsWith('oloengine/src/') || rel.startsWith('oloeditor/src/')) && declaresComponent) {
    return {
      kind: 'requires-read',
      doc: DOCS.components,
      why: 'the cross-binding touch-points a component change needs (save-game Serialize + RegisterAll, Lua, the inspector and Add Component menu, a hand-written copy ctor / operator==); §0 is the table (CLAUDE.md, Definition of done 3)',
    }
  }

  return { kind: 'none' }
}

export function readGateMessage(gate: { doc: string; why: string }, path: string, root: string): string {
  return (
    `olo-read-gates: read ${resolvePath(root)}/${gate.doc} before editing ${resolvePath(path).split('/').slice(-2).join('/')}. ` +
    `It covers ${gate.why}. Read that checkout's copy (any part counts; read the part you need), then retry the edit.`
  )
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * After a new test .cpp is written: is it built and classified? An entry counts only as a
 * whole source entry (CMakeLists.txt lists paths relative to OloEngine/tests/) or a
 * file_layer_map key (repo-relative): `OldNewThingTest.cpp` is no entry for `NewThingTest.cpp`.
 */
export function newTestFileNotes(path: string, root: string, content: string, cmakeLists: string | undefined, catalogue: string | undefined): string[] {
  const rel = relativeTo(path, root) ?? ''
  const relToTests = rel.startsWith('oloengine/tests/') ? rel.slice('oloengine/tests/'.length) : rel
  const base = resolvePath(path).split('/').pop() ?? path
  const notes: string[] = []

  if (cmakeLists !== undefined) {
    const entry = new RegExp(`(?:^|[\\s"(])${escapeRegExp(relToTests)}(?=[\\s")]|$)`, 'im')
    if (!entry.test(cmakeLists.replace(/\\/g, '/'))) {
      notes.push(
        `${base} is not listed in OloEngine/tests/CMakeLists.txt (as \`${relToTests}\`), which names every test source: until it is, the file is never compiled and a --gtest_filter for it runs NOTHING (and the run still says PASSED).`,
      )
    }
  }

  const hasLayer = /^\s*\/\/\s*OLO_TEST_LAYER:\s*\S+/m.test(content)
  let inCatalogue = false
  if (catalogue !== undefined) {
    try {
      const map = (JSON.parse(catalogue) as { file_layer_map?: Record<string, unknown> }).file_layer_map ?? {}
      inCatalogue = Object.keys(map).some(key => normPath(key) === rel)
    } catch {
      inCatalogue = false
    }
  }
  if (!hasLayer && !inCatalogue) {
    notes.push(`${base} has no \`// OLO_TEST_LAYER: <id>\` line near the top and no file_layer_map entry in test_catalogue.json: every test .cpp must be classified (CLAUDE.md, Definition of done 2).`)
  }
  if (/\bTEST(?:_F|_P)?\s*\(\s*\w+\s*,\s*DISABLED_/.test(content)) {
    notes.push('A test here is DISABLED_: an evidence test that needs a GL 4.6 context skips cleanly without one instead (CLAUDE.md, Rendering changes must be visually verified).')
  }
  return notes.length === 0 ? [] : [`olo-read-gates: ${notes.join(' ')}`]
}
