#include "OloEnginePCH.h"

// OLO_TEST_LAYER: unit
// =============================================================================
// ComponentFieldRegistryTest — the engine-side component-field registry and the
// two graph nodes over it (issue #793, the follow-up slice of #634).
//
// The registry is GENERATED by OloHeaderTool from the same component
// data-member scan that drives the scene serializer and the editor's MCP
// registry. That is what makes it worth testing rather than reading: the
// generator decides, per field, whether visual scripting can address it at all
// and which PinType it gets, and a wrong answer there is invisible until a
// designer's graph silently does nothing.
//
// What each group would catch:
//
//   Shape*     — the table itself being empty, unsorted or ambiguous. An empty
//                registry is the loud failure the generator already refuses to
//                emit; a table with duplicate keys is the quiet one, and it
//                would make Find() return whichever entry hashed first.
//
//   Mapping*   — a field exposed as the WRONG PinType. The one that matters is
//                Entity vs Asset: the scan folds `AssetHandle` and `UUID` onto
//                one PropType because scene YAML round-trips them identically,
//                and if that fold reached the pin types, CheckLinkCompatibility
//                would accept a wire between an entity reference and an asset
//                slot that the runtime can never satisfy.
//
//   Exclusion* — per-tick runtime state or entity identity becoming writable.
//
//   ReadWrite* — the accessor pair on a live entity, including the two guards a
//                graph specifically needs: the serializer's load-time clamp
//                (so a graph cannot produce a component state a scene load
//                could not), and the non-finite refusal (a graph can compute a
//                NaN without erroring, and storing one poisons every consumer
//                downstream, frames later and far from the cause).
//
//   Node*      — the two nodes end to end, including that an unresolved or
//                misspelled selection REPORTS rather than silently no-ops, and
//                that Set still triggers its exec output on a failure so one
//                bad field name does not stop the rest of the graph.
// =============================================================================

#include <gtest/gtest.h>

#include "OloEngine/Scene/Components.h"
#include "OloEngine/Scene/Entity.h"
#include "OloEngine/Scene/Scene.h"
#include "OloEngine/Scripting/VisualScript/ComponentFieldRegistry.h"
#include "OloEngine/Scripting/VisualScript/VisualScriptGraph.h"
#include "OloEngine/Scripting/VisualScript/VisualScriptNodeRegistry.h"
#include "OloEngine/Scripting/VisualScript/VisualScriptSerializer.h"
#include "OloEngine/Scripting/VisualScript/VisualScriptVM.h"

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <limits>
#include <set>
#include <string>
#include <string_view>
#include <vector>

#ifndef OLO_TEST_EDITOR_ROOT
#error "OLO_TEST_EDITOR_ROOT must be defined by the test target's CMake — see OloEngine/tests/CMakeLists.txt"
#endif

using namespace OloEngine;
using namespace OloEngine::VisualScript;

namespace
{
    class ComponentFieldRegistryTest : public ::testing::Test
    {
      protected:
        void SetUp() override
        {
            NodeRegistry::EnsureStandardLibrary();
            m_Scene = Ref<Scene>::Create();
            m_Entity = m_Scene->CreateEntity("Subject");
        }

        Ref<Scene> m_Scene;
        Entity m_Entity;
    };

    //==========================================================================
    // Shape
    //==========================================================================

    TEST_F(ComponentFieldRegistryTest, ShapeRegistryCoversTheEngineBroadly)
    {
        // A floor, not an exact count: the number moves with every component
        // added, and pinning it exactly would make this test a chore rather than
        // a guard. What it catches is the generator emitting a near-empty table
        // because the scan or the exclusion set went wrong.
        EXPECT_GT(ComponentFieldRegistry::All().size(), 500u);
        EXPECT_GT(ComponentFieldRegistry::ComponentNames().size(), 50u);
    }

    TEST_F(ComponentFieldRegistryTest, ShapeEntriesAreSortedAndUnique)
    {
        std::set<std::string> seen;
        std::string previousComponent;
        std::string previousField;
        for (const ComponentFieldEntry& entry : ComponentFieldRegistry::All())
        {
            const std::string key = entry.m_Component + "." + entry.m_Field;
            EXPECT_TRUE(seen.insert(key).second) << "duplicate registry key " << key;

            if (!previousComponent.empty())
            {
                const bool ordered = previousComponent < entry.m_Component ||
                                     (previousComponent == entry.m_Component && previousField < entry.m_Field);
                EXPECT_TRUE(ordered) << previousComponent << "." << previousField << " precedes " << key;
            }
            previousComponent = entry.m_Component;
            previousField = entry.m_Field;
        }
    }

    TEST_F(ComponentFieldRegistryTest, ShapeEveryEntryIsCallable)
    {
        for (const ComponentFieldEntry& entry : ComponentFieldRegistry::All())
        {
            ASSERT_NE(entry.m_Has, nullptr) << entry.m_Component << "." << entry.m_Field;
            ASSERT_NE(entry.m_Read, nullptr) << entry.m_Component << "." << entry.m_Field;
            ASSERT_NE(entry.m_Write, nullptr) << entry.m_Component << "." << entry.m_Field;
            EXPECT_NE(entry.m_Type, PinType::Exec) << entry.m_Component << "." << entry.m_Field;
            EXPECT_NE(entry.m_Type, PinType::Any) << entry.m_Component << "." << entry.m_Field;
        }
    }

    TEST_F(ComponentFieldRegistryTest, ShapeFindAcceptsBothComponentSpellings)
    {
        // The curated table on Entity.AddComponent / Entity.HasComponent (#634)
        // takes the short name, so a graph author who learned "Transform" there
        // must not have to discover that these nodes want "TransformComponent".
        const ComponentFieldEntry* viaStruct = ComponentFieldRegistry::Find("TransformComponent", "Translation");
        const ComponentFieldEntry* viaShort = ComponentFieldRegistry::Find("Transform", "Translation");
        ASSERT_NE(viaStruct, nullptr);
        EXPECT_EQ(viaStruct, viaShort);

        EXPECT_EQ(ComponentFieldRegistry::Find("NotAComponent", "Translation"), nullptr);
        EXPECT_EQ(ComponentFieldRegistry::Find("TransformComponent", "NotAField"), nullptr);
    }

    //==========================================================================
    // PinType mapping
    //==========================================================================

    TEST_F(ComponentFieldRegistryTest, MappingScalarAndVectorFieldsTakeTheirPinType)
    {
        const ComponentFieldEntry* translation = ComponentFieldRegistry::Find("TransformComponent", "Translation");
        ASSERT_NE(translation, nullptr);
        EXPECT_EQ(translation->m_Type, PinType::Vec3);

        const ComponentFieldEntry* tag = ComponentFieldRegistry::Find("TagComponent", "Tag");
        ASSERT_NE(tag, nullptr);
        EXPECT_EQ(tag->m_Type, PinType::String);
    }

    TEST_F(ComponentFieldRegistryTest, MappingEntityReferenceIsNotExposedAsAnAsset)
    {
        // The regression this exists for. Both spell as PropType::AssetHandle in
        // the shared scan; only SerField::cppType tells them apart.
        const ComponentFieldEntry* entityRef = ComponentFieldRegistry::Find("CameraRigComponent", "Target");
        ASSERT_NE(entityRef, nullptr) << "CameraRigComponent::m_Target is the UUID-typed field this pins";
        EXPECT_EQ(entityRef->m_Type, PinType::Entity);

        const ComponentFieldEntry* assetRef =
            ComponentFieldRegistry::Find("AnimationGraphComponent", "AnimationGraphAssetHandle");
        ASSERT_NE(assetRef, nullptr);
        EXPECT_EQ(assetRef->m_Type, PinType::Asset);
    }

    TEST_F(ComponentFieldRegistryTest, MappingUnrepresentableFieldTypesAreAbsent)
    {
        // A quat / mat / ivec / container / Ref<T> field has no PinType, and the
        // generator must drop it rather than pick something close. Asserted over
        // the whole table so a future widening of the scan cannot leak one in.
        for (const ComponentFieldEntry& entry : ComponentFieldRegistry::All())
        {
            switch (entry.m_Type)
            {
                case PinType::Bool:
                case PinType::Int:
                case PinType::Float:
                case PinType::Vec2:
                case PinType::Vec3:
                case PinType::Vec4:
                case PinType::String:
                case PinType::Entity:
                case PinType::Asset:
                    break;
                default:
                    ADD_FAILURE() << entry.m_Component << "." << entry.m_Field << " has PinType "
                                  << PinTypeToString(entry.m_Type);
            }
        }
    }

    //==========================================================================
    // Exclusions
    //==========================================================================

    TEST_F(ComponentFieldRegistryTest, ExclusionRuntimeOnlyComponentsAreUnreachable)
    {
        // Mirrors kComponentsNotFieldEditable in tools/OloHeaderTool/main.cpp.
        // IDComponent is the important one: the UUID is how a graph addresses the
        // entity in the first place, so a graph rewriting it would break the
        // handle it is holding.
        for (const char* component : { "IDComponent", "WorldTransformComponent", "AnimationStateComponent",
                                       "UIResolvedRectComponent", "DialogueStateComponent" })
        {
            EXPECT_TRUE(ComponentFieldRegistry::FieldsOf(component).empty()) << component << " should not be exposed";
        }
    }

    TEST_F(ComponentFieldRegistryTest, ExclusionTheSceneGraphIsNotAWritableField)
    {
        // RelationshipComponent::m_ParentHandle and the parent's m_Children are
        // two halves of one link. Only Entity::SetParent updates both, so a raw
        // field write would report success, reparent nothing, and leave the two
        // disagreeing — the state Scene::PropagateWorldTransforms names as "data
        // corruption, not a supported path".
        EXPECT_TRUE(ComponentFieldRegistry::FieldsOf("RelationshipComponent").empty());
        EXPECT_EQ(ComponentFieldRegistry::Find("RelationshipComponent", "ParentHandle"), nullptr);
    }

    //==========================================================================
    // Read / write
    //==========================================================================

    TEST_F(ComponentFieldRegistryTest, ReadWriteRoundTripsAVectorField)
    {
        const ComponentFieldEntry* entry = ComponentFieldRegistry::Find("TransformComponent", "Translation");
        ASSERT_NE(entry, nullptr);
        ASSERT_TRUE(entry->Has(m_Entity));

        EXPECT_EQ(entry->Write(m_Entity, PinValue::MakeVec3(glm::vec3(1.0f, 2.0f, 3.0f))), FieldWriteResult::Changed);
        EXPECT_FLOAT_EQ(m_Entity.GetComponent<TransformComponent>().Translation.y, 2.0f);

        const PinValue read = entry->Read(m_Entity);
        EXPECT_EQ(read.GetType(), PinType::Vec3);
        EXPECT_FLOAT_EQ(read.AsVec3().z, 3.0f);

        // Writing the same value again is not a change — the signal the editor's
        // dirty/undo handling and any future change-tracking would key on.
        EXPECT_EQ(entry->Write(m_Entity, PinValue::MakeVec3(glm::vec3(1.0f, 2.0f, 3.0f))), FieldWriteResult::Unchanged);
    }

    TEST_F(ComponentFieldRegistryTest, ReadWriteMissingComponentIsReportedNotAssumed)
    {
        const ComponentFieldEntry* entry = ComponentFieldRegistry::Find("BoidComponent", "MaxNeighbors");
        ASSERT_NE(entry, nullptr);
        EXPECT_FALSE(entry->Has(m_Entity)) << "the fixture entity carries no BoidComponent";
    }

    TEST_F(ComponentFieldRegistryTest, ReadWriteClampsToTheSerializersLoadTimeRange)
    {
        // BoidComponent::m_MaxNeighbors carries OLO_SERIALIZE(Clamp, 1, 4096), so
        // the registry must refuse to leave it at 0 — a value a scene load could
        // never produce.
        const ComponentFieldEntry* entry = ComponentFieldRegistry::Find("BoidComponent", "MaxNeighbors");
        ASSERT_NE(entry, nullptr);
        ASSERT_TRUE(entry->m_Bounds.IsBounded()) << "the Clamp annotation should have reached the registry";

        m_Entity.AddComponent<BoidComponent>();
        ASSERT_TRUE(entry->Has(m_Entity));

        (void)entry->Write(m_Entity, PinValue::MakeInt(-5));
        EXPECT_GE(entry->Read(m_Entity).AsInt(), 1);

        (void)entry->Write(m_Entity, PinValue::MakeInt(1'000'000));
        EXPECT_LE(entry->Read(m_Entity).AsInt(), 4096);
    }

    TEST_F(ComponentFieldRegistryTest, ReadWriteRefusesANonFiniteFloat)
    {
        const ComponentFieldEntry* entry = ComponentFieldRegistry::Find("TransformComponent", "Translation");
        ASSERT_NE(entry, nullptr);

        (void)entry->Write(m_Entity, PinValue::MakeVec3(glm::vec3(4.0f, 5.0f, 6.0f)));
        const glm::vec3 before = entry->Read(m_Entity).AsVec3();

        const f32 nan = std::numeric_limits<f32>::quiet_NaN();
        EXPECT_EQ(entry->Write(m_Entity, PinValue::MakeVec3(glm::vec3(1.0f, nan, 1.0f))), FieldWriteResult::Rejected);

        // Nothing stored — not even the two good components. A half-updated
        // vector is worse than a refused write.
        const glm::vec3 after = entry->Read(m_Entity).AsVec3();
        EXPECT_FLOAT_EQ(after.x, before.x);
        EXPECT_FLOAT_EQ(after.y, before.y);
        EXPECT_FLOAT_EQ(after.z, before.z);
    }

    TEST_F(ComponentFieldRegistryTest, ReadWriteRefusesANonFiniteScalarFloat)
    {
        // The scalar sibling of the vector case above, and the one that was
        // silently broken first: `std::isfinite(value.AsFloat())` can never fail,
        // because AsFloat() already maps a non-finite Float to 0.0f. Written that
        // way, a NaN was stored as a perfectly plausible 0 and reported as a
        // successful change. The guard has to inspect the PinValue itself.
        const ComponentFieldEntry* entry = ComponentFieldRegistry::Find("BoidComponent", "MaxSpeed");
        ASSERT_NE(entry, nullptr);
        m_Entity.AddComponent<BoidComponent>();
        ASSERT_TRUE(entry->Has(m_Entity));

        ASSERT_EQ(entry->Write(m_Entity, PinValue::MakeFloat(12.0f)), FieldWriteResult::Changed);
        const f32 before = entry->Read(m_Entity).AsFloat();

        for (const f32 bad : { std::numeric_limits<f32>::quiet_NaN(), std::numeric_limits<f32>::infinity() })
        {
            EXPECT_EQ(entry->Write(m_Entity, PinValue::MakeFloat(bad)), FieldWriteResult::Rejected);
            EXPECT_FLOAT_EQ(entry->Read(m_Entity).AsFloat(), before) << "a refused write must store nothing";
        }
    }

    TEST_F(ComponentFieldRegistryTest, ReadWriteClampsIntoTheFieldsOwnWidth)
    {
        // An Int pin is an i64 and most integer fields are much narrower. Without
        // the width clamp a static_cast would wrap, so a graph writing 300 into a
        // u8 field would store 44 and report success.
        for (const ComponentFieldEntry& entry : ComponentFieldRegistry::All())
        {
            if (entry.m_Type != PinType::Int || entry.m_Bounds.IsBounded() || !entry.Has(m_Entity))
            {
                continue;
            }
            (void)entry.Write(m_Entity, PinValue::MakeInt(std::numeric_limits<i64>::max()));
            const i64 stored = entry.Read(m_Entity).AsInt();
            EXPECT_GE(stored, 0) << entry.m_Component << "." << entry.m_Field << " wrapped negative";
        }
    }

    //==========================================================================
    // The nodes
    //==========================================================================

    /// Runs the two nodes against a real Scene and a real entity.
    class ComponentFieldNodeTest : public ComponentFieldRegistryTest
    {
      protected:
        void SetUp() override
        {
            ComponentFieldRegistryTest::SetUp();
            m_Asset = Ref<VisualScriptAsset>::Create();
        }

        VisualScriptGraph& Graph()
        {
            return m_Asset->m_EventGraph;
        }

        /// Add a Get/Set Component Field node and select its target field.
        /// Returns the id, never a reference: `AddNode` invalidates the previous
        /// reference (its own doc comment says so), and holding one across the
        /// next AddNode is the classic way to corrupt a graph built in a test.
        [[nodiscard]] NodeId AddFieldNode(std::string_view typeName, const char* component, const char* field)
        {
            const NodeId id = Graph().AddNode(std::string(typeName)).m_Id;
            VisualScriptNode* node = Graph().FindNode(id);
            node->SetProperty(std::string(NodeProps::kComponentName), component);
            node->SetProperty(std::string(NodeProps::kFieldName), field);
            return id;
        }

        /// Compile and fire OnBeginPlay with the fixture's scene attached, so the
        /// nodes resolve a real entity. Errors land on the instance, which is
        /// what several of these cases assert on.
        [[nodiscard]] bool RunBeginPlay()
        {
            std::vector<CompileDiagnostic> errors;
            Ref<VisualScriptPlan> plan = VisualScriptPlan::Compile(*m_Asset, errors);
            if (!plan)
            {
                ADD_FAILURE() << (errors.empty() ? std::string("compile failed with no diagnostics")
                                                 : errors[0].m_Message);
                return false;
            }
            m_Instance = VisualScriptInstance(plan, m_Entity.GetUUID());
            m_Runtime.m_Scene = m_Scene.Raw();
            m_Runtime.m_DeltaTime = 1.0f / 60.0f;
            m_Instance.BeginPlay(m_Runtime);
            return true;
        }

        [[nodiscard]] std::string FirstError() const
        {
            return m_Instance.GetErrors().empty() ? std::string{} : m_Instance.GetErrors().front();
        }

        Ref<VisualScriptAsset> m_Asset;
        VisualScriptInstance m_Instance;
        RuntimeContext m_Runtime;
    };

    TEST_F(ComponentFieldNodeTest, NodeSetWritesThroughToTheComponent)
    {
        const NodeId begin = Graph().AddNode(std::string(NodeTypes::kOnBeginPlay)).m_Id;
        const NodeId self = Graph().AddNode("Entity.GetSelf").m_Id;
        const NodeId set = AddFieldNode(NodeTypes::kSetComponentField, "TransformComponent", "Translation");
        Graph().FindNode(set)->m_PinDefaults["Value"] = PinValue::MakeVec3(glm::vec3(7.0f, 8.0f, 9.0f));

        Graph().AddLink(begin, "Then", set, "Enter");
        Graph().AddLink(self, "Self", set, "Target");

        ASSERT_TRUE(RunBeginPlay());
        EXPECT_TRUE(m_Instance.GetErrors().empty()) << FirstError();
        EXPECT_FLOAT_EQ(m_Entity.GetComponent<TransformComponent>().Translation.x, 7.0f);
        EXPECT_FLOAT_EQ(m_Entity.GetComponent<TransformComponent>().Translation.z, 9.0f);
    }

    TEST_F(ComponentFieldNodeTest, NodeGetReadsTheLiveValueWithTheFieldsPinType)
    {
        m_Entity.GetComponent<TransformComponent>().Translation = glm::vec3(4.0f, 5.0f, 6.0f);

        const NodeId begin = Graph().AddNode(std::string(NodeTypes::kOnBeginPlay)).m_Id;
        const NodeId self = Graph().AddNode("Entity.GetSelf").m_Id;
        const NodeId get = AddFieldNode(NodeTypes::kGetComponentField, "TransformComponent", "Translation");
        // Round-trip the read into a DIFFERENT field, so the assertion reads the
        // engine copy of the value rather than the VM scratch slot it came from.
        const NodeId set = AddFieldNode(NodeTypes::kSetComponentField, "TransformComponent", "Scale");

        Graph().AddLink(begin, "Then", set, "Enter");
        Graph().AddLink(self, "Self", get, "Target");
        Graph().AddLink(self, "Self", set, "Target");
        Graph().AddLink(get, "Value", set, "Value");

        ASSERT_TRUE(RunBeginPlay());
        EXPECT_TRUE(m_Instance.GetErrors().empty()) << FirstError();
        EXPECT_FLOAT_EQ(m_Entity.GetComponent<TransformComponent>().Scale.y, 5.0f);
    }

    TEST_F(ComponentFieldNodeTest, NodeUnknownFieldReportsAndStillContinuesTheExecChain)
    {
        const NodeId begin = Graph().AddNode(std::string(NodeTypes::kOnBeginPlay)).m_Id;
        const NodeId self = Graph().AddNode("Entity.GetSelf").m_Id;
        const NodeId bad = AddFieldNode(NodeTypes::kSetComponentField, "TransformComponent", "NoSuchField");
        // A valid Set downstream of the broken one. If a failure severed the exec
        // chain this would never run, and one typo would silently disable the
        // rest of the graph with only the first message to explain it.
        const NodeId good = AddFieldNode(NodeTypes::kSetComponentField, "TransformComponent", "Translation");
        Graph().FindNode(good)->m_PinDefaults["Value"] = PinValue::MakeVec3(glm::vec3(2.0f, 2.0f, 2.0f));

        Graph().AddLink(begin, "Then", bad, "Enter");
        Graph().AddLink(bad, "Then", good, "Enter");
        Graph().AddLink(self, "Self", bad, "Target");
        Graph().AddLink(self, "Self", good, "Target");

        ASSERT_TRUE(RunBeginPlay());
        ASSERT_FALSE(m_Instance.GetErrors().empty()) << "an unknown field must be reported, never silently skipped";
        EXPECT_NE(FirstError().find("NoSuchField"), std::string::npos)
            << "the message should name the field: " << FirstError();
        EXPECT_FLOAT_EQ(m_Entity.GetComponent<TransformComponent>().Translation.x, 2.0f)
            << "the downstream node must still have run";
    }

    TEST_F(ComponentFieldNodeTest, NodeMissingComponentOnTheTargetIsReported)
    {
        const NodeId begin = Graph().AddNode(std::string(NodeTypes::kOnBeginPlay)).m_Id;
        const NodeId self = Graph().AddNode("Entity.GetSelf").m_Id;
        const NodeId set = AddFieldNode(NodeTypes::kSetComponentField, "BoidComponent", "MaxNeighbors");
        Graph().FindNode(set)->m_PinDefaults["Value"] = PinValue::MakeInt(8);

        Graph().AddLink(begin, "Then", set, "Enter");
        Graph().AddLink(self, "Self", set, "Target");

        ASSERT_TRUE(RunBeginPlay());
        ASSERT_FALSE(m_Instance.GetErrors().empty());
        EXPECT_NE(FirstError().find("BoidComponent"), std::string::npos) << FirstError();
    }

    TEST_F(ComponentFieldNodeTest, NodeUnselectedFieldIsReportedRatherThanSilentlySkipped)
    {
        const NodeId begin = Graph().AddNode(std::string(NodeTypes::kOnBeginPlay)).m_Id;
        const NodeId self = Graph().AddNode("Entity.GetSelf").m_Id;
        // A freshly created node, never configured - the state the author leaves
        // it in between dropping it on the canvas and picking a field.
        const NodeId set = Graph().AddNode(std::string(NodeTypes::kSetComponentField)).m_Id;

        Graph().AddLink(begin, "Then", set, "Enter");
        Graph().AddLink(self, "Self", set, "Target");

        ASSERT_TRUE(RunBeginPlay());
        ASSERT_FALSE(m_Instance.GetErrors().empty());
        EXPECT_NE(FirstError().find("no component/field selected"), std::string::npos) << FirstError();
    }

    TEST_F(ComponentFieldNodeTest, ShippedDemoGraphLoadsCompilesAndActuallyMovesTheEntity)
    {
        // The sample under SandboxProject is the worked example of these two
        // nodes, so it is worth more than a parse check: the first draft of it
        // read an `Elapsed` variable that nothing ever wrote, so `sin(0) * 0.75`
        // pinned Y to zero on every tick and the "bob" demonstrated nothing while
        // loading and compiling perfectly. Run it and assert it moves.
        const auto path = std::filesystem::path{ OLO_TEST_EDITOR_ROOT } / "SandboxProject" / "Assets" /
                          "VisualScripts" / "ComponentFieldDemo.olovs";
        ASSERT_TRUE(std::filesystem::exists(path)) << path.string();
        ASSERT_TRUE(VisualScriptSerializer::Deserialize(*m_Asset, path));

        std::vector<CompileDiagnostic> errors;
        Ref<VisualScriptPlan> plan = VisualScriptPlan::Compile(*m_Asset, errors);
        ASSERT_TRUE(plan) << (errors.empty() ? std::string("compile failed with no diagnostics") : errors[0].m_Message);

        m_Instance = VisualScriptInstance(plan, m_Entity.GetUUID());
        m_Runtime.m_Scene = m_Scene.Raw();
        m_Runtime.m_DeltaTime = 1.0f / 60.0f;
        m_Instance.BeginPlay(m_Runtime);

        // Far enough into the sine to be unambiguously off zero, and short enough
        // to stay in the first half-period so the sign is known.
        for (int i = 0; i < 30; ++i)
            m_Instance.Tick(m_Runtime);

        EXPECT_TRUE(m_Instance.GetErrors().empty()) << FirstError();
        EXPECT_GT(m_Entity.GetComponent<TransformComponent>().Translation.y, 0.05f)
            << "the demo should be driving Y through Get/Set Component Field";
    }

} // namespace
