#pragma once

#include "OloEngine/Core/Base.h"
#include "OloEngine/Core/Ref.h"
#include "OloEngine/Renderer/Texture.h"

#include <unordered_map>
#include <vector>

#include <glm/glm.hpp>

namespace OloEngine
{
    // Quadratic Bézier curve in em-space (3 control points).
    struct SlugCurve
    {
        glm::vec2 P1{};
        glm::vec2 P2{};
        glm::vec2 P3{};
    };

    // Per-glyph rendering data generated by SlugFontProcessor.
    struct SlugGlyphRenderData
    {
        // Location of this glyph's band data in the band texture.
        u32 BandTextureX = 0;
        u32 BandTextureY = 0;

        // Number of horizontal/vertical bands.
        u32 HBandCount = 0;
        u32 VBandCount = 0;

        // Band transform: maps em-space → band index.
        // bandIndex = renderCoord * Scale + Offset
        f32 BandScaleX = 0.0f;
        f32 BandScaleY = 0.0f;
        f32 BandOffsetX = 0.0f;
        f32 BandOffsetY = 0.0f;
    };

    // Per-glyph metrics needed for text layout (advance, kerning, bounds).
    struct SlugGlyphData
    {
        f32 AdvanceWidth = 0.0f;
        f32 PlaneBoundsLeft = 0.0f;
        f32 PlaneBoundsBottom = 0.0f;
        f32 PlaneBoundsRight = 0.0f;
        f32 PlaneBoundsTop = 0.0f;

        // Slug rendering data (populated by SlugFontProcessor).
        SlugGlyphRenderData RenderData;

        // True if this glyph has curves and can be rendered.
        bool HasCurves = false;
    };

    struct SlugFontMetrics
    {
        f32 AscenderY = 0.0f;
        f32 DescenderY = 0.0f;
        f32 LineHeight = 0.0f;
        f32 UnitsPerEm = 0.0f;
    };

    struct SlugFontData
    {
        SlugFontMetrics Metrics;
        std::unordered_map<u32, SlugGlyphData> Glyphs; // codepoint → glyph
        std::unordered_map<u64, f32> KerningPairs;     // (left<<32|right) → kern advance

        // GPU textures for Slug rendering.
        Ref<Texture2D> CurveTexture; // RGBA16F — control point data
        Ref<Texture2D> BandTexture;  // RG16UI  — band headers + curve lists

        // Deferred GPU upload.
        //
        // A font parsed without a live GL context (a headless metrics-only load
        // — e.g. Font::GetDefault() called from a unit test before the renderer
        // is up, or an asset preprocessor) cannot create its curve/band textures
        // yet. Rather than caching the font as permanently non-renderable, the
        // processor retains the already-packed, already-padded texel data here
        // and the GPU textures are uploaded lazily the first time a texture is
        // requested with a context bound (SlugFontProcessor::EnsureGpuTextures).
        // The CPU copies are freed once uploaded, so a font that does eventually
        // render pays no lasting memory cost. Without this, a font first touched
        // before the renderer exists would silently drop all its text on every
        // later render even once a context is live (issue #520).
        bool GpuUploadPending = false;
        std::vector<f32> PendingCurveTexels; // RGBA16F, padded to Width*Height*4 floats
        std::vector<u16> PendingBandTexels;  // RG16UI,  padded to Width*Height*2 u16s
        u32 PendingCurveWidth = 0;
        u32 PendingCurveHeight = 0;
        u32 PendingBandWidth = 0;
        u32 PendingBandHeight = 0;

        [[nodiscard]] const SlugGlyphData* GetGlyph(u32 codepoint) const
        {
            if (auto const it = Glyphs.find(codepoint); it != Glyphs.end())
            {
                return &it->second;
            }
            return nullptr;
        }

        [[nodiscard]] f32 GetAdvance(u32 codepoint, u32 nextCodepoint) const
        {
            const auto* glyph = GetGlyph(codepoint);
            if (!glyph)
            {
                return 0.0f;
            }
            f32 advance = glyph->AdvanceWidth;
            if (auto const it = KerningPairs.find((static_cast<u64>(codepoint) << 32) | nextCodepoint); it != KerningPairs.end())
            {
                advance += it->second;
            }
            return advance;
        }
    };
} // namespace OloEngine
