#!/usr/bin/env python3
# =============================================================================
# generate_courtyard_scene.py
#
# Emits the DENSE ARCHITECTURAL / FOLIAGE benchmark scene (issue #974):
#   OloEditor/SandboxProject/Assets/Scenes/Benchmark/Courtyard.olo
#
# Unlike generate_perf_scenes.py (git-ignored output), the Courtyard scene is
# COMMITTED — this generator exists because ~150 local lights and a 48-tower
# instanced ring are unmaintainable by hand, not because the scene is
# regenerated per run. Regenerate only when deliberately changing the scene,
# and commit the result. Output is byte-stable: fixed seed, deterministic
# float formatting, no timestamps.
#
#   python OloEngine/tests/scripts/generate_courtyard_scene.py
#
# The scene is the feature-density stress axis of the benchmark trio
# (MaterialLab / Courtyard / OceanCoast — docs/guides/renderer-benchmarks.md):
# Sponza opaque+masked geometry, 4 decal modes, 142 point + 12 spot lights
# (10 of them shadow-casting), a realtime DDGI volume, SSGI + SSR + SSAO,
# volumetric fog with light shafts, wind-driven terrain foliage (billboards +
# pine/palm meshes with octahedral impostors), and a distant instanced tower
# ring for fog/culling depth. Capture manifests live under
# OloEditor/assets/benchmark/manifests/courtyard.*.yaml.
#
# Every YAML key below is either verified against SceneSerializer.cpp /
# Scene/Generated/SceneSerializeComponents.Generated.inl or copied verbatim
# from a committed scene that uses it (SponzaForwardPlus / SponzaDeferred,
# DDGITest, SSGITest, SSRTest, VolumetricFogTest, DecalModeMatrixTest,
# FoliageGenerationTest, Drift, InstancingDemo, ClothWindTest).
# =============================================================================

import argparse
import math
import pathlib
import random
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
DEFAULT_OUT = (REPO_ROOT / "OloEditor" / "SandboxProject" / "Assets" / "Scenes"
               / "Benchmark" / "Courtyard.olo")

# Issue #974 entity-UUID namespace for this scene: 974000002xxxxxx.
ID_BASE = 974_000_002_000_000

SEED = 974

# Colored palette for the atrium light grid (cycled, SponzaForwardPlus-style).
PALETTE = [
    (1.0, 0.25, 0.12), (1.0, 0.55, 0.15), (1.0, 0.9, 0.25), (0.3, 1.0, 0.35),
    (0.25, 0.85, 0.95), (0.3, 0.45, 1.0), (0.75, 0.35, 1.0), (1.0, 0.5, 0.75),
]


def f(x):
    """Compact float formatting: 4 significant decimals, no trailing zeros."""
    s = f"{x:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(v):
    return "[" + ", ".join(f(c) for c in v) + "]"


HEADER = """\
Scene: Courtyard.olo
# ─────────────────────────────────────────────────────────────────────────────
# DENSE ARCHITECTURAL / FOLIAGE benchmark scene (issue #974).
#
# The feature-density stress axis of the benchmark trio (see
# docs/guides/renderer-benchmarks.md): every deferred-path feature enabled at
# once, in one frame, deterministically.
#
#   * Sponza atrium (opaque + alpha-masked fabric/plants) with a low sun
#     angled down the long (X) axis for long CSM shadows.
#   * 120 colored point lights in a 6x4x5 grid through the atrium
#     (SponzaForwardPlus layout), 6 shadow-casting warm points on the
#     centre-line, 16 garden points outside, 12 spots (4 shadow-casting).
#   * Realtime DDGI: LightProbeVolumeComponent (Mode 1) covering the atrium.
#   * 4 DecalComponents on the atrium floor, one per DecalMode
#     (0 Albedo / 1 Normal / 2 RMA / 3 Emissive — DecalModeMatrixTest shape).
#   * SSGI + SSR + SSAO + volumetric fog with light shafts via the scene-level
#     PostProcessSettings / FogSettings blocks below.
#   * A 192x192 procedural terrain garden east (+X) of the atrium with three
#     wind-swayed foliage layers: grass billboards (alpha-masked), pine and
#     palm meshes with octahedral impostors (Drift layout).
#   * A 48-tower InstancedMeshComponent massing ring at radius ~420-520 for
#     geometry at depth (fog integration + culling).
#
# The renderer-side switches the scene cannot serialize (Path=Deferred,
# EnableDDGI, TAA) are applied by the capture manifests under
# OloEditor/assets/benchmark/manifests/courtyard.*.yaml — open this scene by
# hand and you must set Deferred + DDGI yourself in Renderer Settings.
#
# GENERATED by OloEngine/tests/scripts/generate_courtyard_scene.py — edit the
# generator and regenerate rather than hand-editing (byte-stable output).
# ─────────────────────────────────────────────────────────────────────────────
"""

# Scene-level settings blocks. Key spellings: PostProcessSettings /
# FogSettings / WindSettings deserializers in SceneSerializer.cpp
# (TrySet key lists), values tuned from SSGITest / SSRTest /
# VolumetricFogTest / ClothWindTest.
SETTINGS = """\
PostProcessSettings:
  TonemapOperator: 2
  Exposure: 1
  Gamma: 2.2
  BloomEnabled: true
  BloomThreshold: 1.2
  BloomIntensity: 0.35
  BloomIterations: 5
  VignetteEnabled: false
  VignetteIntensity: 0.5
  VignetteSmoothness: 0.2
  ChromaticAberrationEnabled: false
  ChromaticAberrationIntensity: 0.5
  # FXAA off: keep the benchmark frame AA-free. TAA is neither scene-serialized
  # nor toggleable from a v1 capture manifest (RendererSettings allowlist), so
  # the temporal axis here is the SSGI/SSR temporal resolves + realtime DDGI.
  FXAAEnabled: false
  DOFEnabled: false
  DOFFocusDistance: 10
  DOFFocusRange: 5
  DOFBokehRadius: 3
  MotionBlurEnabled: false
  MotionBlurStrength: 0.5
  MotionBlurSamples: 4
  ColorGradingEnabled: false
  SSAOEnabled: true
  SSAORadius: 0.6
  SSAOBias: 0.025
  SSAOIntensity: 1
  SSAOSamples: 32
  SSAODebugView: false
  SSREnabled: true
  SSRMaxDistance: 60
  SSRThickness: 0.9
  SSRStride: 0.22
  SSRMaxSteps: 96
  SSRBinarySearchSteps: 6
  SSRIntensity: 1
  SSRMaxRoughness: 0.6
  SSREdgeFade: 0.1
  SSRDebugView: false
  SSRTemporalResolve: true
  SSGIEnabled: true
  SSGIIntensity: 1.5
  SSGIMaxDistance: 30
  SSGIThickness: 1.5
  SSGIStride: 0.5
  SSGIMaxSteps: 32
  SSGIRayCount: 16
  SSGIEdgeFade: 0.1
  SSGIDebugView: false
  SSGITemporalResolve: true
  AutoExposureEnabled: false
FogSettings:
  Enabled: true
  Mode: 1
  Color: [0.5, 0.55, 0.62]
  Density: 0.022
  Start: 0
  End: 650
  HeightFalloff: 0.35
  HeightOffset: 0
  MaxOpacity: 0.8
  EnableScattering: true
  RayleighStrength: 0.5
  MieStrength: 0.02
  MieDirectionality: 0.72
  RayleighColor: [0.27, 0.51, 0.83]
  SunIntensity: 5
  EnableVolumetric: true
  VolumetricSamples: 64
  AbsorptionCoefficient: 0.012
  EnableNoise: true
  NoiseScale: 0.05
  NoiseSpeed: 0.35
  NoiseIntensity: 0.45
  EnableLightShafts: true
  LightShaftIntensity: 1.3
WindSettings:
  Enabled: true
  Direction: [0.85, 0, 0.35]
  Speed: 9
  GustStrength: 0.5
  GustFrequency: 0.7
  TurbulenceIntensity: 0.45
  TurbulenceScale: 0.12
  GridWorldSize: 420
  GridResolution: 128
"""


class SceneWriter:
    def __init__(self):
        self.parts = []
        self.next_id = ID_BASE
        self.count = 0

    def entity(self, tag, translation=(0, 0, 0), rotation=(0, 0, 0),
               scale=(1, 1, 1), components="", comment=None):
        eid = self.next_id
        self.next_id += 1
        self.count += 1
        if comment:
            self.parts.append(f"  # {comment}\n")
        self.parts.append(
            f"  - Entity: {eid}\n"
            f"    TagComponent:\n"
            f"      Tag: {tag}\n"
            f"    TransformComponent:\n"
            f"      Translation: {vec(translation)}\n"
            f"      Rotation: {vec(rotation)}\n"
            f"      Scale: {vec(scale)}\n"
            + components
        )
        return eid

    def text(self):
        return HEADER + SETTINGS + "Entities:\n" + "".join(self.parts)


# --- component snippets (4-space indent = component key level) ---------------

def camera(fov=0.785398185, near=0.05, far=2500.0):
    return (
        "    CameraComponent:\n"
        "      Camera:\n"
        "        ProjectionType: 0\n"
        f"        PerspectiveFOV: {f(fov)}\n"
        f"        PerspectiveNear: {f(near)}\n"
        f"        PerspectiveFar: {f(far)}\n"
        "        OrthographicSize: 10\n"
        "        OrthographicNear: -1\n"
        "        OrthographicFar: 1\n"
        "      Primary: true\n"
        "      FixedAspectRatio: false\n"
    )


def environment_map():
    return (
        "    EnvironmentMapComponent:\n"
        "      FilePath: assets/textures/hdr/newport_loft.hdr\n"
        "      IsCubemapFolder: false\n"
        "      EnableSkybox: true\n"
        "      Rotation: 0\n"
        "      Exposure: 1\n"
        "      BlurAmount: 0\n"
        "      EnableIBL: true\n"
        "      IBLIntensity: 0.35\n"
        "      Tint: [1, 1, 1]\n"
    )


def dir_light():
    # Low sun angled down the atrium's long (X) axis: long shadows through the
    # colonnade, and the volumetric light shafts read against the west end.
    return (
        "    DirectionalLightComponent:\n"
        "      Direction: [-0.72, -0.38, -0.2]\n"
        "      Color: [1, 0.88, 0.72]\n"
        "      Intensity: 5.5\n"
        "      CastShadows: true\n"
        "      ShadowBias: 0.0015\n"
        "      ShadowNormalBias: 0.15\n"
        "      MaxShadowDistance: 900\n"
        "      CascadeSplitLambda: 0.92\n"
        "      CascadeDebugVisualization: false\n"
    )


def model(path):
    return (
        "    ModelComponent:\n"
        f"      FilePath: {path}\n"
        "      Visible: true\n"
    )


def mesh(primitive):
    return f"    MeshComponent:\n      Primitive: {primitive}\n"


def material(albedo, metallic=0.0, roughness=0.9):
    return (
        "    MaterialComponent:\n"
        f"      AlbedoColor: {vec(albedo)}\n"
        f"      Metallic: {f(metallic)}\n"
        f"      Roughness: {f(roughness)}\n"
    )


def point_light(color, intensity, range_, cast_shadows=False):
    return (
        "    PointLightComponent:\n"
        f"      Color: {vec(color)}\n"
        f"      Intensity: {f(intensity)}\n"
        f"      Range: {f(range_)}\n"
        "      Attenuation: 1\n"
        f"      CastShadows: {'true' if cast_shadows else 'false'}\n"
        "      ShadowBias: 0.005\n"
        "      ShadowNormalBias: 0.1\n"
    )


def spot_light(direction, color, intensity, range_, inner, outer,
               cast_shadows=False):
    # Key shape: generated serializer block for SpotLightComponent
    # (SceneSerializeComponents.Generated.inl); cutoffs in degrees, values
    # after VirtualShadowMapLocalLights.olo.
    return (
        "    SpotLightComponent:\n"
        f"      Direction: {vec(direction)}\n"
        f"      Color: {vec(color)}\n"
        f"      Intensity: {f(intensity)}\n"
        f"      Range: {f(range_)}\n"
        f"      InnerCutoff: {f(inner)}\n"
        f"      OuterCutoff: {f(outer)}\n"
        "      Attenuation: 0.03\n"
        f"      CastShadows: {'true' if cast_shadows else 'false'}\n"
        "      ShadowBias: 0.005\n"
        "      ShadowNormalBias: 0.1\n"
    )


def decal(color, size, mode, albedo_tex=None, emissive_tex=None):
    # Key shape: DeserializeDecalComponent (SceneSerializer.cpp) /
    # DecalModeMatrixTest.olo.
    s = (
        "    DecalComponent:\n"
        f"      Color: {vec(color)}\n"
        f"      Size: {vec(size)}\n"
        "      FadeDistance: 0.02\n"
        "      NormalAngleThreshold: 0.5\n"
    )
    if albedo_tex:
        s += f"      AlbedoTexturePath: {albedo_tex}\n"
    if emissive_tex:
        s += f"      EmissiveTexturePath: {emissive_tex}\n"
    s += (
        f"      Mode: {mode}\n"
        "      Transparent: false\n"
    )
    return s


def light_probe_volume():
    # Key shape: DDGITest.olo. Mode 1 = Realtime DDGI. Bounds cover the whole
    # atrium interior (floor to clerestory). 10x6x5 = 300 probes at a capture
    # budget of 8/frame -> a full refresh every 38 frames; the manifests warm
    # 128 frames (>= 3 full passes at hysteresis 0.85).
    return (
        "    LightProbeVolumeComponent:\n"
        "      BoundsMin: [-16, -0.5, -8]\n"
        "      BoundsMax: [16, 15.5, 8]\n"
        "      Resolution: [10, 6, 5]\n"
        "      Spacing: 3.56\n"
        "      Intensity: 1\n"
        "      Active: true\n"
        "      BakedDataAsset: 0\n"
        "      ShowDebugProbes: false\n"
        "      Mode: 1\n"
        "      RaysPerProbe: 256\n"
        "      Hysteresis: 0.85\n"
        "      ProbeCaptureBudget: 8\n"
        "      RelightBudget: 0\n"
        "      SelfShadowBias: 0.3\n"
    )


def terrain_and_foliage():
    # Key shape: FoliageGenerationTest.olo (billboard layers + procedural
    # terrain with AutoMaterial) and Drift.olo (mesh foliage layers with
    # octahedral impostor keys). Terrain origin is a CORNER (Drift comment):
    # this tile spans x in [24, 216], z in [-96, 96] — the garden east of the
    # Sponza atrium.
    return (
        "    TerrainComponent:\n"
        "      HeightmapPath: \"\"\n"
        "      WorldSizeX: 192\n"
        "      WorldSizeZ: 192\n"
        "      HeightScale: 7\n"
        "      ProceduralEnabled: true\n"
        "      ProceduralSeed: 974\n"
        "      ProceduralResolution: 256\n"
        "      ProceduralOctaves: 5\n"
        "      ProceduralFrequency: 2\n"
        "      ProceduralLacunarity: 2\n"
        "      ProceduralPersistence: 0.45\n"
        "      ShapingRidgeBlend: 0\n"
        "      ShapingWarpStrength: 0.12\n"
        "      ShapingWarpFrequency: 2\n"
        "      ShapingTerraceSteps: 0\n"
        "      ShapingTerraceSharpness: 0.6\n"
        "      ShapingHeightExponent: 1.3\n"
        "      AutoMaterial: true\n"
        "      SplatmapGenResolution: 256\n"
        "      LayerRules:\n"
        "        - LayerIndex: 0\n"
        "          MinHeight: 0\n"
        "          MaxHeight: 0.08\n"
        "          HeightBlend: 0.04\n"
        "          MinSlopeDeg: 0\n"
        "          MaxSlopeDeg: 30\n"
        "          SlopeBlend: 8\n"
        "          Strength: 1\n"
        "        - LayerIndex: 1\n"
        "          MinHeight: 0.04\n"
        "          MaxHeight: 0.88\n"
        "          HeightBlend: 0.1\n"
        "          MinSlopeDeg: 0\n"
        "          MaxSlopeDeg: 32\n"
        "          SlopeBlend: 8\n"
        "          Strength: 1\n"
        "        - LayerIndex: 2\n"
        "          MinHeight: 0\n"
        "          MaxHeight: 1\n"
        "          HeightBlend: 0\n"
        "          MinSlopeDeg: 34\n"
        "          MaxSlopeDeg: 90\n"
        "          SlopeBlend: 10\n"
        "          Strength: 1\n"
        "        - LayerIndex: 3\n"
        "          MinHeight: 0.9\n"
        "          MaxHeight: 1\n"
        "          HeightBlend: 0.08\n"
        "          MinSlopeDeg: 0\n"
        "          MaxSlopeDeg: 45\n"
        "          SlopeBlend: 10\n"
        "          Strength: 1\n"
        "      TessellationEnabled: false\n"
        "      TargetTriangleSize: 8\n"
        "      MorphRegion: 0.3\n"
        "      StreamingEnabled: false\n"
        "      TileDirectory: \"\"\n"
        "      TileFilePattern: tile_%d_%d.raw\n"
        "      TileWorldSize: 256\n"
        "      TileResolution: 513\n"
        "      StreamingLoadRadius: 3\n"
        "      StreamingMaxTiles: 25\n"
        "      VoxelEnabled: false\n"
        "      VoxelSize: 1\n"
        "      SplatmapPath0: \"\"\n"
        "      SplatmapPath1: \"\"\n"
        "      Layers:\n"
        "        - Name: Sand\n"
        "          AlbedoPath: \"\"\n"
        "          NormalPath: \"\"\n"
        "          ARMPath: \"\"\n"
        "          TilingScale: 16\n"
        "          HeightBlendSharpness: 4\n"
        "          TriplanarSharpness: 8\n"
        "          BaseColor: [0.76, 0.7, 0.5]\n"
        "          Roughness: 0.95\n"
        "          Metallic: 0\n"
        "        - Name: Grass\n"
        "          AlbedoPath: \"\"\n"
        "          NormalPath: \"\"\n"
        "          ARMPath: \"\"\n"
        "          TilingScale: 20\n"
        "          HeightBlendSharpness: 4\n"
        "          TriplanarSharpness: 8\n"
        "          BaseColor: [0.28, 0.45, 0.17]\n"
        "          Roughness: 0.9\n"
        "          Metallic: 0\n"
        "        - Name: Rock\n"
        "          AlbedoPath: \"\"\n"
        "          NormalPath: \"\"\n"
        "          ARMPath: \"\"\n"
        "          TilingScale: 12\n"
        "          HeightBlendSharpness: 4\n"
        "          TriplanarSharpness: 8\n"
        "          BaseColor: [0.42, 0.4, 0.38]\n"
        "          Roughness: 0.8\n"
        "          Metallic: 0\n"
        "        - Name: Snow\n"
        "          AlbedoPath: \"\"\n"
        "          NormalPath: \"\"\n"
        "          ARMPath: \"\"\n"
        "          TilingScale: 18\n"
        "          HeightBlendSharpness: 4\n"
        "          TriplanarSharpness: 8\n"
        "          BaseColor: [0.92, 0.93, 0.96]\n"
        "          Roughness: 0.6\n"
        "          Metallic: 0\n"
        "    FoliageComponent:\n"
        "      Enabled: true\n"
        "      Layers:\n"
        "        - Name: Grass\n"
        "          MeshPath: \"\"\n"
        "          AlbedoPath: assets/textures/grass.png\n"
        "          Density: 5\n"
        "          SplatmapChannel: 1\n"
        "          MinSlopeAngle: 0\n"
        "          MaxSlopeAngle: 30\n"
        "          MinScale: 0.9\n"
        "          MaxScale: 1.8\n"
        "          MinHeight: 1.1\n"
        "          MaxHeight: 2.4\n"
        "          RandomRotation: true\n"
        "          ViewDistance: 170\n"
        "          FadeStartDistance: 135\n"
        "          WindStrength: 0.4\n"
        "          WindSpeed: 1.6\n"
        "          BaseColor: [0.3, 0.46, 0.16]\n"
        "          Roughness: 0.8\n"
        "          AlphaCutoff: 0.5\n"
        "          Enabled: true\n"
        "        - Name: Pines\n"
        "          MeshPath: SandboxProject/Assets/Models/Vegetation/pine.obj\n"
        "          AlbedoPath: assets/textures/grass.png\n"
        "          Density: 0.02\n"
        "          SplatmapChannel: 1\n"
        "          MinSlopeAngle: 0\n"
        "          MaxSlopeAngle: 35\n"
        "          MinScale: 0.9\n"
        "          MaxScale: 1.4\n"
        "          MinHeight: 7\n"
        "          MaxHeight: 12\n"
        "          RandomRotation: true\n"
        "          ViewDistance: 700\n"
        "          FadeStartDistance: 600\n"
        "          WindStrength: 0.18\n"
        "          WindSpeed: 0.8\n"
        "          BaseColor: [0.19, 0.33, 0.2]\n"
        "          Roughness: 0.8\n"
        "          AlphaCutoff: 0.5\n"
        "          UseImpostor: true\n"
        "          ImpostorStartDistance: 30\n"
        "          ImpostorTransitionBand: 18\n"
        "          ImpostorFramesPerAxis: 8\n"
        "          ImpostorAtlasResolution: 1024\n"
        "          ImpostorHemiOctahedral: true\n"
        "          Enabled: true\n"
        "        - Name: Palms\n"
        "          MeshPath: SandboxProject/Assets/Models/Vegetation/palm.obj\n"
        "          AlbedoPath: assets/textures/grass.png\n"
        "          Density: 0.012\n"
        "          SplatmapChannel: 0\n"
        "          MinSlopeAngle: 0\n"
        "          MaxSlopeAngle: 25\n"
        "          MinScale: 0.9\n"
        "          MaxScale: 1.3\n"
        "          MinHeight: 6\n"
        "          MaxHeight: 10\n"
        "          RandomRotation: true\n"
        "          ViewDistance: 700\n"
        "          FadeStartDistance: 600\n"
        "          WindStrength: 0.3\n"
        "          WindSpeed: 1.1\n"
        "          BaseColor: [0.25, 0.42, 0.2]\n"
        "          Roughness: 0.8\n"
        "          AlphaCutoff: 0.5\n"
        "          UseImpostor: true\n"
        "          ImpostorStartDistance: 30\n"
        "          ImpostorTransitionBand: 18\n"
        "          ImpostorFramesPerAxis: 8\n"
        "          ImpostorAtlasResolution: 1024\n"
        "          ImpostorHemiOctahedral: true\n"
        "          Enabled: true\n"
    )


def tower_ring(rng, n=48, cx=60.0, cz=0.0, r_min=420.0, r_max=520.0):
    # One InstancedMeshComponent (InstancingDemo layout): column-major mat4
    # rows [c*sx, 0, sin*sx, 0, 0, sy, 0, 0, -sin*sz, 0, c*sz, 0, tx, ty, tz, 1]
    # (Y-yaw * nonuniform scale). Unit cube primitive is centred, so
    # ty = sy/2 + ground top (-0.45).
    header = (
        "    InstancedMeshComponent:\n"
        "      Primitive: 1\n"
        "      FrustumCullPerInstance: true\n"
        "      CastShadows: false\n"
        "      CullDistance: 0\n"
        "      Instances:\n"
    )
    rows = []
    for i in range(n):
        ang = (i / n) * 2.0 * math.pi + rng.uniform(-0.03, 0.03)
        radius = rng.uniform(r_min, r_max)
        tx = cx + radius * math.cos(ang)
        tz = cz + radius * math.sin(ang)
        sx = rng.uniform(14.0, 26.0)
        sz = rng.uniform(14.0, 26.0)
        sy = rng.uniform(35.0, 85.0)
        ty = sy / 2.0 - 0.45
        yaw = rng.uniform(0.0, math.pi)
        c, s = math.cos(yaw), math.sin(yaw)
        shade = rng.uniform(0.35, 0.55)
        col = (shade * 0.9, shade * 0.95, shade * 1.05)
        rows.append(
            f"        - Transform: [{f(c * sx)}, 0, {f(s * sx)}, 0, "
            f"0, {f(sy)}, 0, 0, "
            f"{f(-s * sz)}, 0, {f(c * sz)}, 0, "
            f"{f(tx)}, {f(ty)}, {f(tz)}, 1]\n"
            f"          Color: [{f(col[0])}, {f(col[1])}, {f(col[2])}, 1]\n"
        )
    return header + "".join(rows)


# --- scene assembly ----------------------------------------------------------

def build():
    rng = random.Random(SEED)
    w = SceneWriter()

    # In-scene primary camera (Play mode / AssetSceneLoad requirement). The
    # capture manifests pose the EDITOR camera themselves; this one mirrors
    # the golden view: west end, looking east (+X) down the atrium.
    w.entity("Camera", (-11.5, 3.4, 1.8), (-0.08, 1.5008, 0), (1, 1, 1),
             camera(),
             comment="── Camera: west end, down the atrium long axis ──")

    w.entity("Skybox", components=environment_map(),
             comment="── Skybox + IBL (Newport Loft, matches the Sponza scenes) ──")

    w.entity("Sun", components=dir_light(),
             comment="── Low sun down the atrium: long shadows + fog shafts ──")

    w.entity("Sponza", components=model("SandboxProject/Assets/Models/Sponza/Sponza.gltf"),
             comment="── Sponza: opaque + alpha-masked architecture ──")

    w.entity("DDGI Probe Volume", components=light_probe_volume(),
             comment="── Realtime DDGI volume covering the atrium interior ──")

    w.entity("Ground Skirt", (60, -0.45, 0), (0, 0, 0), (1250, 1, 1250),
             mesh(3) + material([0.32, 0.34, 0.3], 0.0, 0.95),
             comment="── Ground skirt under garden + tower ring (fog receiver) ──")

    w.entity("Garden Terrain", (24, -0.2, -96), (0, 0, 0), (1, 1, 1),
             terrain_and_foliage(),
             comment="── Procedural garden terrain + wind-swayed foliage, east of the atrium (corner-origin tile: x 24..216, z -96..96) ──")

    w.entity("Distant Towers", (0, 0, 0), (0, 0, 0), (1, 1, 1),
             tower_ring(rng),
             comment="── 48 instanced massing towers, radius ~420-520: geometry at depth for fog + culling ──")

    # ── Decals: one per DecalMode on the atrium floor (DecalModeMatrixTest
    #    shape). Kept off the fountain (x ~ 0).
    checker = "Assets/Textures/Checkerboard.png"
    w.entity("Decal Albedo", (-8.5, 0.05, 0.8), (0, 0, 0), (1, 1, 1),
             decal([0.9, 0.3, 0.2, 1], [3, 2, 3], 0, albedo_tex=checker),
             comment="── Decal mode matrix on the atrium floor: Albedo / Normal / RMA / Emissive ──")
    w.entity("Decal Normal", (-5, 0.05, 0.8), (0, 0, 0), (1, 1, 1),
             decal([1, 1, 1, 1], [3, 2, 3], 1))
    w.entity("Decal RMA", (3.5, 0.05, 0.8), (0, 0, 0), (1, 1, 1),
             decal([1, 1, 1, 1], [3, 2, 3], 2))
    w.entity("Decal Emissive", (7, 0.05, 0.8), (0, 0, 0), (1, 1, 1),
             decal([0.2, 0.9, 1, 1], [3, 2, 3], 3, emissive_tex=checker))

    # ── 6 shadow-casting point lights on the atrium centre-line.
    for i, x in enumerate((-10, -6, -2, 2, 6, 10)):
        warm = i % 2 == 0
        col = (1, 0.75, 0.45) if warm else (0.55, 0.75, 1)
        w.entity(f"PLight Shadow {i}", (x, 2.4, 0), (0, 0, 0), (1, 1, 1),
                 point_light(col, 7, 9, cast_shadows=True),
                 comment=("── 6 shadow-casting points, atrium centre-line ──"
                          if i == 0 else None))

    # ── 12 spot lights: 8 gallery spots aimed down-inward (4 shadowed),
    #    4 garden spots over the terrain.
    idx = 0
    for zi, z in enumerate((-4.2, 4.2)):
        inward = 0.55 if z < 0 else -0.55
        for xi, x in enumerate((-9, -4.5, 0, 4.5)):
            tilt = 0.12 if xi % 2 == 0 else -0.12
            shadowed = idx % 2 == 0  # 4 of the 8
            col = (1, 0.9, 0.7) if zi == 0 else (0.7, 0.85, 1)
            w.entity(f"Spot Gallery {idx}", (x, 7.2, z), (0, 0, 0), (1, 1, 1),
                     spot_light((tilt, -1, inward), col, 10, 14, 16, 28,
                                cast_shadows=shadowed),
                     comment=("── 8 gallery spots aimed into the atrium (alternating CastShadows) ──"
                              if idx == 0 else None))
            idx += 1
    garden_spots = ((50, -30), (90, 25), (130, -20), (170, 35))
    for i, (x, z) in enumerate(garden_spots):
        w.entity(f"Spot Garden {i}", (x, 9, z), (0, 0, 0), (1, 1, 1),
                 spot_light((0.1, -1, 0.05), (0.85, 0.95, 1), 9, 25, 18, 32),
                 comment=("── 4 garden spots over the foliage terrain ──"
                          if i == 0 else None))

    # ── 16 unshadowed garden point lights scattered over the terrain.
    for i in range(16):
        x = rng.uniform(35, 200)
        z = rng.uniform(-80, 80)
        col = PALETTE[i % len(PALETTE)]
        w.entity(f"PLight Garden {i}", (x, 5.5, z), (0, 0, 0), (1, 1, 1),
                 point_light(col, 5, 12),
                 comment=("── 16 colored garden points over the foliage ──"
                          if i == 0 else None))

    # ── 120 colored point lights: the SponzaForwardPlus 6x4x5 atrium grid.
    xs = (-12, -7.2, -2.4, 2.4, 7.2, 12)
    zs = (-4.5, -1.5, 1.5, 4.5)
    ys = (0.6, 3, 6.5, 10.5, 14)
    n = 0
    for y in ys:
        for z in zs:
            for x in xs:
                col = PALETTE[n % len(PALETTE)]
                w.entity(f"PLight Grid {n}", (x, y, z), (0, 0, 0), (1, 1, 1),
                         point_light(col, 4.5, 6.5),
                         comment=("── 120 colored points: 6x4x5 atrium grid (SponzaForwardPlus layout) ──"
                                  if n == 0 else None))
                n += 1

    return w


def main():
    ap = argparse.ArgumentParser(
        description="Generate the Courtyard benchmark scene (.olo, issue #974)")
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    w = build()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(w.text(), encoding="utf-8", newline="\n")
    print(f"{args.out} ({w.count} entities)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
