#!/usr/bin/env python3
# =============================================================================
# generate_reference_fixture_scenes.py
#
# Emits the five REFERENCE FIXTURE scenes for issue #1239:
#   OloEditor/SandboxProject/Assets/Scenes/Benchmark/
#     ReferenceHead.olo      a head-scale subject under a pinned studio rig
#     AnimalShortCoat.olo    Khronos Fox — skinned, animated, short coat
#     AnimalLongCoat.olo     procedural long-coated quadruped stand-in
#     Meadow.olo             open grass/flower field, wind-driven
#     Woodland.olo           dense tree canopy with impostors, wind-driven
#
# WHAT THESE FIXTURES ARE FOR
# ---------------------------
# They are the measuring instrument for the AAA characters-and-flora epic
# (#1225), not a showcase. Issue #1239's own scope boundary: "Fixtures
# initially show current limitations and are upgraded by feature owners."
#
# So the head has no subsurface scattering, the long coat is a solid shell,
# and the meadow is alpha-masked billboards — because that is what the engine
# does TODAY. Each of those is the baseline that #1230, #1232, #1241, #1244,
# #1246, #1251, #1254 and #1258 will be measured against. Improving a fixture
# to make its capture look better destroys the baseline it exists to record.
#
# Like generate_courtyard_scene.py, these scenes are COMMITTED and this
# generator exists because the foliage layer tables and the lighting rigs are
# unmaintainable by hand — not because they are regenerated per run. Output is
# byte-stable: fixed seed, deterministic float formatting, no timestamps.
#
#   python OloEngine/tests/scripts/generate_reference_fixture_scenes.py
#
# Every YAML key below is either verified against SceneSerializer.cpp or
# copied from a committed scene that uses it (fox.olo, PBRReference.olo,
# Courtyard.olo, FoliageGenerationTest.olo, Drift.olo).
# =============================================================================

import argparse
import math
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
SCENE_DIR = REPO_ROOT / "OloEditor" / "SandboxProject" / "Assets" / "Scenes" / "Benchmark"

SEED = 1239


def f(x):
    """Compact float formatting: 4 significant decimals, no trailing zeros."""
    s = f"{x:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(v):
    return "[" + ", ".join(f(c) for c in v) + "]"


# =============================================================================
# Scene assembly
# =============================================================================

class SceneWriter:
    def __init__(self, name, id_base, header_note, settings):
        self.name = name
        self.parts = []
        self.next_id = id_base
        self.count = 0
        self.header_note = header_note
        self.settings = settings

    def entity(self, tag, translation=(0, 0, 0), rotation=(0, 0, 0),
               scale=(1, 1, 1), components="", comment=None):
        eid = self.next_id
        self.next_id += 1
        self.count += 1
        if comment:
            self.parts.append(f"  # {comment}\n")
        self.parts.append(
            f"  - Entity: {eid}\n"
            f"    TagComponent:\n"
            f"      Tag: {tag}\n"
            f"    TransformComponent:\n"
            f"      Translation: {vec(translation)}\n"
            f"      Rotation: {vec(rotation)}\n"
            f"      Scale: {vec(scale)}\n"
            + components
        )
        return eid

    def text(self):
        # A blank note line emits a bare "#", never "# " — pre-commit's
        # trailing-whitespace hook would strip the space and the committed
        # scene would stop matching this generator's output byte for byte,
        # which is the property that makes "regenerate and diff" meaningful.
        def comment(line):
            return f"# {line}\n" if line else "#\n"

        header = (
            f"Scene: {self.name}.olo\n"
            "# ─────────────────────────────────────────────────────────────────────────────\n"
            + comment(self.header_note[0])
        )
        for line in self.header_note[1:]:
            header += comment(line)
        header += (
            "#\n"
            "# GENERATED by OloEngine/tests/scripts/generate_reference_fixture_scenes.py\n"
            "# (issue #1239) — edit the generator and regenerate rather than hand-editing.\n"
            "# ─────────────────────────────────────────────────────────────────────────────\n"
        )
        return header + self.settings + "Entities:\n" + "".join(self.parts)


# =============================================================================
# Component snippets (4-space indent = component key level)
# =============================================================================

def camera(fov=0.785398185, near=0.05, far=1000.0):
    return (
        "    CameraComponent:\n"
        "      Camera:\n"
        "        ProjectionType: 0\n"
        f"        PerspectiveFOV: {f(fov)}\n"
        f"        PerspectiveNear: {f(near)}\n"
        f"        PerspectiveFar: {f(far)}\n"
        "        OrthographicSize: 10\n"
        "        OrthographicNear: -1\n"
        "        OrthographicFar: 1\n"
        "      Primary: true\n"
        "      FixedAspectRatio: false\n"
    )


def environment_map(path="assets/textures/hdr/newport_loft.hdr", ibl=0.5,
                    skybox=True, is_folder=False, rotation=0.0):
    return (
        "    EnvironmentMapComponent:\n"
        f"      FilePath: {path}\n"
        f"      IsCubemapFolder: {'true' if is_folder else 'false'}\n"
        f"      EnableSkybox: {'true' if skybox else 'false'}\n"
        f"      Rotation: {f(rotation)}\n"
        "      Exposure: 1\n"
        "      BlurAmount: 0\n"
        "      EnableIBL: true\n"
        f"      IBLIntensity: {f(ibl)}\n"
        "      Tint: [1, 1, 1]\n"
    )


def procedural_sky(sun_direction, turbidity=2.6, ibl=0.9, exposure=0.10):
    """Physically-based sky instead of an HDR probe, for the OUTDOOR fixtures.

    Two reasons, and the second is the important one:
      * the first capture of the meadow rendered the Newport Loft interior
        CEILING above the grass, because an indoor probe is an indoor probe;
      * a procedural sky carries NO third-party rights at all, so the
        vegetation fixtures' provenance lists shrink to assets this repository
        actually owns. The head and animal fixtures keep the HDR because a
        studio probe is what a studio rig wants.

    SunDirection points TOWARD the sun, the opposite convention to
    DirectionalLightComponent::Direction (which is where the light travels).
    The caller passes the negated light direction so the sky's sun disk sits
    where the shadows say it should — otherwise the backlit camera looks into
    an empty patch of sky.
    """
    return (
        "    ProceduralSkyComponent:\n"
        f"      SunDirection: {vec(sun_direction)}\n"
        f"      Turbidity: {f(turbidity)}\n"
        f"      Exposure: {f(exposure)}\n"
        "      SunIntensity: 1\n"
        "      SunDiskSize: 1\n"
        "      ShowSunDisk: true\n"
        "      EnableSkybox: true\n"
        "      EnableIBL: true\n"
        f"      IBLIntensity: {f(ibl)}\n"
        "      CubemapResolution: 256\n"
    )


def dir_light(direction, color=(1, 0.95, 0.88), intensity=3.0, shadows=True,
              max_shadow_distance=120.0, cascade_lambda=0.92):
    return (
        "    DirectionalLightComponent:\n"
        f"      Direction: {vec(direction)}\n"
        f"      Color: {vec(color)}\n"
        f"      Intensity: {f(intensity)}\n"
        f"      CastShadows: {'true' if shadows else 'false'}\n"
        "      ShadowDepthBiasTexels: 2\n"
        # Engine default (0.01), deliberately NOT the 0.1 the sample scenes
        # author: a 10x normal bias detaches contact shadows from their caster
        # (#1119), which would corrupt the very thing a head fixture measures.
        "      ShadowNormalBias: 0.01\n"
        f"      MaxShadowDistance: {f(max_shadow_distance)}\n"
        f"      CascadeSplitLambda: {f(cascade_lambda)}\n"
        "      CascadeDebugVisualization: false\n"
    )


def point_light(color, intensity, range_, cast_shadows=False):
    # Every field is written out, defaults included: a benchmark fixture's
    # lighting is part of the measurement, so "what was Attenuation?" must be
    # answerable from the scene file rather than from the engine's defaults at
    # the time the capture happened.
    return (
        "    PointLightComponent:\n"
        f"      Color: {vec(color)}\n"
        f"      Intensity: {f(intensity)}\n"
        f"      Range: {f(range_)}\n"
        "      Attenuation: 1\n"
        f"      CastShadows: {'true' if cast_shadows else 'false'}\n"
        "      ShadowBias: 0.005\n"
        "      ShadowNormalBias: 0.01\n"
    )


def model(path):
    return (
        "    ModelComponent:\n"
        f"      FilePath: {path}\n"
        "      Visible: true\n"
    )


def mesh(primitive):
    return f"    MeshComponent:\n      Primitive: {primitive}\n"


def material(albedo, metallic=0.0, roughness=0.9):
    return (
        "    MaterialComponent:\n"
        f"      AlbedoColor: {vec(albedo)}\n"
        f"      Metallic: {f(metallic)}\n"
        f"      Roughness: {f(roughness)}\n"
    )


def animated_model(source_path, clip_index=0, playing=True, blend=0.3):
    """Skinned model + skeleton + playback state.

    SourceFilePath is relative to Project::GetAssetDirectory()
    (OloEditor/SandboxProject/Assets), which is why the editor-tree models
    reach out through `../../assets/` — the shape fox.olo uses.
    SceneSerializer's animated branch calls ModelImporter::PopulateAnimatedEntity,
    which fills in MeshComponent / SkeletonComponent / MaterialComponent from
    the file, so the empty maps below are placeholders the loader overwrites.
    """
    return (
        "    MeshComponent:\n"
        "      {}\n"
        "    AnimationStateComponent:\n"
        "      State: 0\n"
        "      CurrentTime: 0\n"
        f"      BlendDuration: {f(blend)}\n"
        f"      CurrentClipIndex: {clip_index}\n"
        f"      IsPlaying: {'true' if playing else 'false'}\n"
        f"      SourceFilePath: {source_path}\n"
        "    SkeletonComponent:\n"
        "      {}\n"
    )


# =============================================================================
# Scene-level settings blocks
# =============================================================================

def settings(ssao=True, ssr=False, ssgi=False, bloom=0.3, tonemap=2,
             fog=None, wind=None, motion_blur=False):
    """PostProcessSettings (+ optional Fog/Wind). Key spellings from
    SceneSerializer.cpp's TrySet lists.

    FXAA is off in every fixture: a benchmark frame must be AA-free so the
    capture measures the renderer, not a post filter, and TAA is pinned from
    the capture manifest instead (it is not scene-serialized).
    AutoExposure is off so every fixture shares one fixed exposure and their
    numbers are comparable.
    """
    s = (
        "PostProcessSettings:\n"
        f"  TonemapOperator: {tonemap}\n"
        "  Exposure: 1\n"
        "  Gamma: 2.2\n"
        f"  BloomEnabled: {'true' if bloom > 0 else 'false'}\n"
        "  BloomThreshold: 1.2\n"
        f"  BloomIntensity: {f(bloom)}\n"
        "  BloomIterations: 5\n"
        "  VignetteEnabled: false\n"
        "  VignetteIntensity: 0.5\n"
        "  VignetteSmoothness: 0.2\n"
        "  ChromaticAberrationEnabled: false\n"
        "  ChromaticAberrationIntensity: 0.5\n"
        "  FXAAEnabled: false\n"
        "  DOFEnabled: false\n"
        "  DOFFocusDistance: 10\n"
        "  DOFFocusRange: 5\n"
        "  DOFBokehRadius: 3\n"
        f"  MotionBlurEnabled: {'true' if motion_blur else 'false'}\n"
        "  MotionBlurStrength: 0.5\n"
        "  MotionBlurSamples: 4\n"
        "  ColorGradingEnabled: false\n"
        f"  SSAOEnabled: {'true' if ssao else 'false'}\n"
        "  SSAORadius: 0.35\n"
        "  SSAOBias: 0.025\n"
        "  SSAOIntensity: 1\n"
        "  SSAOSamples: 32\n"
        "  SSAODebugView: false\n"
        f"  SSREnabled: {'true' if ssr else 'false'}\n"
        "  SSRMaxDistance: 40\n"
        "  SSRThickness: 0.9\n"
        "  SSRStride: 0.22\n"
        "  SSRMaxSteps: 96\n"
        "  SSRBinarySearchSteps: 6\n"
        "  SSRIntensity: 1\n"
        "  SSRMaxRoughness: 0.6\n"
        "  SSREdgeFade: 0.1\n"
        "  SSRDebugView: false\n"
        "  SSRTemporalResolve: true\n"
        f"  SSGIEnabled: {'true' if ssgi else 'false'}\n"
        "  SSGIIntensity: 1.2\n"
        "  SSGIMaxDistance: 20\n"
        "  SSGIThickness: 1.5\n"
        "  SSGIStride: 0.5\n"
        "  SSGIMaxSteps: 32\n"
        "  SSGIRayCount: 16\n"
        "  SSGIEdgeFade: 0.1\n"
        "  SSGIDebugView: false\n"
        "  SSGITemporalResolve: true\n"
        "  AutoExposureEnabled: false\n"
    )
    if fog:
        s += fog
    if wind:
        s += wind
    return s


NO_FOG = (
    "FogSettings:\n"
    "  Enabled: false\n"
    "  Mode: 1\n"
    "  Color: [0.5, 0.55, 0.62]\n"
    "  Density: 0\n"
    "  Start: 0\n"
    "  End: 500\n"
    "  HeightFalloff: 0.35\n"
    "  HeightOffset: 0\n"
    "  MaxOpacity: 0\n"
    "  EnableScattering: false\n"
    "  EnableVolumetric: false\n"
    "  EnableNoise: false\n"
    "  EnableLightShafts: false\n"
)

OUTDOOR_FOG = (
    "FogSettings:\n"
    "  Enabled: true\n"
    "  Mode: 1\n"
    "  Color: [0.62, 0.68, 0.76]\n"
    "  Density: 0.008\n"
    "  Start: 0\n"
    "  End: 420\n"
    "  HeightFalloff: 0.4\n"
    "  HeightOffset: 0\n"
    "  MaxOpacity: 0.65\n"
    "  EnableScattering: true\n"
    "  RayleighStrength: 0.5\n"
    "  MieStrength: 0.02\n"
    "  MieDirectionality: 0.72\n"
    "  RayleighColor: [0.27, 0.51, 0.83]\n"
    "  SunIntensity: 4\n"
    "  EnableVolumetric: true\n"
    "  VolumetricSamples: 48\n"
    "  AbsorptionCoefficient: 0.01\n"
    "  EnableNoise: true\n"
    "  NoiseScale: 0.05\n"
    "  NoiseSpeed: 0.35\n"
    "  NoiseIntensity: 0.4\n"
    "  EnableLightShafts: true\n"
    "  LightShaftIntensity: 1.1\n"
)


def wind_settings(enabled, speed=6.0, gust=0.45, direction=(0.85, 0, 0.35)):
    """Wind drives foliage sway, and (issue #974) reads the MOCK clock, so a
    fixed-dt capture reproduces the same bend frame for frame."""
    return (
        "WindSettings:\n"
        f"  Enabled: {'true' if enabled else 'false'}\n"
        f"  Direction: {vec(direction)}\n"
        f"  Speed: {f(speed)}\n"
        f"  GustStrength: {f(gust)}\n"
        "  GustFrequency: 0.7\n"
        "  TurbulenceIntensity: 0.45\n"
        "  TurbulenceScale: 0.12\n"
        "  GridWorldSize: 256\n"
        "  GridResolution: 128\n"
    )


# =============================================================================
# Terrain + foliage (shared by Meadow and Woodland)
# =============================================================================

def terrain(world_size, height_scale, seed, layers, layer_rules):
    s = (
        "    TerrainComponent:\n"
        '      HeightmapPath: ""\n'
        f"      WorldSizeX: {f(world_size)}\n"
        f"      WorldSizeZ: {f(world_size)}\n"
        f"      HeightScale: {f(height_scale)}\n"
        "      ProceduralEnabled: true\n"
        f"      ProceduralSeed: {seed}\n"
        "      ProceduralResolution: 256\n"
        "      ProceduralOctaves: 5\n"
        "      ProceduralFrequency: 2\n"
        "      ProceduralLacunarity: 2\n"
        "      ProceduralPersistence: 0.45\n"
        "      ShapingRidgeBlend: 0\n"
        "      ShapingWarpStrength: 0.12\n"
        "      ShapingWarpFrequency: 2\n"
        "      ShapingTerraceSteps: 0\n"
        "      ShapingTerraceSharpness: 0.6\n"
        "      ShapingHeightExponent: 1.2\n"
        "      AutoMaterial: true\n"
        "      SplatmapGenResolution: 256\n"
        "      LayerRules:\n"
    )
    for rule in layer_rules:
        s += (
            f"        - LayerIndex: {rule['index']}\n"
            f"          MinHeight: {f(rule['min_h'])}\n"
            f"          MaxHeight: {f(rule['max_h'])}\n"
            f"          HeightBlend: {f(rule['h_blend'])}\n"
            f"          MinSlopeDeg: {f(rule['min_slope'])}\n"
            f"          MaxSlopeDeg: {f(rule['max_slope'])}\n"
            "          SlopeBlend: 8\n"
            "          Strength: 1\n"
        )
    s += (
        "      TessellationEnabled: false\n"
        "      TargetTriangleSize: 8\n"
        "      MorphRegion: 0.3\n"
        "      StreamingEnabled: false\n"
        '      TileDirectory: ""\n'
        "      TileFilePattern: tile_%d_%d.raw\n"
        "      TileWorldSize: 256\n"
        "      TileResolution: 513\n"
        "      StreamingLoadRadius: 3\n"
        "      StreamingMaxTiles: 25\n"
        "      VoxelEnabled: false\n"
        "      VoxelSize: 1\n"
        '      SplatmapPath0: ""\n'
        '      SplatmapPath1: ""\n'
        "      Layers:\n"
    )
    for layer in layers:
        s += (
            f"        - Name: {layer['name']}\n"
            '          AlbedoPath: ""\n'
            '          NormalPath: ""\n'
            '          ARMPath: ""\n'
            f"          TilingScale: {f(layer['tiling'])}\n"
            "          HeightBlendSharpness: 4\n"
            "          TriplanarSharpness: 8\n"
            f"          BaseColor: {vec(layer['color'])}\n"
            f"          Roughness: {f(layer['roughness'])}\n"
            "          Metallic: 0\n"
        )
    return s


def foliage(layers):
    s = "    FoliageComponent:\n      Enabled: true\n      Layers:\n"
    for lay in layers:
        s += (
            f"        - Name: {lay['name']}\n"
            f"          MeshPath: {lay.get('mesh', '\"\"')}\n"
            f"          AlbedoPath: {lay['albedo']}\n"
            f"          Density: {f(lay['density'])}\n"
            f"          SplatmapChannel: {lay['channel']}\n"
            f"          MinSlopeAngle: {f(lay.get('min_slope', 0))}\n"
            f"          MaxSlopeAngle: {f(lay.get('max_slope', 32))}\n"
            f"          MinScale: {f(lay['min_scale'])}\n"
            f"          MaxScale: {f(lay['max_scale'])}\n"
            f"          MinHeight: {f(lay['min_height'])}\n"
            f"          MaxHeight: {f(lay['max_height'])}\n"
            "          RandomRotation: true\n"
            f"          ViewDistance: {f(lay['view_distance'])}\n"
            f"          FadeStartDistance: {f(lay['fade_start'])}\n"
            f"          WindStrength: {f(lay['wind_strength'])}\n"
            f"          WindSpeed: {f(lay['wind_speed'])}\n"
            f"          BaseColor: {vec(lay['color'])}\n"
            "          Roughness: 0.8\n"
            "          AlphaCutoff: 0.5\n"
        )
        if lay.get("impostor"):
            s += (
                "          UseImpostor: true\n"
                f"          ImpostorStartDistance: {f(lay['impostor_start'])}\n"
                "          ImpostorTransitionBand: 18\n"
                "          ImpostorFramesPerAxis: 8\n"
                "          ImpostorAtlasResolution: 1024\n"
                "          ImpostorHemiOctahedral: true\n"
            )
        s += "          Enabled: true\n"
    return s


GRASS_TEX = "assets/textures/grass.png"
PINE = "SandboxProject/Assets/Models/Vegetation/pine.obj"
PALM = "SandboxProject/Assets/Models/Vegetation/palm.obj"

MEADOW_TERRAIN_LAYERS = [
    {"name": "Soil", "tiling": 16, "color": (0.34, 0.28, 0.20), "roughness": 0.95},
    {"name": "Grass", "tiling": 22, "color": (0.30, 0.46, 0.18), "roughness": 0.9},
    {"name": "Rock", "tiling": 12, "color": (0.42, 0.40, 0.38), "roughness": 0.8},
    {"name": "DryGrass", "tiling": 20, "color": (0.52, 0.48, 0.26), "roughness": 0.9},
]

WOODLAND_TERRAIN_LAYERS = [
    {"name": "Soil", "tiling": 16, "color": (0.26, 0.20, 0.14), "roughness": 0.95},
    {"name": "Needles", "tiling": 22, "color": (0.24, 0.28, 0.16), "roughness": 0.92},
    {"name": "Rock", "tiling": 12, "color": (0.38, 0.37, 0.35), "roughness": 0.8},
    {"name": "Moss", "tiling": 20, "color": (0.22, 0.34, 0.18), "roughness": 0.9},
]

TERRAIN_RULES = [
    {"index": 0, "min_h": 0, "max_h": 0.10, "h_blend": 0.05, "min_slope": 0, "max_slope": 30},
    {"index": 1, "min_h": 0.05, "max_h": 0.85, "h_blend": 0.12, "min_slope": 0, "max_slope": 32},
    {"index": 2, "min_h": 0, "max_h": 1, "h_blend": 0, "min_slope": 34, "max_slope": 90},
    {"index": 3, "min_h": 0.80, "max_h": 1, "h_blend": 0.10, "min_slope": 0, "max_slope": 45},
]


WOODLAND_RULES = [
    {"index": 0, "min_h": 0, "max_h": 0.35, "h_blend": 0.12, "min_slope": 0, "max_slope": 34},
    {"index": 1, "min_h": 0.15, "max_h": 1.0, "h_blend": 0.18, "min_slope": 0, "max_slope": 34},
    {"index": 2, "min_h": 0, "max_h": 1, "h_blend": 0, "min_slope": 36, "max_slope": 90},
    {"index": 3, "min_h": 0, "max_h": 0.22, "h_blend": 0.10, "min_slope": 0, "max_slope": 18},
]

# =============================================================================
# The five fixtures
# =============================================================================

HEAD_NOTE = [
    "REFERENCE HEAD fixture (issue #1239).",
    "",
    "Two head-scale subjects under one pinned studio rig, so the capture",
    "separates SHAPE response from TEXTURE response:",
    "  * Suzanne (CC0) — smooth organic head geometry. Measures silhouette,",
    "    grazing-angle specular and backlit rim on an untextured surface.",
    "  * DamagedHelmet (CC-BY 4.0) — 2K albedo/normal/metal-rough/AO/emissive.",
    "    Measures the same rig's response to real PBR texture detail.",
    "",
    "CURRENT LIMITATION THIS FIXTURE RECORDS: there is no subsurface",
    "scattering, no eye shader and no groom in the engine today, so neither",
    "subject is a photoreal human head. A scanned AAA head is a genuine",
    "external dependency — see docs/guides/benchmark-reference-fixtures.md.",
    "The rig is built so that dropping a licensed head in its place changes",
    "the subject and nothing else.",
]

ANIMAL_NOTE_COMMON = [
    "",
    "Ground, sky and light rig are IDENTICAL to the other animal fixture, so",
    "the short- and long-coated captures differ only in the subject.",
]


def build_reference_head():
    w = SceneWriter(
        "ReferenceHead", 1_239_000_001_000_000, HEAD_NOTE,
        settings(ssao=True, ssr=True, ssgi=False, bloom=0.25, fog=NO_FOG,
                 wind=wind_settings(False)),
    )

    w.entity("Camera", (0, 1.1, 3.1), (-0.05, 0, 0), (1, 1, 1), camera(),
             comment="── Camera (scene camera; capture manifests pose the EDITOR camera) ──")
    # SKYBOX OFF, IBL ON. A visible environment turned the first capture of this
    # fixture into a photo of the Newport Loft interior with two heads in it:
    # the backlit camera read as "well lit from behind by a room", and no
    # lighting change was legible against a busy backdrop. A measurement fixture
    # wants a controlled background and a rig that drives the image, so the HDR
    # stays as the fill source and stops being the picture.
    w.entity("Skybox", components=environment_map(ibl=0.3, skybox=False),
             comment="── Studio IBL (Newport Loft HDR) — fill only, skybox NOT drawn ──")

    # Key light: high front-left, the only shadow caster. A single directional
    # keeps the shadow term unambiguous — two would make "which light made
    # this shadow?" unanswerable from a single AOV.
    # With the skybox off the rig has to carry the image, so the key and rim
    # are strong enough to read against an unlit background rather than being
    # a nudge on top of a bright environment.
    w.entity("Key Light", components=dir_light((-0.45, -0.8, -0.42), (1, 0.96, 0.90), 6.0,
                                               shadows=True, max_shadow_distance=30, cascade_lambda=0.85),
             comment="── Key: high front-right-above, sole shadow caster ──")
    # Rim/back light behind the subjects — what makes the BACKLIT camera a
    # real backlit shot rather than a dark one.
    w.entity("Rim Light", (0, 1.65, -1.9), components=point_light((0.82, 0.90, 1.0), 45.0, 7.0),
             comment="── Rim: behind and above, cool — the backlit camera's subject ──")
    w.entity("Fill Light", (1.9, 0.85, 1.9), components=point_light((1.0, 0.93, 0.84), 14.0, 8.0),
             comment="── Fill: low warm bounce, no shadows ──")

    # Subjects. Separation and scale are set so BOTH fit the 42-degree frontal
    # frame with margin: Suzanne is ~2.7 units wide before scaling, and the
    # first capture of this fixture clipped its left ear at +-1.15 / 0.55.
    for tag, x, yaw, path in (
        ("Suzanne", -0.95, 0.35, "assets/models/Suzanne/glTF/Suzanne.gltf"),
        ("DamagedHelmet", 0.95, -0.35, "assets/models/DamagedHelmet/glTF/DamagedHelmet.gltf"),
    ):
        w.entity(tag, (x, 1.05, 0), (0, yaw, 0), (0.5, 0.5, 0.5), model(path),
                 comment=("── Subject A: organic head geometry (Suzanne, CC0) ──" if x < 0 else
                          "── Subject B: textured PBR detail (DamagedHelmet, CC-BY 4.0) ──"))

    # Plinths + floor: mid-grey, matte, so the subjects own the frame.
    for tag, x in (("Plinth A", -0.95), ("Plinth B", 0.95)):
        w.entity(tag, (x, 0.33, 0), (0, 0, 0), (0.58, 0.66, 0.58),
                 mesh(1) + material((0.20, 0.20, 0.21), 0.0, 0.85))
    w.entity("Floor", (0, -0.02, 0), (0, 0, 0), (24, 0.04, 24),
             mesh(1) + material((0.16, 0.16, 0.17), 0.0, 0.75),
             comment="── Matte floor: contact shadow + a little bounce, no reflection show ──")
    return w


def build_animal(name, note, subject_components, subject_transform, subject_tag):
    w = SceneWriter(
        name,
        1_239_000_002_000_000 if name == "AnimalShortCoat" else 1_239_000_003_000_000,
        note,
        settings(ssao=True, ssr=False, ssgi=False, bloom=0.25, fog=NO_FOG,
                 wind=wind_settings(True, speed=4.0, gust=0.3)),
    )
    w.entity("Camera", (0, 0.8, 2.6), (-0.05, 0, 0), (1, 1, 1), camera(),
             comment="── Camera (scene camera; capture manifests pose the EDITOR camera) ──")
    # Skybox off for the same reason as the head fixture: the first capture of
    # these fixtures was a photograph of the Newport Loft window with a small
    # animal in front of it, and a blown-out background makes a coat silhouette
    # unjudgeable. The HDR stays as the fill source.
    w.entity("Skybox", components=environment_map(ibl=0.35, skybox=False),
             comment="── IBL fill only (Newport Loft HDR); skybox NOT drawn ──")
    # Low sun from behind-left: gives the grazing camera a long raking light
    # across the flank and the backlit camera a true rim.
    w.entity("Sun", components=dir_light((-0.55, -0.35, -0.76), (1, 0.92, 0.80), 5.5,
                                         shadows=True, max_shadow_distance=60, cascade_lambda=0.88),
             comment="── Low sun from behind-left: raking flank light + a real rim ──")
    w.entity("Fill Light", (2.6, 1.7, 2.8), components=point_light((0.85, 0.90, 1.0), 9.0, 10.0),
             comment="── Cool sky fill from the camera side ──")

    translation, rotation, scale = subject_transform
    w.entity(subject_tag, translation, rotation, scale, subject_components,
             comment="── THE SUBJECT ──")

    w.entity("Ground", (0, -0.02, 0), (0, 0, 0), (60, 0.04, 60),
             mesh(1) + material((0.24, 0.26, 0.18), 0.0, 0.92),
             comment="── Ground: matte earth, identical in both animal fixtures ──")
    return w


def build_animal_short_coat():
    note = [
        "SHORT-COATED ANIMAL fixture (issue #1239).",
        "",
        "Khronos Fox (glTF-Sample-Assets): skinned, three clips, coat painted",
        "into a single 1K albedo texture — which is exactly how a shipping",
        "short-coated character is authored, so this fixture is a REAL",
        "measurement rather than a stand-in.",
        "",
        "The Walk clip plays, driven by the capture manifest's fixed dt, so a",
        "moving-sequence camera sees genuine skinned deformation in the",
        "velocity buffer and not just camera parallax.",
        "",
        "Fox.gltf is authored in CENTIMETRES (bbox ~79 units tall), hence the",
        "0.01 scale — the units field in the manifest provenance block records",
        "this, because a silently mis-scaled subject invalidates every",
        "screen-coverage number taken from the capture.",
    ] + ANIMAL_NOTE_COMMON
    return build_animal(
        "AnimalShortCoat", note,
        animated_model("../../assets/models/Fox/Fox.gltf", clip_index=1, playing=True),
        # Fox.gltf is authored head-toward +Z (verified from the first capture of
        # this fixture, which showed its back and tail), so +90 degrees about Y
        # puts the head on +X where the frontal camera is looking.
        ((0, 0, 0), (0, math.pi / 2.0, 0), (0.01, 0.01, 0.01)),
        "Fox",
    )


def build_animal_long_coat():
    note = [
        "LONG-COATED ANIMAL fixture (issue #1239).",
        "",
        "A procedurally generated quadruped whose long coat is a SOLID OFFSET",
        "SHELL (Models/Reference/generate_reference_animals.py).",
        "",
        "THIS IS THE CURRENT-LIMITATION BASELINE, and it is meant to look like",
        "one: hard silhouette, no strand detail, no anisotropic specular, no",
        "wind response. Issues #1232 (groom curve assets) and #1241 replace the",
        "shell with real curves, and this capture is what they are measured",
        "against. Do not 'improve' the coat here.",
        "",
        "No rigged long-coated asset is obtainable without a purchase, so this",
        "subject is static where the short-coated Fox animates — the moving",
        "sequence for this fixture comes from the manifest's camera Motion.",
    ] + ANIMAL_NOTE_COMMON
    return build_animal(
        "AnimalLongCoat", note,
        model("SandboxProject/Assets/Models/Reference/longcoat-quadruped.obj")
        + material((0.46, 0.40, 0.32), 0.0, 0.78),
        ((0, 0, 0), (0, 0, 0), (1, 1, 1)),
        "LongCoatedQuadruped",
    )


MEADOW_NOTE = [
    "MEADOW vegetation fixture (issue #1239).",
    "",
    "An open 192 m field of dense alpha-masked grass and flower billboards over",
    "procedural terrain, with wind on.",
    "",
    "CURRENT LIMITATION THIS FIXTURE RECORDS: ground cover is CAMERA-FACING",
    "CARDS, not geometry. Expect the card silhouette to read at grazing angles,",
    "expect alpha-test aliasing under motion, and expect no self-shadowing",
    "within a clump. #1230 (foliage instance identity) and #1244 are measured",
    "against this capture — and #1230 is in flight on a sibling branch, so the",
    "fixture consumes the foliage system exactly as it is today.",
]

WOODLAND_NOTE = [
    "WOODLAND vegetation fixture (issue #1239).",
    "",
    "Dense pine/palm canopy with octahedral impostors over the same procedural",
    "terrain as the meadow, plus a grass understory. Wind on.",
    "",
    "The frame deliberately straddles the impostor cross-fade band, which is",
    "the transition a canopy fixture exists to measure: mesh in the near field,",
    "impostor cards beyond ImpostorStartDistance, and the blend between them.",
    "",
    "CURRENT LIMITATION THIS FIXTURE RECORDS: the trees are the two low-poly",
    "meshes generate_vegetation.py emits (a few dozen triangles each) because",
    "that is every tree this repository owns. Canopy density, not leaf detail,",
    "is what this capture measures honestly.",
]


def build_meadow():
    w = SceneWriter(
        "Meadow", 1_239_000_004_000_000, MEADOW_NOTE,
        settings(ssao=True, ssr=False, ssgi=False, bloom=0.3, fog=OUTDOOR_FOG,
                 wind=wind_settings(True, speed=7.0, gust=0.5)),
    )
    w.entity("Camera", (0, 2.0, 8.0), (-0.06, 0, 0), (1, 1, 1), camera(far=2000.0),
             comment="── Camera (scene camera; capture manifests pose the EDITOR camera) ──")
    w.entity("Sky", components=procedural_sky((0.62, 0.42, 0.66), turbidity=2.4, ibl=0.9),
             comment="── Procedural sky + IBL; sun disk aligned with the directional light ──")
    w.entity("Sun", components=dir_light((-0.62, -0.42, -0.66), (1, 0.94, 0.82), 5.0,
                                         shadows=True, max_shadow_distance=300, cascade_lambda=0.9),
             comment="── Low afternoon sun: long grass shadows, real backlight ──")

    # Terrain origin is a CORNER, so this tile spans [-96, 96] on both axes and
    # the fixture cameras can sit near the world origin.
    w.entity(
        "Meadow Terrain", (-96, 0, -96), (0, 0, 0), (1, 1, 1),
        terrain(192, 5.0, SEED, MEADOW_TERRAIN_LAYERS, TERRAIN_RULES)
        + foliage([
            {"name": "Grass", "albedo": GRASS_TEX, "density": 9.0, "channel": 1,
             "min_scale": 0.85, "max_scale": 1.7, "min_height": 0.9, "max_height": 1.9,
             "view_distance": 150, "fade_start": 120, "wind_strength": 0.55, "wind_speed": 1.8,
             "color": (0.32, 0.48, 0.17), "max_slope": 32},
            {"name": "TallGrass", "albedo": GRASS_TEX, "density": 3.5, "channel": 1,
             "min_scale": 1.2, "max_scale": 2.2, "min_height": 1.6, "max_height": 2.8,
             "view_distance": 170, "fade_start": 135, "wind_strength": 0.7, "wind_speed": 1.4,
             "color": (0.40, 0.50, 0.20), "max_slope": 28},
            {"name": "Flowers", "albedo": GRASS_TEX, "density": 1.2, "channel": 3,
             "min_scale": 0.6, "max_scale": 1.1, "min_height": 0.5, "max_height": 1.0,
             "view_distance": 90, "fade_start": 70, "wind_strength": 0.5, "wind_speed": 2.1,
             "color": (0.78, 0.72, 0.34), "max_slope": 24},
        ]),
        comment="── 192 m procedural meadow: three billboard layers, wind-driven ──",
    )
    return w


def build_woodland():
    w = SceneWriter(
        "Woodland", 1_239_000_005_000_000, WOODLAND_NOTE,
        settings(ssao=True, ssr=False, ssgi=False, bloom=0.3, fog=OUTDOOR_FOG,
                 wind=wind_settings(True, speed=6.0, gust=0.55)),
    )
    w.entity("Camera", (0, 2.2, 10.0), (-0.04, 0, 0), (1, 1, 1), camera(far=2000.0),
             comment="── Camera (scene camera; capture manifests pose the EDITOR camera) ──")
    w.entity("Sky", components=procedural_sky((0.58, 0.52, 0.63), turbidity=2.8, ibl=0.4),
             comment="── Procedural sky + IBL; sun disk aligned with the directional light ──")
    w.entity("Sun", components=dir_light((-0.58, -0.52, -0.63), (1, 0.93, 0.78), 2.2,
                                         shadows=True, max_shadow_distance=400, cascade_lambda=0.92),
             comment="── Sun raking through the canopy ──")

    w.entity(
        "Woodland Terrain", (-96, 0, -96), (0, 0, 0), (1, 1, 1),
        terrain(192, 6.0, SEED + 1, WOODLAND_TERRAIN_LAYERS, WOODLAND_RULES)
        + foliage([
            {"name": "Understory", "albedo": GRASS_TEX, "density": 4.0, "channel": 1,
             "min_scale": 0.8, "max_scale": 1.5, "min_height": 0.8, "max_height": 1.6,
             "view_distance": 110, "fade_start": 85, "wind_strength": 0.35, "wind_speed": 1.5,
             "color": (0.26, 0.40, 0.18), "max_slope": 32},
            {"name": "Pines", "mesh": PINE, "albedo": GRASS_TEX, "density": 0.09, "channel": 1,
             "min_scale": 0.9, "max_scale": 1.5, "min_height": 8, "max_height": 15,
             "view_distance": 600, "fade_start": 520, "wind_strength": 0.2, "wind_speed": 0.8,
             "color": (0.19, 0.33, 0.20), "max_slope": 36,
             "impostor": True, "impostor_start": 45},
            {"name": "Palms", "mesh": PALM, "albedo": GRASS_TEX, "density": 0.03, "channel": 0,
             "min_scale": 0.9, "max_scale": 1.3, "min_height": 6, "max_height": 11,
             "view_distance": 600, "fade_start": 520, "wind_strength": 0.32, "wind_speed": 1.1,
             "color": (0.25, 0.42, 0.20), "max_slope": 26,
             "impostor": True, "impostor_start": 45},
        ]),
        comment="── 192 m procedural woodland: canopy + understory, impostors beyond 45 m ──",
    )
    return w


BUILDERS = {
    "ReferenceHead": build_reference_head,
    "AnimalShortCoat": build_animal_short_coat,
    "AnimalLongCoat": build_animal_long_coat,
    "Meadow": build_meadow,
    "Woodland": build_woodland,
}


def main():
    ap = argparse.ArgumentParser(
        description="Generate the #1239 reference fixture benchmark scenes (.olo)")
    ap.add_argument("--out-dir", type=pathlib.Path, default=SCENE_DIR)
    ap.add_argument("--only", choices=sorted(BUILDERS), default=None)
    args = ap.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    names = [args.only] if args.only else list(BUILDERS)
    for name in names:
        w = BUILDERS[name]()
        path = args.out_dir / f"{name}.olo"
        path.write_text(w.text(), encoding="utf-8", newline="\n")
        print(f"{path} ({w.count} entities)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
