#!/usr/bin/env python3
# =============================================================================
# generate_test_catalogue.py
#
# Scans every .cpp under the roots declared in test_catalogue.json, extracts
# `TEST`, `TEST_F`, `TEST_P`, `TYPED_TEST`, and `INSTANTIATE_TEST_SUITE_P`
# invocations with a regex, groups them by layer via the authoritative
# file-to-layer mapping, and rewrites the auto-catalogue block in
# docs/renderer-testing.md between its BEGIN/END markers.
#
# Modes:
#   (default)   Rewrite docs/renderer-testing.md in place.
#   --check     Exit 1 if the generated block would differ from what's
#               already on disk, OR if any rendering-scope .cpp is missing
#               from file_layer_map / exclude. Used by pre-commit / CI.
#
# This is the registration mechanism that replaces manual doc edits: as
# long as every new test file is added to test_catalogue.json (enforced by
# --check), the catalogue regenerates itself.
# =============================================================================

import argparse
import json
import pathlib
import re
import sys
from collections import defaultdict


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
CATALOGUE_PATH = pathlib.Path(__file__).parent / "test_catalogue.json"
DOC_PATH = REPO_ROOT / "docs" / "renderer-testing.md"

BEGIN_MARKER = "<!-- BEGIN: auto-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
END_MARKER = "<!-- END: auto-catalogue -->"

# TEST / TEST_F / TEST_P / TYPED_TEST / INSTANTIATE_TEST_SUITE_P:
# all take at least (SuiteName, TestName). INSTANTIATE_TEST_SUITE_P has
# a different ordering but we only need the suite name for cataloguing.
TEST_RE = re.compile(
    r"^\s*(?:TEST|TEST_F|TEST_P|TYPED_TEST|TYPED_TEST_P)\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)",
    re.MULTILINE,
)
INSTANTIATE_RE = re.compile(
    r"^\s*INSTANTIATE_TEST_SUITE_P\s*\(\s*(\w+)\s*,\s*(\w+)",
    re.MULTILINE,
)


def load_config():
    with CATALOGUE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def scan_cpp_files(cfg):
    """Return a list of rel-path strings that are in-scope for classification."""
    files = set()
    for root in cfg["scan_roots"]:
        root_dir = REPO_ROOT / root
        if not root_dir.exists():
            continue
        for p in root_dir.rglob("*.cpp"):
            rel = p.relative_to(REPO_ROOT).as_posix()
            files.add(rel)
    for extra in cfg.get("extra_roots", []):
        p = REPO_ROOT / extra
        if p.exists():
            files.add(p.relative_to(REPO_ROOT).as_posix())
    return sorted(files)


def extract_tests(file_path):
    """Return list[(suite, name)] for every test registered in file_path."""
    tests = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return tests
    for m in TEST_RE.finditer(text):
        tests.append((m.group(1), m.group(2)))
    return tests


def extract_instantiations(file_path):
    """Return list[(instance, suite)] for INSTANTIATE_TEST_SUITE_P calls."""
    instances = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return instances
    for m in INSTANTIATE_RE.finditer(text):
        instances.append((m.group(1), m.group(2)))
    return instances


def validate(cfg, files):
    """Every file under scan_roots must be in file_layer_map or exclude."""
    classified = set(cfg["file_layer_map"].keys())
    excluded = set(cfg.get("exclude", []))
    unknown = []
    for rel in files:
        if rel not in classified and rel not in excluded:
            unknown.append(rel)

    # Also flag stale entries (in config but not on disk).
    stale = []
    all_on_disk = set(files)
    for rel in classified:
        if rel not in all_on_disk:
            stale.append(rel)

    return unknown, stale


def build_markdown(cfg):
    # Group files by layer id in declaration order.
    by_layer = defaultdict(list)
    for rel, layer_id in cfg["file_layer_map"].items():
        by_layer[layer_id].append(rel)

    lines = []
    lines.append(BEGIN_MARKER)
    lines.append("")
    lines.append("> **Do not edit by hand.** Generated from [test_catalogue.json](../OloEngine/tests/scripts/test_catalogue.json) by [generate_test_catalogue.py](../OloEngine/tests/scripts/generate_test_catalogue.py). Add new test files to the config and run the script (or pre-commit will run it with `--check`).")
    lines.append("")

    total_tests = 0
    total_files = 0

    for layer in cfg["layers"]:
        layer_id = layer["id"]
        files = sorted(by_layer.get(layer_id, []))
        if not files:
            continue

        title = layer["title"]
        anchor = layer.get("anchor", "")
        # The catalogue is inserted under "## 3.12" in docs/renderer-testing.md,
        # so per-layer sub-headings must be "### ..." (one level deeper) to
        # satisfy MD001 (heading-increment). A previous hardcoded "####" was
        # skipping a level and tripping markdownlint.
        if anchor:
            heading = f"### {layer_id} — [{title}](#{anchor})"
        else:
            heading = f"### {layer_id} — {title}"

        lines.append(heading)
        lines.append("")
        lines.append("| File | Tests | Cases |")
        lines.append("|---|---:|---|")

        for rel in files:
            abs_path = REPO_ROOT / rel
            tests = extract_tests(abs_path)
            instances = extract_instantiations(abs_path)
            name = pathlib.Path(rel).name
            link = f"[{name}](../{rel})"

            # Group test names by suite, preserving source order for both.
            suites = []  # list of (suite, [names])
            by_suite = {}
            for suite, test_name in tests:
                if suite not in by_suite:
                    by_suite[suite] = []
                    suites.append(suite)
                by_suite[suite].append(test_name)

            suite_chunks = []
            for suite in suites:
                names_md = ", ".join(f"`{n}`" for n in by_suite[suite])
                suite_chunks.append(f"**{suite}** &mdash; {names_md}")
            cell = "<br/>".join(suite_chunks)

            if instances:
                cell += f"<br/>*Parametrised via {len(instances)} `INSTANTIATE_TEST_SUITE_P`*"
            if not cell:
                cell = "*(no direct TEST macros — likely helper or fixture)*"

            lines.append(f"| {link} | {len(tests)} | {cell} |")
            total_tests += len(tests)
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} rendering-scope test files, {total_tests} TEST / TEST_F / TEST_P declarations across all layers. Non-rendering subsystems (audio, networking, gameplay, save-game, &hellip;) are catalogued separately and are not listed here by design.")
    lines.append("")
    lines.append(END_MARKER)

    return "\n".join(lines)


def replace_block(original_text, new_block):
    if BEGIN_MARKER not in original_text or END_MARKER not in original_text:
        raise RuntimeError(
            f"Markers not found in {DOC_PATH}. Insert "
            f"'{BEGIN_MARKER}' and '{END_MARKER}' lines at the target location."
        )
    # Split on BEGIN, then on END of the tail.
    before, rest = original_text.split(BEGIN_MARKER, 1)
    _old, after = rest.split(END_MARKER, 1)
    return before + new_block + after


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate and diff without writing; exit 1 on unclassified files or stale block.",
    )
    args = parser.parse_args()

    cfg = load_config()
    files = scan_cpp_files(cfg)
    unknown, stale = validate(cfg, files)

    if unknown:
        print("ERROR: the following test files are not registered in test_catalogue.json:", file=sys.stderr)
        for u in unknown:
            print(f"  - {u}", file=sys.stderr)
        print("Add each to file_layer_map (with a layer id) or exclude.", file=sys.stderr)

    if stale:
        print("ERROR: the following file_layer_map entries point at files that no longer exist:", file=sys.stderr)
        for s in stale:
            print(f"  - {s}", file=sys.stderr)

    if unknown or stale:
        sys.exit(1)

    block = build_markdown(cfg)
    doc_text = DOC_PATH.read_text(encoding="utf-8")
    new_text = replace_block(doc_text, block)

    if args.check:
        if new_text != doc_text:
            print("ERROR: auto-catalogue block in docs/renderer-testing.md is out of date.", file=sys.stderr)
            print("Run 'python OloEngine/tests/scripts/generate_test_catalogue.py' to regenerate.", file=sys.stderr)
            sys.exit(1)
        print(f"OK: catalogue in sync ({len(files)} files classified).")
        return

    if new_text == doc_text:
        print(f"No changes ({len(files)} files, block already current).")
        return

    DOC_PATH.write_text(new_text, encoding="utf-8")
    print(f"Rewrote {DOC_PATH.relative_to(REPO_ROOT).as_posix()} ({len(files)} files classified).")


if __name__ == "__main__":
    main()
