#!/usr/bin/env python3
# =============================================================================
# generate_test_catalogue.py
#
# Scans EVERY .cpp under test_root (OloEngine/tests) — the whole tree, no
# allowlist and no exclude list — extracts `TEST`, `TEST_F`, `TEST_P`,
# `TYPED_TEST`, and `INSTANTIATE_TEST_SUITE_P` invocations with a regex,
# classifies each via the file_layer_map, and rewrites THREE auto-catalogue
# blocks in docs/testing.md:
#
#   * Renderer-scope tests (L1–L11 + plumbing/cullinglod/shaderpipe/...)
#     → renderer testing pyramid
#   * Functional / cross-subsystem tests (tagged "Functional")
#     → engine-wide cross-subsystem axis
#   * Plain subsystem unit tests (tagged "unit")
#     → grouped by directory; everything that is neither of the above
#
# Modes:
#   (default)   Rewrite all three blocks in docs/testing.md in place.
#   --check     Exit 1 if any generated block would differ from what's already
#               on disk, OR if any test .cpp is missing from file_layer_map.
#               Used by pre-commit / CI.
#
# This is the registration mechanism that replaces manual doc edits: every test
# file (any .cpp declaring >=1 TEST macro) must be in file_layer_map — there are
# no exclusions. Files with no test macros (the gtest main, libFuzzer targets,
# fixtures/helpers) are not tests and need no entry. Add new test files to
# test_catalogue.json (enforced by --check) and the catalogue regenerates itself.
# =============================================================================

import argparse
import json
import pathlib
import re
import sys
from collections import defaultdict


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
CATALOGUE_PATH = pathlib.Path(__file__).parent / "test_catalogue.json"

# Two distinct marker pairs let us drop both blocks into the same consolidated
# doc (docs/testing.md, sections 9.1 and 9.2). Both pairs MUST exist in the
# target doc; the script errors out if either is missing.
RENDERER_BEGIN = "<!-- BEGIN: renderer-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
RENDERER_END = "<!-- END: renderer-catalogue -->"
FUNCTIONAL_BEGIN = "<!-- BEGIN: functional-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
FUNCTIONAL_END = "<!-- END: functional-catalogue -->"
UNIT_BEGIN = "<!-- BEGIN: unit-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
UNIT_END = "<!-- END: unit-catalogue -->"

# Classification tag for plain subsystem unit tests — everything that is neither
# a renderer-pyramid test nor a Functional cross-subsystem test. Grouped by
# directory in its own doc block.
UNIT_TAG = "unit"

# Shared boilerplate emitted into every one of the three catalogue blocks.
DOC_GENERATED_NOTE = "> **Do not edit by hand.** Generated by [generate_test_catalogue.py](../OloEngine/tests/scripts/generate_test_catalogue.py). Classify a new test in-file with a `// OLO_TEST_LAYER: <id>` comment near the top (preferred — no shared file to conflict on), or add it to [test_catalogue.json](../OloEngine/tests/scripts/test_catalogue.json). Then run the script (or pre-commit will run it with `--check`)."
TABLE_HEADER = "| File | Tests | Cases |"
TABLE_SEPARATOR = "|---|---:|---|"

# TEST / TEST_F / TEST_P / TYPED_TEST / INSTANTIATE_TEST_SUITE_P:
# all take at least (SuiteName, TestName). INSTANTIATE_TEST_SUITE_P has
# a different ordering but we only need the suite name for cataloguing.
TEST_RE = re.compile(
    r"^\s*(?:TEST|TEST_F|TEST_P|TYPED_TEST|TYPED_TEST_P)\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)",
    re.MULTILINE,
)
INSTANTIATE_RE = re.compile(
    r"^\s*INSTANTIATE_TEST_SUITE_P\s*\(\s*(\w+)\s*,\s*(\w+)",
    re.MULTILINE,
)

# In-file classification marker. A test .cpp can carry its own layer/tag with a
# one-line comment near the top, e.g. `// OLO_TEST_LAYER: L1` or
# `// OLO_TEST_LAYER: Functional`. This is the preferred way to classify a NEW
# test: it lives in the test file itself, so adding a test never touches the
# shared test_catalogue.json and two branches adding tests can't collide on it.
# The central file_layer_map remains as a fallback for files that don't (yet)
# carry a marker; a file may use one or the other, not both.
LAYER_MARKER_RE = re.compile(
    r"^[ \t]*//[ \t]*OLO_TEST_LAYER:[ \t]*([A-Za-z0-9_]+)",
    re.MULTILINE,
)


def load_config():
    with CATALOGUE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def scan_cpp_files(cfg):
    """Return every .cpp under the test root. The whole tree is in scope — there
    is no allowlist and no exclude list. Whether a file *needs* classification is
    decided later by whether it actually declares any tests (see validate)."""
    files = set()
    root_dir = REPO_ROOT / cfg["test_root"]
    for p in root_dir.rglob("*.cpp"):
        # The script's own directory holds tooling, not tests.
        if "scripts" in p.relative_to(root_dir).parts:
            continue
        files.add(p.relative_to(REPO_ROOT).as_posix())
    return sorted(files)


def extract_tests(file_path):
    """Return list[(suite, name)] for every test registered in file_path."""
    tests = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return tests
    for m in TEST_RE.finditer(text):
        tests.append((m.group(1), m.group(2)))
    return tests


def extract_instantiations(file_path):
    """Return list[(instance, suite)] for INSTANTIATE_TEST_SUITE_P calls."""
    instances = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return instances
    for m in INSTANTIATE_RE.finditer(text):
        instances.append((m.group(1), m.group(2)))
    return instances


def extract_layer_marker(file_path):
    """Return (layer_id, error) for the in-file `// OLO_TEST_LAYER: <id>` marker.

    layer_id is the marker's value, or None if the file carries no marker. error
    is a message string if the file carries multiple *conflicting* markers, else
    None (duplicate identical markers are tolerated)."""
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None, None
    found = LAYER_MARKER_RE.findall(text)
    if not found:
        return None, None
    distinct = sorted(set(found))
    if len(distinct) > 1:
        return None, f"multiple conflicting // OLO_TEST_LAYER markers: {distinct}"
    return found[0], None


def known_layer_ids(cfg):
    """The set of layer ids a marker or file_layer_map entry may use."""
    ids = {layer["id"] for layer in cfg["layers"]}
    ids.add(UNIT_TAG)
    ids.add(cfg.get("functional_tag", "Functional"))
    return ids


def classify_files(cfg, files):
    """Build the effective rel->layer classification for every test file.

    A file is a "test file" iff it declares at least one TEST / TEST_F / TEST_P /
    TYPED_TEST macro. Files with none (the gtest main, libFuzzer targets,
    fixtures/helpers) are not tests and need no entry — that is the definition of
    a non-test, not a configurable exclusion.

    Each test file is classified by EITHER an in-file `// OLO_TEST_LAYER: <id>`
    marker (preferred — see LAYER_MARKER_RE) OR an entry in the central
    file_layer_map, never both. The marker wins where present. There is no
    exclude escape hatch: an unclassified test file is an error.

    Returns (effective_map, errors). effective_map maps rel -> layer id; errors is
    a list of human-readable problem strings (empty == valid)."""
    json_map = cfg["file_layer_map"]
    valid = known_layer_ids(cfg)
    effective = {}
    errors = []

    for rel in files:
        abs_path = REPO_ROOT / rel
        if not extract_tests(abs_path):  # not a test file -> needs no classification
            continue

        marker, marker_err = extract_layer_marker(abs_path)
        in_json = rel in json_map
        if marker_err:
            errors.append(f"{rel}: {marker_err}")
            continue
        if marker and in_json:
            errors.append(
                f"{rel}: has an // OLO_TEST_LAYER:{marker} marker AND a "
                f"file_layer_map entry - remove the JSON entry (the marker "
                f"supersedes it)."
            )

        layer = marker if marker else json_map.get(rel)
        if layer is None:
            errors.append(
                f"{rel}: unclassified test file. Add '// OLO_TEST_LAYER: <id>' "
                f"near the top (preferred), or a file_layer_map entry. "
                f"Valid ids: {sorted(valid)}."
            )
            continue
        if layer not in valid:
            src = "marker" if marker else "file_layer_map"
            errors.append(
                f"{rel}: {src} layer '{layer}' is not a known id. "
                f"Valid ids: {sorted(valid)}."
            )
            continue
        effective[rel] = layer

    # Flag stale file_layer_map entries (in config but not on disk).
    on_disk = set(files)
    for rel in json_map:
        if rel not in on_disk:
            errors.append(
                f"{rel}: file_layer_map entry points at a file that no longer exists."
            )

    return effective, errors


def build_gtest_filter(effective, include, exclude):
    """Build a GoogleTest --gtest_filter value from layer classifications.

    include / exclude are sets of layer ids. The filter selects every test suite
    that lives in an `include` layer (or all suites when include is empty) and
    subtracts every suite that lives in an `exclude` layer. Suites are matched
    with both `Suite.*` and `*/Suite.*` so value-parametrised instantiations
    (`Prefix/Suite.Case/0`) are covered; typed-test forms (`Suite/0.Case`) are a
    known gap — see docs/testing.md."""
    def suites_for(labels):
        seen = []
        seen_set = set()
        for rel, layer in sorted(effective.items()):
            if layer not in labels:
                continue
            for suite, _name in extract_tests(REPO_ROOT / rel):
                if suite not in seen_set:
                    seen_set.add(suite)
                    seen.append(suite)
        return seen

    def patterns(suites):
        out = []
        for s in suites:
            out.append(f"{s}.*")
            out.append(f"*/{s}.*")
        return out

    positives = patterns(suites_for(include)) if include else ["*"]
    filt = ":".join(positives)
    negatives = patterns(suites_for(exclude))
    if negatives:
        filt += ":-" + ":".join(negatives)
    return filt


def file_row(rel):
    """Render one (file, count, cell) markdown row for the given test .cpp."""
    abs_path = REPO_ROOT / rel
    tests = extract_tests(abs_path)
    instances = extract_instantiations(abs_path)
    name = pathlib.Path(rel).name
    link = f"[{name}](../{rel})"

    # Group test names by suite, preserving source order for both.
    suites = []
    by_suite = {}
    for suite, test_name in tests:
        if suite not in by_suite:
            by_suite[suite] = []
            suites.append(suite)
        by_suite[suite].append(test_name)

    suite_chunks = []
    for suite in suites:
        names_md = ", ".join(f"`{n}`" for n in by_suite[suite])
        suite_chunks.append(f"**{suite}** &mdash; {names_md}")
    cell = "<br/>".join(suite_chunks)

    if instances:
        cell += f"<br/>*Parametrised via {len(instances)} `INSTANTIATE_TEST_SUITE_P`*"
    if not cell:
        cell = "*(no direct TEST macros — likely helper or fixture)*"

    return link, len(tests), cell


def build_renderer_block(cfg):
    """Group renderer-scope files by layer in declaration order; render markdown."""
    functional_tag = cfg.get("functional_tag", "Functional")
    by_layer = defaultdict(list)
    for rel, layer_id in cfg["file_layer_map"].items():
        if layer_id == functional_tag or layer_id == UNIT_TAG:
            continue
        by_layer[layer_id].append(rel)

    lines = []
    lines.append(RENDERER_BEGIN)
    lines.append("")
    lines.append(DOC_GENERATED_NOTE)
    lines.append("")

    total_tests = 0
    total_files = 0

    for layer in cfg["layers"]:
        layer_id = layer["id"]
        if layer_id == functional_tag:
            continue
        files = sorted(by_layer.get(layer_id, []))
        if not files:
            continue

        title = layer["title"]
        # Per-layer sub-headings are "#### ..." (one level below the "### 9.1
        # Renderer tests" anchor in docs/testing.md) to keep MD001 happy.
        heading = f"#### {layer_id} — {title}"

        lines.append(heading)
        lines.append("")
        lines.append(TABLE_HEADER)
        lines.append(TABLE_SEPARATOR)

        for rel in files:
            link, n, cell = file_row(rel)
            lines.append(f"| {link} | {n} | {cell} |")
            total_tests += n
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} renderer-scope test files, {total_tests} TEST / TEST_F / TEST_P declarations across all layers.")
    lines.append("")
    lines.append(RENDERER_END)

    return "\n".join(lines)


def build_functional_block(cfg):
    """Group Functional tests by subdirectory under tests/Functional/ for readability."""
    functional_tag = cfg.get("functional_tag", "Functional")
    files = sorted(
        rel for rel, tag in cfg["file_layer_map"].items() if tag == functional_tag
    )

    # Bucket by the first path segment under tests/Functional/.
    by_subdir = defaultdict(list)
    prefix = "OloEngine/tests/Functional/"
    for rel in files:
        tail = rel[len(prefix):] if rel.startswith(prefix) else rel
        first = tail.split("/", 1)[0] if "/" in tail else "(root)"
        by_subdir[first].append(rel)

    lines = []
    lines.append(FUNCTIONAL_BEGIN)
    lines.append("")
    lines.append(DOC_GENERATED_NOTE)
    lines.append("")

    total_tests = 0
    total_files = 0

    for subdir in sorted(by_subdir.keys()):
        entries = by_subdir[subdir]
        heading = f"#### {subdir} ({len(entries)} file{'s' if len(entries) != 1 else ''})"
        lines.append(heading)
        lines.append("")
        lines.append(TABLE_HEADER)
        lines.append(TABLE_SEPARATOR)

        for rel in entries:
            link, n, cell = file_row(rel)
            lines.append(f"| {link} | {n} | {cell} |")
            total_tests += n
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} Functional test files, {total_tests} TEST / TEST_F declarations across all subsystems.")
    lines.append("")
    lines.append(FUNCTIONAL_END)

    return "\n".join(lines)


def build_unit_block(cfg):
    """Group plain subsystem unit tests (tag 'unit') by their directory under
    tests/ for readability. These are tests that belong to neither the renderer
    pyramid nor the Functional axis."""
    files = sorted(
        rel for rel, tag in cfg["file_layer_map"].items() if tag == UNIT_TAG
    )

    # Bucket by the first path segment under tests/; top-level files go to
    # "(top-level)" so the grab-bag of cross-subsystem unit tests is still listed.
    by_subdir = defaultdict(list)
    prefix = "OloEngine/tests/"
    for rel in files:
        tail = rel[len(prefix):] if rel.startswith(prefix) else rel
        first = tail.split("/", 1)[0] if "/" in tail else "(top-level)"
        by_subdir[first].append(rel)

    lines = []
    lines.append(UNIT_BEGIN)
    lines.append("")
    lines.append(DOC_GENERATED_NOTE)
    lines.append("")

    total_tests = 0
    total_files = 0

    for subdir in sorted(by_subdir.keys()):
        entries = sorted(by_subdir[subdir])
        heading = f"#### {subdir} ({len(entries)} file{'s' if len(entries) != 1 else ''})"
        lines.append(heading)
        lines.append("")
        lines.append(TABLE_HEADER)
        lines.append(TABLE_SEPARATOR)

        for rel in entries:
            link, n, cell = file_row(rel)
            lines.append(f"| {link} | {n} | {cell} |")
            total_tests += n
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} unit / subsystem test files, {total_tests} TEST / TEST_F declarations across all subsystems.")
    lines.append("")
    lines.append(UNIT_END)

    return "\n".join(lines)


def replace_block(doc_path, original_text, new_block, begin_marker, end_marker):
    if begin_marker not in original_text or end_marker not in original_text:
        raise RuntimeError(
            f"Markers not found in {doc_path}. Insert "
            f"'{begin_marker}' and '{end_marker}' lines at the target location."
        )
    before, rest = original_text.split(begin_marker, 1)
    _old, after = rest.split(end_marker, 1)
    return before + new_block + after


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate and diff without writing; exit 1 on unclassified files or stale blocks.",
    )
    parser.add_argument(
        "--gtest-filter",
        action="store_true",
        help="Print a GoogleTest --gtest_filter value (selecting/excluding tests "
        "by layer via --include / --exclude) and exit, instead of touching the doc.",
    )
    parser.add_argument(
        "--include",
        default="",
        help="Comma-separated layer ids to INCLUDE in --gtest-filter (default: all).",
    )
    parser.add_argument(
        "--exclude",
        default="",
        help="Comma-separated layer ids to EXCLUDE in --gtest-filter "
        "(e.g. 'L6,L7,L8' for a fast inner loop that skips perf/golden/visual tests).",
    )
    args = parser.parse_args()

    cfg = load_config()
    files = scan_cpp_files(cfg)
    effective, errors = classify_files(cfg, files)

    if errors:
        print("ERROR: test-catalogue classification problems:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    # The effective map (markers overlaying file_layer_map) is the source of
    # truth for every downstream consumer below.
    cfg["file_layer_map"] = effective

    if args.gtest_filter:
        inc = {x.strip() for x in args.include.split(",") if x.strip()}
        exc = {x.strip() for x in args.exclude.split(",") if x.strip()}
        print(build_gtest_filter(effective, inc, exc))
        return

    # Both blocks land in the same consolidated doc -- docs/testing.md by
    # default. The script first updates the renderer block, then the
    # functional block, reading the doc fresh after the first update so
    # the second replacement sees the modified content.
    doc_path = REPO_ROOT / cfg["doc"]
    if not doc_path.exists():
        print(f"ERROR: target doc does not exist: {doc_path}", file=sys.stderr)
        sys.exit(1)

    original_text = doc_path.read_text(encoding="utf-8")
    new_text = replace_block(doc_path, original_text,
                             build_renderer_block(cfg),
                             RENDERER_BEGIN, RENDERER_END)
    new_text = replace_block(doc_path, new_text,
                             build_functional_block(cfg),
                             FUNCTIONAL_BEGIN, FUNCTIONAL_END)
    new_text = replace_block(doc_path, new_text,
                             build_unit_block(cfg),
                             UNIT_BEGIN, UNIT_END)

    if new_text == original_text:
        if args.check:
            print(f"OK: catalogues in sync ({len(files)} files classified).")
        else:
            print(f"No changes ({len(files)} files, blocks already current).")
        return

    if args.check:
        print(f"ERROR: auto-catalogue blocks in {doc_path.relative_to(REPO_ROOT).as_posix()} are out of date.", file=sys.stderr)
        print("Run 'python OloEngine/tests/scripts/generate_test_catalogue.py' to regenerate.", file=sys.stderr)
        sys.exit(1)

    doc_path.write_text(new_text, encoding="utf-8")
    print(f"Rewrote {doc_path.relative_to(REPO_ROOT).as_posix()} ({len(files)} files classified).")


if __name__ == "__main__":
    main()
