#!/usr/bin/env python3
# =============================================================================
# generate_test_catalogue.py
#
# Scans every .cpp under the roots declared in test_catalogue.json, extracts
# `TEST`, `TEST_F`, `TEST_P`, `TYPED_TEST`, and `INSTANTIATE_TEST_SUITE_P`
# invocations with a regex, classifies each via the file_layer_map, and
# rewrites TWO auto-catalogue blocks:
#
#   * Renderer-scope tests (L1–L11 + plumbing/cullinglod/shaderpipe/...)
#     → block in docs/testing.md (renderer testing pyramid)
#   * Functional / cross-subsystem tests (tagged "Functional")
#     → block in docs/testing.md (engine-wide cross-subsystem axis)
#
# Modes:
#   (default)   Rewrite both target docs in place.
#   --check     Exit 1 if either generated block would differ from what's
#               already on disk, OR if any in-scope .cpp is missing from
#               file_layer_map / exclude. Used by pre-commit / CI.
#
# This is the registration mechanism that replaces manual doc edits: as
# long as every new test file is added to test_catalogue.json (enforced by
# --check), the catalogue regenerates itself.
# =============================================================================

import argparse
import json
import pathlib
import re
import sys
from collections import defaultdict


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
CATALOGUE_PATH = pathlib.Path(__file__).parent / "test_catalogue.json"

# Two distinct marker pairs let us drop both blocks into the same consolidated
# doc (docs/testing.md, sections 9.1 and 9.2). Both pairs MUST exist in the
# target doc; the script errors out if either is missing.
RENDERER_BEGIN = "<!-- BEGIN: renderer-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
RENDERER_END = "<!-- END: renderer-catalogue -->"
FUNCTIONAL_BEGIN = "<!-- BEGIN: functional-catalogue (generated by OloEngine/tests/scripts/generate_test_catalogue.py) -->"
FUNCTIONAL_END = "<!-- END: functional-catalogue -->"

# TEST / TEST_F / TEST_P / TYPED_TEST / INSTANTIATE_TEST_SUITE_P:
# all take at least (SuiteName, TestName). INSTANTIATE_TEST_SUITE_P has
# a different ordering but we only need the suite name for cataloguing.
TEST_RE = re.compile(
    r"^\s*(?:TEST|TEST_F|TEST_P|TYPED_TEST|TYPED_TEST_P)\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)",
    re.MULTILINE,
)
INSTANTIATE_RE = re.compile(
    r"^\s*INSTANTIATE_TEST_SUITE_P\s*\(\s*(\w+)\s*,\s*(\w+)",
    re.MULTILINE,
)


def load_config():
    with CATALOGUE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def scan_cpp_files(cfg):
    """Return a list of rel-path strings that are in-scope for classification."""
    files = set()
    for root in cfg["scan_roots"]:
        root_dir = REPO_ROOT / root
        if not root_dir.exists():
            continue
        for p in root_dir.rglob("*.cpp"):
            rel = p.relative_to(REPO_ROOT).as_posix()
            files.add(rel)
    for extra in cfg.get("extra_roots", []):
        p = REPO_ROOT / extra
        if p.exists():
            files.add(p.relative_to(REPO_ROOT).as_posix())
    return sorted(files)


def extract_tests(file_path):
    """Return list[(suite, name)] for every test registered in file_path."""
    tests = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return tests
    for m in TEST_RE.finditer(text):
        tests.append((m.group(1), m.group(2)))
    return tests


def extract_instantiations(file_path):
    """Return list[(instance, suite)] for INSTANTIATE_TEST_SUITE_P calls."""
    instances = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return instances
    for m in INSTANTIATE_RE.finditer(text):
        instances.append((m.group(1), m.group(2)))
    return instances


def validate(cfg, files):
    """Every file under scan_roots must be in file_layer_map or exclude."""
    classified = set(cfg["file_layer_map"].keys())
    excluded = set(cfg.get("exclude", []))
    unknown = []
    for rel in files:
        if rel not in classified and rel not in excluded:
            unknown.append(rel)

    # Also flag stale entries (in config but not on disk).
    stale = []
    all_on_disk = set(files)
    for rel in classified:
        if rel not in all_on_disk:
            stale.append(rel)

    return unknown, stale


def file_row(rel):
    """Render one (file, count, cell) markdown row for the given test .cpp."""
    abs_path = REPO_ROOT / rel
    tests = extract_tests(abs_path)
    instances = extract_instantiations(abs_path)
    name = pathlib.Path(rel).name
    link = f"[{name}](../{rel})"

    # Group test names by suite, preserving source order for both.
    suites = []
    by_suite = {}
    for suite, test_name in tests:
        if suite not in by_suite:
            by_suite[suite] = []
            suites.append(suite)
        by_suite[suite].append(test_name)

    suite_chunks = []
    for suite in suites:
        names_md = ", ".join(f"`{n}`" for n in by_suite[suite])
        suite_chunks.append(f"**{suite}** &mdash; {names_md}")
    cell = "<br/>".join(suite_chunks)

    if instances:
        cell += f"<br/>*Parametrised via {len(instances)} `INSTANTIATE_TEST_SUITE_P`*"
    if not cell:
        cell = "*(no direct TEST macros — likely helper or fixture)*"

    return link, len(tests), cell


def build_renderer_block(cfg):
    """Group renderer-scope files by layer in declaration order; render markdown."""
    functional_tag = cfg.get("functional_tag", "Functional")
    by_layer = defaultdict(list)
    for rel, layer_id in cfg["file_layer_map"].items():
        if layer_id == functional_tag:
            continue
        by_layer[layer_id].append(rel)

    lines = []
    lines.append(RENDERER_BEGIN)
    lines.append("")
    lines.append("> **Do not edit by hand.** Generated from [test_catalogue.json](../OloEngine/tests/scripts/test_catalogue.json) by [generate_test_catalogue.py](../OloEngine/tests/scripts/generate_test_catalogue.py). Add new test files to the config and run the script (or pre-commit will run it with `--check`).")
    lines.append("")

    total_tests = 0
    total_files = 0

    for layer in cfg["layers"]:
        layer_id = layer["id"]
        if layer_id == functional_tag:
            continue
        files = sorted(by_layer.get(layer_id, []))
        if not files:
            continue

        title = layer["title"]
        # Per-layer sub-headings are "#### ..." (one level below the "### 9.1
        # Renderer tests" anchor in docs/testing.md) to keep MD001 happy.
        heading = f"#### {layer_id} — {title}"

        lines.append(heading)
        lines.append("")
        lines.append("| File | Tests | Cases |")
        lines.append("|---|---:|---|")

        for rel in files:
            link, n, cell = file_row(rel)
            lines.append(f"| {link} | {n} | {cell} |")
            total_tests += n
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} renderer-scope test files, {total_tests} TEST / TEST_F / TEST_P declarations across all layers.")
    lines.append("")
    lines.append(RENDERER_END)

    return "\n".join(lines)


def build_functional_block(cfg):
    """Group Functional tests by subdirectory under tests/Functional/ for readability."""
    functional_tag = cfg.get("functional_tag", "Functional")
    files = sorted(
        rel for rel, tag in cfg["file_layer_map"].items() if tag == functional_tag
    )

    # Bucket by the first path segment under tests/Functional/.
    by_subdir = defaultdict(list)
    prefix = "OloEngine/tests/Functional/"
    for rel in files:
        tail = rel[len(prefix):] if rel.startswith(prefix) else rel
        first = tail.split("/", 1)[0] if "/" in tail else "(root)"
        by_subdir[first].append(rel)

    lines = []
    lines.append(FUNCTIONAL_BEGIN)
    lines.append("")
    lines.append("> **Do not edit by hand.** Generated from [test_catalogue.json](../OloEngine/tests/scripts/test_catalogue.json) by [generate_test_catalogue.py](../OloEngine/tests/scripts/generate_test_catalogue.py). Add new test files to the config and run the script (or pre-commit will run it with `--check`).")
    lines.append("")

    total_tests = 0
    total_files = 0

    for subdir in sorted(by_subdir.keys()):
        entries = by_subdir[subdir]
        heading = f"#### {subdir} ({len(entries)} file{'s' if len(entries) != 1 else ''})"
        lines.append(heading)
        lines.append("")
        lines.append("| File | Tests | Cases |")
        lines.append("|---|---:|---|")

        for rel in entries:
            link, n, cell = file_row(rel)
            lines.append(f"| {link} | {n} | {cell} |")
            total_tests += n
            total_files += 1

        lines.append("")

    lines.append(f"**Totals.** {total_files} Functional test files, {total_tests} TEST / TEST_F declarations across all subsystems.")
    lines.append("")
    lines.append(FUNCTIONAL_END)

    return "\n".join(lines)


def replace_block(doc_path, original_text, new_block, begin_marker, end_marker):
    if begin_marker not in original_text or end_marker not in original_text:
        raise RuntimeError(
            f"Markers not found in {doc_path}. Insert "
            f"'{begin_marker}' and '{end_marker}' lines at the target location."
        )
    before, rest = original_text.split(begin_marker, 1)
    _old, after = rest.split(end_marker, 1)
    return before + new_block + after


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate and diff without writing; exit 1 on unclassified files or stale blocks.",
    )
    args = parser.parse_args()

    cfg = load_config()
    files = scan_cpp_files(cfg)
    unknown, stale = validate(cfg, files)

    if unknown:
        print("ERROR: the following test files are not registered in test_catalogue.json:", file=sys.stderr)
        for u in unknown:
            print(f"  - {u}", file=sys.stderr)
        print("Add each to file_layer_map (with a layer id or 'Functional') or exclude.", file=sys.stderr)

    if stale:
        print("ERROR: the following file_layer_map entries point at files that no longer exist:", file=sys.stderr)
        for s in stale:
            print(f"  - {s}", file=sys.stderr)

    if unknown or stale:
        sys.exit(1)

    # Both blocks land in the same consolidated doc -- docs/testing.md by
    # default. The script first updates the renderer block, then the
    # functional block, reading the doc fresh after the first update so
    # the second replacement sees the modified content.
    doc_path = REPO_ROOT / cfg["doc"]
    if not doc_path.exists():
        print(f"ERROR: target doc does not exist: {doc_path}", file=sys.stderr)
        sys.exit(1)

    original_text = doc_path.read_text(encoding="utf-8")
    new_text = replace_block(doc_path, original_text,
                             build_renderer_block(cfg),
                             RENDERER_BEGIN, RENDERER_END)
    new_text = replace_block(doc_path, new_text,
                             build_functional_block(cfg),
                             FUNCTIONAL_BEGIN, FUNCTIONAL_END)

    if new_text == original_text:
        if args.check:
            print(f"OK: catalogues in sync ({len(files)} files classified).")
        else:
            print(f"No changes ({len(files)} files, blocks already current).")
        return

    if args.check:
        print(f"ERROR: auto-catalogue blocks in {doc_path.relative_to(REPO_ROOT).as_posix()} are out of date.", file=sys.stderr)
        print("Run 'python OloEngine/tests/scripts/generate_test_catalogue.py' to regenerate.", file=sys.stderr)
        sys.exit(1)

    doc_path.write_text(new_text, encoding="utf-8")
    print(f"Rewrote {doc_path.relative_to(REPO_ROOT).as_posix()} ({len(files)} files classified).")


if __name__ == "__main__":
    main()
