// Auto-generated by OloHeaderTool — DO NOT EDIT MANUALLY

using System.Runtime.CompilerServices;

namespace OloEngine
{
	public static partial class InternalCalls
	{
		#region AudioSoundGraphComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSoundGraphComponent_GetVolume(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSoundGraphComponent_SetVolume(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSoundGraphComponent_GetPitch(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSoundGraphComponent_SetPitch(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool AudioSoundGraphComponent_GetLooping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSoundGraphComponent_SetLooping(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool AudioSoundGraphComponent_GetPlayOnAwake(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSoundGraphComponent_SetPlayOnAwake(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern ulong AudioSoundGraphComponent_GetSoundGraphHandle(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSoundGraphComponent_SetSoundGraphHandle(ulong entityID, ulong value);
		#endregion

		#region AudioSourceComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetVolume(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetVolume(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetPitch(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetPitch(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool AudioSourceComponent_GetPlayOnAwake(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetPlayOnAwake(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool AudioSourceComponent_GetLooping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetLooping(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool AudioSourceComponent_GetSpatialization(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetSpatialization(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int AudioSourceComponent_GetAttenuationModel(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetAttenuationModel(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetRollOff(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetRollOff(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetMinGain(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetMinGain(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetMaxGain(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetMaxGain(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetMinDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetMinDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetMaxDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetMaxDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetConeInnerAngle(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetConeInnerAngle(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetConeOuterAngle(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetConeOuterAngle(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetConeOuterGain(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetConeOuterGain(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float AudioSourceComponent_GetDopplerFactor(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void AudioSourceComponent_SetDopplerFactor(ulong entityID, float value);
		#endregion

		#region BoxCollider2DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_GetOffset(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_SetOffset(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_GetSize(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_SetSize(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float BoxCollider2DComponent_GetDensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_SetDensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float BoxCollider2DComponent_GetFriction(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_SetFriction(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float BoxCollider2DComponent_GetRestitution(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider2DComponent_SetRestitution(ulong entityID, float value);
		#endregion

		#region BoxCollider3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider3DComponent_GetHalfExtents(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider3DComponent_SetHalfExtents(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider3DComponent_GetOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void BoxCollider3DComponent_SetOffset(ulong entityID, ref Vector3 value);
		#endregion

		#region CameraComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int CameraComponent_GetProjectionType(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetProjectionType(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetPerspectiveFOV(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetPerspectiveFOV(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetPerspectiveNearClip(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetPerspectiveNearClip(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetPerspectiveFarClip(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetPerspectiveFarClip(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetOrthographicSize(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetOrthographicSize(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetOrthographicNearClip(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetOrthographicNearClip(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CameraComponent_GetOrthographicFarClip(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetOrthographicFarClip(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CameraComponent_GetPrimary(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetPrimary(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CameraComponent_GetFixedAspectRatio(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CameraComponent_SetFixedAspectRatio(ulong entityID, bool value);
		#endregion

		#region CapsuleCollider3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CapsuleCollider3DComponent_GetRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CapsuleCollider3DComponent_SetRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CapsuleCollider3DComponent_GetHalfHeight(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CapsuleCollider3DComponent_SetHalfHeight(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CapsuleCollider3DComponent_GetOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CapsuleCollider3DComponent_SetOffset(ulong entityID, ref Vector3 value);
		#endregion

		#region CharacterController3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CharacterController3DComponent_GetSlopeLimit(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CharacterController3DComponent_SetSlopeLimit(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CharacterController3DComponent_GetStepOffset(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CharacterController3DComponent_SetStepOffset(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CharacterController3DComponent_GetJumpPower(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CharacterController3DComponent_SetJumpPower(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CharacterController3DComponent_GetDisableGravity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CharacterController3DComponent_SetDisableGravity(ulong entityID, bool value);
		#endregion

		#region CinematicComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern ulong CinematicComponent_GetSequence(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CinematicComponent_SetSequence(ulong entityID, ulong value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CinematicComponent_GetPlayOnStart(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CinematicComponent_SetPlayOnStart(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CinematicComponent_GetLoop(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CinematicComponent_SetLoop(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CinematicComponent_GetPlaybackSpeed(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CinematicComponent_SetPlaybackSpeed(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool CinematicComponent_GetPlaying(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CinematicComponent_SetPlaying(ulong entityID, bool value);
		#endregion

		#region CircleCollider2DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_GetOffset(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_SetOffset(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleCollider2DComponent_GetRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_SetRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleCollider2DComponent_GetDensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_SetDensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleCollider2DComponent_GetFriction(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_SetFriction(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleCollider2DComponent_GetRestitution(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleCollider2DComponent_SetRestitution(ulong entityID, float value);
		#endregion

		#region CircleRendererComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleRendererComponent_GetColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleRendererComponent_SetColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleRendererComponent_GetThickness(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleRendererComponent_SetThickness(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float CircleRendererComponent_GetFade(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void CircleRendererComponent_SetFade(ulong entityID, float value);
		#endregion

		#region DirectionalLightComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void DirectionalLightComponent_GetColor(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void DirectionalLightComponent_SetColor(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float DirectionalLightComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void DirectionalLightComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool DirectionalLightComponent_GetCastShadows(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void DirectionalLightComponent_SetCastShadows(ulong entityID, bool value);
		#endregion

		#region LightProbeComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float LightProbeComponent_GetInfluenceRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeComponent_SetInfluenceRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float LightProbeComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool LightProbeComponent_GetActive(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeComponent_SetActive(ulong entityID, bool value);
		#endregion

		#region LightProbeVolumeComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_GetBoundsMin(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_SetBoundsMin(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_GetBoundsMax(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_SetBoundsMax(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float LightProbeVolumeComponent_GetSpacing(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_SetSpacing(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float LightProbeVolumeComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool LightProbeVolumeComponent_GetActive(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void LightProbeVolumeComponent_SetActive(ulong entityID, bool value);
		#endregion

		#region MaterialComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_GetAlbedoColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_SetAlbedoColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float MaterialComponent_GetMetallic(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_SetMetallic(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float MaterialComponent_GetRoughness(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_SetRoughness(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_GetEmissive(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void MaterialComponent_SetEmissive(ulong entityID, ref Vector4 value);
		#endregion

		#region NameplateComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool NameplateComponent_GetEnabled(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetEnabled(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool NameplateComponent_GetShowHealthBar(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetShowHealthBar(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool NameplateComponent_GetShowManaBar(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetShowManaBar(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_GetWorldOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetWorldOffset(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_GetBarSize(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetBarSize(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_GetHealthBarColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetHealthBarColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_GetManaBarColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetManaBarColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_GetBarBackgroundColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetBarBackgroundColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float NameplateComponent_GetManaBarGap(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NameplateComponent_SetManaBarGap(ulong entityID, float value);
		#endregion

		#region NavAgentComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float NavAgentComponent_GetMaxSpeed(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_SetMaxSpeed(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float NavAgentComponent_GetAcceleration(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_SetAcceleration(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float NavAgentComponent_GetStoppingDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_SetStoppingDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool NavAgentComponent_GetLockYAxis(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_SetLockYAxis(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_GetTargetPosition(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavAgentComponent_SetTargetPosition(ulong entityID, ref Vector3 value);
		#endregion

		#region NavMeshBoundsComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavMeshBoundsComponent_GetMin(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavMeshBoundsComponent_SetMin(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavMeshBoundsComponent_GetMax(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void NavMeshBoundsComponent_SetMax(ulong entityID, ref Vector3 value);
		#endregion

		#region ParticleSystemComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ParticleSystemComponent_GetPlaying(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ParticleSystemComponent_SetPlaying(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ParticleSystemComponent_GetLooping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ParticleSystemComponent_SetLooping(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ParticleSystemComponent_GetEmissionRate(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ParticleSystemComponent_SetEmissionRate(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ParticleSystemComponent_GetWindInfluence(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ParticleSystemComponent_SetWindInfluence(ulong entityID, float value);
		#endregion

		#region PhysicsJoint3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int PhysicsJoint3DComponent_GetJointType(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetJointType(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_GetLocalAnchorA(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetLocalAnchorA(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_GetLocalAnchorB(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetLocalAnchorB(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_GetAxis(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetAxis(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetMinDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetMinDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetMaxDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetMaxDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMinAngleDeg(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMinAngleDeg(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMaxAngleDeg(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMaxAngleDeg(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMinLimit(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMinLimit(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMaxLimit(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMaxLimit(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetConeHalfAngleDeg(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetConeHalfAngleDeg(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetBreakForce(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetBreakForce(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetBreakTorque(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetBreakTorque(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int PhysicsJoint3DComponent_GetHingeMotorMode(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMotorMode(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMotorTargetVelocityDeg(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMotorTargetVelocityDeg(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMotorTargetAngleDeg(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMotorTargetAngleDeg(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMaxMotorTorque(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMaxMotorTorque(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeMaxFrictionTorque(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeMaxFrictionTorque(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeLimitSpringFrequency(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeLimitSpringFrequency(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetHingeLimitSpringDamping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetHingeLimitSpringDamping(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int PhysicsJoint3DComponent_GetSliderMotorMode(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMotorMode(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMotorTargetVelocity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMotorTargetVelocity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMotorTargetPosition(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMotorTargetPosition(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMaxMotorForce(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMaxMotorForce(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderMaxFrictionForce(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderMaxFrictionForce(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderLimitSpringFrequency(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderLimitSpringFrequency(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PhysicsJoint3DComponent_GetSliderLimitSpringDamping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PhysicsJoint3DComponent_SetSliderLimitSpringDamping(ulong entityID, float value);
		#endregion

		#region PointLightComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PointLightComponent_GetColor(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PointLightComponent_SetColor(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PointLightComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PointLightComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float PointLightComponent_GetRange(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PointLightComponent_SetRange(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool PointLightComponent_GetCastShadows(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void PointLightComponent_SetCastShadows(ulong entityID, bool value);
		#endregion

		#region ProceduralSkyComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_GetSunDirection(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetSunDirection(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ProceduralSkyComponent_GetTurbidity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetTurbidity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ProceduralSkyComponent_GetExposure(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetExposure(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ProceduralSkyComponent_GetSunIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetSunIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ProceduralSkyComponent_GetSunDiskSize(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetSunDiskSize(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ProceduralSkyComponent_GetShowSunDisk(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetShowSunDisk(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ProceduralSkyComponent_GetLinkSunToDirectionalLight(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetLinkSunToDirectionalLight(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ProceduralSkyComponent_GetEnableSkybox(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetEnableSkybox(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ProceduralSkyComponent_GetEnableIBL(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetEnableIBL(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ProceduralSkyComponent_GetIBLIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ProceduralSkyComponent_SetIBLIntensity(ulong entityID, float value);
		#endregion

		#region ReflectionProbeComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ReflectionProbeComponent_GetInfluenceRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ReflectionProbeComponent_SetInfluenceRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ReflectionProbeComponent_GetBlendDistance(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ReflectionProbeComponent_SetBlendDistance(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern uint ReflectionProbeComponent_GetResolution(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ReflectionProbeComponent_SetResolution(ulong entityID, uint value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float ReflectionProbeComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ReflectionProbeComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool ReflectionProbeComponent_GetActive(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void ReflectionProbeComponent_SetActive(ulong entityID, bool value);
		#endregion

		#region Rigidbody2DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int Rigidbody2DComponent_GetType(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody2DComponent_SetType(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool Rigidbody2DComponent_GetFixedRotation(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody2DComponent_SetFixedRotation(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody2DComponent_GetLinearVelocity(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody2DComponent_SetLinearVelocity(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float Rigidbody2DComponent_GetAngularVelocity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody2DComponent_SetAngularVelocity(ulong entityID, float value);
		#endregion

		#region Rigidbody3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int Rigidbody3DComponent_GetBodyType(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetBodyType(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float Rigidbody3DComponent_GetMass(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetMass(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float Rigidbody3DComponent_GetLinearDrag(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetLinearDrag(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float Rigidbody3DComponent_GetAngularDrag(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetAngularDrag(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool Rigidbody3DComponent_GetDisableGravity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetDisableGravity(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool Rigidbody3DComponent_GetIsTrigger(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void Rigidbody3DComponent_SetIsTrigger(ulong entityID, bool value);
		#endregion

		#region SphereAreaLightComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_GetColor(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_SetColor(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SphereAreaLightComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SphereAreaLightComponent_GetRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_SetRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SphereAreaLightComponent_GetRange(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_SetRange(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool SphereAreaLightComponent_GetCastShadows(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereAreaLightComponent_SetCastShadows(ulong entityID, bool value);
		#endregion

		#region SphereCollider3DComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SphereCollider3DComponent_GetRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereCollider3DComponent_SetRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereCollider3DComponent_GetOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SphereCollider3DComponent_SetOffset(ulong entityID, ref Vector3 value);
		#endregion

		#region SpotLightComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_GetColor(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetColor(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SpotLightComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SpotLightComponent_GetRange(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetRange(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SpotLightComponent_GetInnerCutoff(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetInnerCutoff(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SpotLightComponent_GetOuterCutoff(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetOuterCutoff(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool SpotLightComponent_GetCastShadows(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpotLightComponent_SetCastShadows(ulong entityID, bool value);
		#endregion

		#region SpriteRendererComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpriteRendererComponent_GetColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpriteRendererComponent_SetColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float SpriteRendererComponent_GetTilingFactor(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void SpriteRendererComponent_SetTilingFactor(ulong entityID, float value);
		#endregion

		#region StarNestSkyComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_GetOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetOffset(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetRotation1(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetRotation1(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetRotation2(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetRotation2(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetFormuparam(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetFormuparam(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetStepSize(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetStepSize(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetTile(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetTile(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetBrightness(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetBrightness(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetDarkMatter(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetDarkMatter(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetDistFading(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetDistFading(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetSaturation(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetSaturation(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetIntensity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int StarNestSkyComponent_GetIterations(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetIterations(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int StarNestSkyComponent_GetVolSteps(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetVolSteps(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool StarNestSkyComponent_GetEnableSkybox(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetEnableSkybox(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool StarNestSkyComponent_GetEnableIBL(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetEnableIBL(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StarNestSkyComponent_GetIBLIntensity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StarNestSkyComponent_SetIBLIntensity(ulong entityID, float value);
		#endregion

		#region StreamingVolumeComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StreamingVolumeComponent_GetLoadRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StreamingVolumeComponent_SetLoadRadius(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float StreamingVolumeComponent_GetUnloadRadius(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void StreamingVolumeComponent_SetUnloadRadius(ulong entityID, float value);
		#endregion

		#region TerrainComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetWorldSizeX(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetWorldSizeX(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetWorldSizeZ(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetWorldSizeZ(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetHeightScale(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetHeightScale(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool TerrainComponent_GetProceduralEnabled(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetProceduralEnabled(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int TerrainComponent_GetSeed(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetSeed(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern uint TerrainComponent_GetResolution(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetResolution(ulong entityID, uint value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern uint TerrainComponent_GetOctaves(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetOctaves(ulong entityID, uint value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetFrequency(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetFrequency(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetLacunarity(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetLacunarity(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetPersistence(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetPersistence(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetRidgeBlend(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetRidgeBlend(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetWarpStrength(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetWarpStrength(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetWarpFrequency(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetWarpFrequency(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern uint TerrainComponent_GetTerraceSteps(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetTerraceSteps(ulong entityID, uint value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetTerraceSharpness(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetTerraceSharpness(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TerrainComponent_GetHeightExponent(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetHeightExponent(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool TerrainComponent_GetAutoMaterial(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetAutoMaterial(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern uint TerrainComponent_GetSplatmapGenResolution(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TerrainComponent_SetSplatmapGenResolution(ulong entityID, uint value);
		#endregion

		#region TextComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string TextComponent_GetText(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TextComponent_SetText(ulong entityID, string value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TextComponent_GetColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TextComponent_SetColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TextComponent_GetKerning(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TextComponent_SetKerning(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float TextComponent_GetLineSpacing(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TextComponent_SetLineSpacing(ulong entityID, float value);
		#endregion

		#region TransformComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_GetTranslation(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_SetTranslation(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_GetScale(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_SetScale(ulong entityID, ref Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_GetRotation(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void TransformComponent_SetRotation(ulong entityID, ref Vector3 value);
		#endregion

		#region UIButtonComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_GetNormalColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetNormalColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_GetHoveredColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetHoveredColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_GetPressedColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetPressedColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_GetDisabledColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetDisabledColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UIButtonComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetInteractable(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int UIButtonComponent_GetState(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIButtonComponent_SetState(ulong entityID, int value);
		#endregion

		#region UICanvasComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int UICanvasComponent_GetSortOrder(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UICanvasComponent_SetSortOrder(ulong entityID, int value);
		#endregion

		#region UICheckboxComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UICheckboxComponent_GetIsChecked(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UICheckboxComponent_SetIsChecked(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UICheckboxComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UICheckboxComponent_SetInteractable(ulong entityID, bool value);
		#endregion

		#region UIDropdownComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int UIDropdownComponent_GetSelectedIndex(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIDropdownComponent_SetSelectedIndex(ulong entityID, int value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UIDropdownComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIDropdownComponent_SetInteractable(ulong entityID, bool value);
		#endregion

		#region UIGridLayoutComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIGridLayoutComponent_GetCellSize(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIGridLayoutComponent_SetCellSize(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIGridLayoutComponent_GetSpacing(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIGridLayoutComponent_SetSpacing(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern int UIGridLayoutComponent_GetConstraintCount(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIGridLayoutComponent_SetConstraintCount(ulong entityID, int value);
		#endregion

		#region UIImageComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIImageComponent_GetColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIImageComponent_SetColor(ulong entityID, ref Vector4 value);
		#endregion

		#region UIInputFieldComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string UIInputFieldComponent_GetText(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_SetText(ulong entityID, string value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string UIInputFieldComponent_GetPlaceholder(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_SetPlaceholder(ulong entityID, string value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIInputFieldComponent_GetFontSize(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_SetFontSize(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_GetTextColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_SetTextColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UIInputFieldComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIInputFieldComponent_SetInteractable(ulong entityID, bool value);
		#endregion

		#region UIPanelComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIPanelComponent_GetBackgroundColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIPanelComponent_SetBackgroundColor(ulong entityID, ref Vector4 value);
		#endregion

		#region UIProgressBarComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIProgressBarComponent_GetValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIProgressBarComponent_SetValue(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIProgressBarComponent_GetMinValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIProgressBarComponent_SetMinValue(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIProgressBarComponent_GetMaxValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIProgressBarComponent_SetMaxValue(ulong entityID, float value);
		#endregion

		#region UIRectTransformComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetAnchorMin(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetAnchorMin(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetAnchorMax(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetAnchorMax(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetAnchoredPosition(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetAnchoredPosition(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetSizeDelta(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetSizeDelta(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetPivot(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetPivot(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIRectTransformComponent_GetRotation(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetRotation(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_GetScale(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIRectTransformComponent_SetScale(ulong entityID, ref Vector2 value);
		#endregion

		#region UIScrollViewComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIScrollViewComponent_GetScrollPosition(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIScrollViewComponent_SetScrollPosition(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIScrollViewComponent_GetContentSize(ulong entityID, out Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIScrollViewComponent_SetContentSize(ulong entityID, ref Vector2 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UIScrollViewComponent_GetScrollSpeed(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIScrollViewComponent_SetScrollSpeed(ulong entityID, float value);
		#endregion

		#region UISliderComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UISliderComponent_GetValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UISliderComponent_SetValue(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UISliderComponent_GetMinValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UISliderComponent_SetMinValue(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UISliderComponent_GetMaxValue(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UISliderComponent_SetMaxValue(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UISliderComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UISliderComponent_SetInteractable(ulong entityID, bool value);
		#endregion

		#region UITextComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string UITextComponent_GetText(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_SetText(ulong entityID, string value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UITextComponent_GetFontSize(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_SetFontSize(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_GetColor(ulong entityID, out Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_SetColor(ulong entityID, ref Vector4 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UITextComponent_GetKerning(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_SetKerning(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float UITextComponent_GetLineSpacing(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UITextComponent_SetLineSpacing(ulong entityID, float value);
		#endregion

		#region UIToggleComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UIToggleComponent_GetIsOn(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIToggleComponent_SetIsOn(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool UIToggleComponent_GetInteractable(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIToggleComponent_SetInteractable(ulong entityID, bool value);
		#endregion

		#region UIWorldAnchorComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIWorldAnchorComponent_GetWorldOffset(ulong entityID, out Vector3 value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void UIWorldAnchorComponent_SetWorldOffset(ulong entityID, ref Vector3 value);
		#endregion

		#region VideoOverlayComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool VideoOverlayComponent_GetPlayOnStart(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoOverlayComponent_SetPlayOnStart(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool VideoOverlayComponent_GetSkipOnInput(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoOverlayComponent_SetSkipOnInput(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool VideoOverlayComponent_GetLooping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoOverlayComponent_SetLooping(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float VideoOverlayComponent_GetVolume(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoOverlayComponent_SetVolume(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string VideoOverlayComponent_GetVideoPath(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoOverlayComponent_SetVideoPath(ulong entityID, string value);
		#endregion

		#region VideoSurfaceComponent
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool VideoSurfaceComponent_GetAutoPlay(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoSurfaceComponent_SetAutoPlay(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern bool VideoSurfaceComponent_GetLooping(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoSurfaceComponent_SetLooping(ulong entityID, bool value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern float VideoSurfaceComponent_GetVolume(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoSurfaceComponent_SetVolume(ulong entityID, float value);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern string VideoSurfaceComponent_GetVideoPath(ulong entityID);
		[MethodImpl(MethodImplOptions.InternalCall)]
		internal static extern void VideoSurfaceComponent_SetVideoPath(ulong entityID, string value);
		#endregion

	}
}
