#include "OloEnginePCH.h"
#include "UUID.h"

#include <atomic>
#include <random>

namespace OloEngine
{
    // SplitMix64 over one atomic counter (issue #1420).
    //
    // The previous generator was three unsynchronised file statics (a
    // random_device, an mt19937_64 and a distribution), and parallel mesh
    // submission default-constructed UUIDs on every worker. Two threads racing
    // on the Mersenne Twister state is undefined behaviour and can hand both of
    // them the same value.
    //
    // Here the only shared state is `s_Counter`, advanced with one fetch_add.
    // Each call therefore owns a distinct counter value, and the output is a
    // bijection of that value: `seed + k * gamma` is distinct for every k below
    // 2^64 because gamma is odd, and the SplitMix64 finaliser is invertible. So
    // two UUIDs generated by one process cannot collide before the 64-bit
    // counter wraps, whichever threads drew them. Across processes (IDs already
    // saved in scenes and asset registries) uniqueness stays probabilistic:
    // each process starts at a random 64-bit offset. A thread_local Mersenne
    // Twister would have fixed the race but left in-process uniqueness to chance.
    namespace
    {
        constexpr u64 s_Gamma = 0x9E3779B97F4A7C15ull; // odd, the SplitMix64 increment

        constinit std::atomic<u64> s_Counter{ 0 };

        // Per thread, so a test measuring its own thread is not disturbed by
        // IDs other threads draw at the same time.
        constinit thread_local u64 t_DrawCount = 0;

        [[nodiscard]] constexpr u64 SplitMix64Finalise(u64 z)
        {
            z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
            z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
            return z ^ (z >> 31);
        }

        // Function-local so the first UUID() drawn during static initialisation
        // still sees a seeded generator, and so concurrent first calls are
        // serialised by the magic-static guard. random_device yields 32 bits a
        // call; the old code seeded from ONE draw, which left only 2^32 possible
        // ID streams across all processes.
        [[nodiscard]] u64 ProcessSeed()
        {
            static const u64 s_Seed = []
            {
                std::random_device device;
                return (static_cast<u64>(device()) << 32) ^ static_cast<u64>(device());
            }();
            return s_Seed;
        }

        [[nodiscard]] u64 NextUUIDValue()
        {
            const u64 seed = ProcessSeed();
            for (;;)
            {
                ++t_DrawCount;
                const u64 k = s_Counter.fetch_add(1, std::memory_order_relaxed);
                // 0 is the "no handle" value (AssetHandle, entity lookups), so a
                // fresh ID must never be 0. Exactly one counter value maps to it.
                if (const u64 value = SplitMix64Finalise(seed + k * s_Gamma); value != 0)
                    return value;
            }
        }
    } // namespace

    UUID::UUID()
        : m_UUID(NextUUIDValue())
    {
    }

    u64 UUID::GetDrawCountOnThisThread()
    {
        return t_DrawCount;
    }
} // namespace OloEngine
