#!/usr/bin/env python3
"""Generate the low-poly vegetation meshes the Drift island field plants (issue #880).

The repo had no vegetation mesh at all, and the foliage impostor path needs one:
FoliageRenderer::UpdateImpostorAtlas bails out on an empty MeshPath, so a layer
with UseImpostor stays a flat billboard without it. These two are deliberately
tiny (a few dozen triangles each) because the runtime only ever sees them once,
through the octahedral impostor bake — the atlas is what gets drawn.

Both are authored BASE AT ORIGIN with +Y up, which is what
foliage-impostor-card-rendering.md §3 assumes when it anchors the card by the
world radius: a mesh centred on the origin instead sinks half below the terrain.

AND BOTH CARRY UVs, which is not optional here. Assimp does not synthesise
missing texture coordinates (it does synthesise normals), and Model::ProcessMesh
leaves Vertex::TexCoord at (0, 0) when the mesh has none — so Impostor_Bake.glsl
would sample the layer's albedo texture at one single texel for the whole tree
and bake a flat silhouette. The mapping below is cylindrical: u wraps once around
the Y axis, v runs 0..1 up the mesh, so the canopy picks up real vertical
variation out of the foliage texture.

Run from anywhere:  python generate_vegetation.py
"""

import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))


class Mesh:
    def __init__(self):
        self.verts = []
        self.faces = []

    def v(self, x, y, z):
        self.verts.append((x, y, z))
        return len(self.verts)  # OBJ indices are 1-based

    def tri(self, a, b, c):
        self.faces.append((a, b, c))

    def uv(self, x, y, z):
        """Cylindrical: u wraps once around Y, v is the height. One UV per vertex,
        so the vt index is the v index and faces can be written `v/vt`."""
        u = 0.5 + math.atan2(z, x) / (2.0 * math.pi)
        return u, min(max(y, 0.0), 1.0)

    def write(self, path, name, note):
        with open(path, "w", newline="\n", encoding="utf-8") as f:
            f.write(f"# {name} — generated by generate_vegetation.py (issue #880). Do not hand-edit.\n")
            f.write(f"# {note}\n")
            f.write(f"o {name}\n")
            for x, y, z in self.verts:
                f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
            for x, y, z in self.verts:
                u, w = self.uv(x, y, z)
                f.write(f"vt {u:.4f} {w:.4f}\n")
            for a, b, c in self.faces:
                f.write(f"f {a}/{a} {b}/{b} {c}/{c}\n")
        print(f"{path}: {len(self.verts)} verts, {len(self.verts)} uvs, {len(self.faces)} tris")


def ring(mesh, radius, y, segments, phase=0.0):
    return [mesh.v(radius * math.cos(phase + 2 * math.pi * i / segments),
                   y,
                   radius * math.sin(phase + 2 * math.pi * i / segments))
            for i in range(segments)]


def tube(mesh, lower, upper):
    n = len(lower)
    for i in range(n):
        j = (i + 1) % n
        mesh.tri(lower[i], upper[i], upper[j])
        mesh.tri(lower[i], upper[j], lower[j])


def cone(mesh, radius, base_y, tip_y, segments):
    base = ring(mesh, radius, base_y, segments)
    tip = mesh.v(0.0, tip_y, 0.0)
    for i in range(segments):
        mesh.tri(base[i], tip, base[(i + 1) % segments])
    # Close the skirt so the silhouette is solid from below as well as above.
    centre = mesh.v(0.0, base_y, 0.0)
    for i in range(segments):
        mesh.tri(base[(i + 1) % segments], centre, base[i])


def make_pine():
    """A conifer: tapered trunk plus three stacked skirts. Height 1.0 (the layer's
    MinHeight/MaxHeight scale it), so every instance is authored in unit height."""
    m = Mesh()
    seg = 6
    tube(m, ring(m, 0.045, 0.00, seg), ring(m, 0.030, 0.42, seg))
    cone(m, 0.190, 0.26, 0.62, seg)
    cone(m, 0.150, 0.48, 0.82, seg)
    cone(m, 0.100, 0.68, 1.00, seg)
    return m


def make_palm():
    """A palm: a leaning trunk with a crown of drooping fronds. Same unit height.
    The lean and the frond spread are what make its impostor read differently from
    the pine's at the same distance — a straight silhouette against a bushy one."""
    m = Mesh()
    seg = 6
    lean = 0.12
    # Trunk in three segments so the lean curves rather than shearing.
    rings = []
    for k, (r, y) in enumerate([(0.050, 0.0), (0.042, 0.28), (0.034, 0.55), (0.028, 0.74)]):
        t = k / 3.0
        bend = lean * t * t
        rings.append([m.v(x + bend, y, z) for (x, y, z) in
                      [(r * math.cos(2 * math.pi * i / seg), y, r * math.sin(2 * math.pi * i / seg))
                       for i in range(seg)]])
    for a, b in zip(rings, rings[1:]):
        tube(m, a, b)

    crown_x, crown_y = lean, 0.74
    for i in range(7):
        a = 2 * math.pi * i / 7
        dx, dz = math.cos(a), math.sin(a)
        # Each frond is one flat triangle from the crown out to a drooping tip,
        # with a mid-span kink so it bows instead of pointing straight out.
        base_l = m.v(crown_x - dz * 0.035, crown_y, dx * 0.035)
        base_r = m.v(crown_x + dz * 0.035, crown_y, -dx * 0.035)
        mid = m.v(crown_x + dx * 0.22, crown_y + 0.20, dz * 0.22)
        tip = m.v(crown_x + dx * 0.44, crown_y + 0.02, dz * 0.44)
        m.tri(base_l, mid, base_r)
        m.tri(base_l, tip, mid)
        m.tri(base_r, mid, tip)
    return m


if __name__ == "__main__":
    make_pine().write(os.path.join(HERE, "pine.obj"), "pine",
                      "Conifer, base at origin, unit height. Impostor source for the Drift island field.")
    make_palm().write(os.path.join(HERE, "palm.obj"), "palm",
                      "Palm, base at origin, unit height. Impostor source for the Drift island field.")
