#pragma once

#include "OloEngine/Core/Base.h"
#include "OloEngine/Core/Ref.h"
#include "OloEngine/Math/Math.h"
#include "OloEngine/Renderer/Ocean/OceanFFTGpu.h"
#include "OloEngine/Renderer/Ocean/OceanSpectrum.h"
#include "OloEngine/Renderer/Texture.h"

#include <glm/glm.hpp>

#include <vector>

namespace OloEngine::Ocean
{
    // =========================================================================
    // Runtime owner of one Tessendorf FFT ocean cascade
    // (docs/WATER_FUTURE_IMPROVEMENTS.md §1).
    //
    // Each tick it produces two GPU textures the water shader samples instead
    // of summing Gerstner waves:
    //   * Displacement (RGBA32F): rgb = (dx, height, dz) choppy displacement,
    //     a = foam factor (saturate(1 - Jacobian)).
    //   * Derivatives  (RGBA32F): rgb = surface normal, a = raw Jacobian.
    // Both tile seamlessly (REPEAT) over PatchSize world metres.
    //
    // Two interchangeable producers fill those textures (§6.4 transition path
    // — same output textures, different generation method):
    //   * GPU compute butterfly (OceanFFTGpu, §1.2) — the default. The
    //     spectrum evolution + inverse FFTs + assembly run as compute passes;
    //     no per-tick CPU FFT and no texture upload.
    //   * CPU reference (OceanSpectrum + OceanFFT) — validation baseline and
    //     automatic fallback when compute is unavailable; evaluates the field
    //     on the CPU and uploads it.
    //
    // The base spectrum h0(k) is CPU-generated either way (deterministic
    // mt19937) and regenerated only when the wind/shape params change.
    //
    // A CPU copy of the field is retained so physics/buoyancy can sample the
    // rendered surface with no GPU readback. In GPU mode that copy is a
    // band-limited low-resolution proxy (ExtractBandLimitedH0, ≤64²) — the
    // same waves at the same world positions minus sub-metre detail — so
    // SampleHeight()/GetField() keep working at a fraction of the full-grid
    // CPU cost (the point of the port).
    // =========================================================================
    class OceanFFTField : public RefCounted
    {
      public:
        OceanFFTField() = default;
        ~OceanFFTField() override = default;

        OceanFFTField(const OceanFFTField&) = delete;
        OceanFFTField& operator=(const OceanFFTField&) = delete;

        /// Evaluate the field at `time` seconds. Regenerates the base spectrum
        /// only when the shape params changed. When `uploadToGpu` is true the
        /// GPU textures are produced (requires a live GL context); pass false
        /// for headless/CPU-only use (tests, physics warm-up). When
        /// `useGpuCompute` is also true the textures are generated by the
        /// compute butterfly pipeline (OceanFFTGpu) and the retained CPU field
        /// becomes a band-limited ≤64² physics proxy; with it false (or when
        /// compute is unavailable) the validated CPU path evaluates at full
        /// resolution and uploads, exactly as before the GPU port.
        void Update(const SpectrumParams& params, f32 time, bool uploadToGpu = true, bool useGpuCompute = true);

        [[nodiscard]] u32 GetDisplacementTextureID() const;
        [[nodiscard]] u32 GetDerivativesTextureID() const;
        [[nodiscard]] f32 GetPatchSize() const noexcept
        {
            return m_Params.m_PatchSize;
        }
        [[nodiscard]] f32 GetChoppiness() const noexcept
        {
            return m_Params.m_Choppiness;
        }

        /// CPU height of the surface column above world `worldXZ` (metres),
        /// inverting the choppy horizontal shift with a short fixed-point
        /// iteration. Returns 0 before the first Update(). In GPU-compute mode
        /// this samples the band-limited physics proxy (see class comment).
        [[nodiscard]] f32 SampleHeight(glm::vec2 worldXZ) const;

        /// The retained CPU field. Full resolution on the CPU path; the
        /// band-limited ≤64² physics proxy in GPU-compute mode.
        [[nodiscard]] const DisplacementField& GetField() const noexcept
        {
            return m_Field;
        }

      private:
        // The subset of SpectrumParams that determines h0(k); a change here
        // forces a base-spectrum regeneration. Choppiness/time are excluded
        // (they only affect the per-tick evaluation, not h0).
        struct H0Key
        {
            u32 Resolution = 0u;
            f32 PatchSize = 0.0f;
            f32 WindSpeed = 0.0f;
            glm::vec2 WindDirection{ 0.0f };
            f32 Amplitude = 0.0f;
            f32 Gravity = 0.0f;
            f32 SmallWaveSuppression = 0.0f;
            f32 DirectionalExponent = 0.0f;
            u32 Seed = 0u;
            u32 SpectrumType = 0u; ///< SpectrumType cast to u32 (selector affects h0)
            f32 JonswapGamma = 0.0f;
            f32 JonswapFetch = 0.0f;

            // Bit-exact change detection (a "slider moved" check, not a math
            // equality test) — Math::BitwiseEqual is the sanctioned form, so we
            // don't trip the no-raw-float-== rule. H0Key is a trivially-copyable
            // POD with no padding, so this is well-defined.
            [[nodiscard]] bool operator==(const H0Key& o) const noexcept
            {
                return Math::BitwiseEqual(*this, o);
            }
            [[nodiscard]] bool operator!=(const H0Key& o) const noexcept
            {
                return !(*this == o);
            }
        };
        [[nodiscard]] static H0Key MakeH0Key(const SpectrumParams& p);

        void Upload();
        void EnsureTextures(u32 resolution);
        [[nodiscard]] glm::vec2 SampleHorizontalBilinear(glm::vec2 worldXZ) const;

        SpectrumParams m_Params;
        H0Key m_H0Key;
        bool m_HasH0 = false;
        std::vector<Complex> m_H0;
        DisplacementField m_Field;

        Ref<Texture2D> m_DisplacementTex; // rgb = (dx, h, dz), a = foam
        Ref<Texture2D> m_DerivativesTex;  // rgb = normal,      a = jacobian
        std::vector<glm::vec4> m_DisplacementScratch;
        std::vector<glm::vec4> m_DerivativesScratch;

        // GPU compute butterfly producer (§1.2) + the band-limited h0 the CPU
        // physics proxy is evaluated from while the GPU owns the rendered
        // field. Both are refreshed when h0 regenerates.
        Ref<OceanFFTGpu> m_GpuFFT;
        bool m_GpuH0Dirty = false;
        std::vector<Complex> m_PhysicsH0;
        u32 m_PhysicsResolution = 0u;
    };
} // namespace OloEngine::Ocean
