#include "OloEnginePCH.h"
#include "OloEngine/Renderer/Ocean/OceanSpectrum.h"

#include <cmath>
#include <random>

// =============================================================================
// Tessendorf "Simulating Ocean Water" (2001) spectrum + IFFT field evaluation.
// See OceanSpectrum.h for the contract and OceanFFT.h for the FFT conventions.
// =============================================================================

namespace OloEngine::Ocean
{
    namespace
    {
        constexpr f32 kTwoPi = 6.28318530717958647692f;

        // Wave vector (rad/m) for FFT bins (n, m) of an N×N grid, patch size L.
        [[nodiscard]] glm::vec2 WaveVector(u32 n, u32 m, u32 N, f32 L)
        {
            const f32 kx = kTwoPi * static_cast<f32>(SignedFrequency(n, N)) / L;
            const f32 kz = kTwoPi * static_cast<f32>(SignedFrequency(m, N)) / L;
            return glm::vec2(kx, kz);
        }
    } // namespace

    f32 PhillipsSpectrum(const SpectrumParams& params, glm::vec2 k)
    {
        const f32 kSqr = glm::dot(k, k);
        if (kSqr < 1e-12f)
            return 0.0f; // no energy at the zero wave vector (k = 0)

        const f32 kMag = std::sqrt(kSqr);

        // Largest wave generated by a continuous wind of speed V: L = V²/g.
        const f32 g = params.m_Gravity;
        const f32 largestWave = std::max(params.m_WindSpeed * params.m_WindSpeed / std::max(g, 1e-4f), 1e-4f);

        // Directional term: energy concentrated along the wind heading.
        const glm::vec2 windDir = glm::normalize(params.m_WindDirection + glm::vec2(1e-6f, 0.0f));
        const f32 kDotW = glm::dot(k / kMag, windDir);
        const f32 directional = std::pow(std::abs(kDotW), params.m_DirectionalExponent);

        // Phillips: A · exp(-1/(kL)²) / k⁴ · |k̂·ŵ|^p
        const f32 kL = kMag * largestWave;
        const f32 k4 = kSqr * kSqr;
        f32 spectrum = params.m_Amplitude * std::exp(-1.0f / (kL * kL)) / k4 * directional;

        // Suppress waves much shorter than `l` (Tessendorf's exp(-k²l²) term):
        // damps the high-frequency tail that the FFT grid can't resolve cleanly.
        if (params.m_SmallWaveSuppression > 0.0f)
        {
            const f32 l = params.m_SmallWaveSuppression;
            spectrum *= std::exp(-kSqr * l * l);
        }

        return spectrum;
    }

    f32 JonswapSpectrum(const SpectrumParams& params, glm::vec2 k)
    {
        const f32 kSqr = glm::dot(k, k);
        if (kSqr < 1e-12f)
            return 0.0f; // no energy at the zero wave vector (k = 0)

        const f32 kMag = std::sqrt(kSqr);
        const f32 g = std::max(params.m_Gravity, 1e-4f);

        // Deep-water dispersion maps the wave vector to an angular frequency:
        // ω = sqrt(g·|k|) (same relation as Dispersion()).
        const f32 omega = std::sqrt(g * kMag);
        if (omega < 1e-4f)
            return 0.0f;

        // JONSWAP peak angular frequency from the fetch relation
        // (Hasselmann et al. 1973): ωₚ = 22·(g²/(V·F))^(1/3). Shorter fetch /
        // weaker wind ⇒ higher ωₚ ⇒ the peak sits at a shorter wavelength.
        const f32 windSpeed = std::max(params.m_WindSpeed, 1e-3f);
        const f32 fetch = std::max(params.m_JonswapFetch, 1.0f);
        const f32 omegaPeak = 22.0f * std::cbrt((g * g) / (windSpeed * fetch));

        // 1-D fetch-limited frequency spectrum (the §1.4 formula):
        //   S(ω) = α·g²/ω⁵ · exp(-5/4·(ωₚ/ω)⁴) · γ^r,
        //   r = exp(-(ω-ωₚ)²/(2σ²ωₚ²)),  σ = 0.07 (ω≤ωₚ) else 0.09.
        // α (the Phillips equilibrium constant) is a constant scale that the
        // OceanFFTField RMS normalisation absorbs, so it folds into m_Amplitude
        // exactly as the Phillips spectrum's A does — only the *shape* differs.
        const f32 peakRatio = omegaPeak / omega;
        const f32 peakRatio4 = peakRatio * peakRatio * peakRatio * peakRatio;
        const f32 omega5 = omega * omega * omega * omega * omega;
        const f32 pm = (g * g) / omega5 * std::exp(-1.25f * peakRatio4);

        const f32 sigma = (omega <= omegaPeak) ? 0.07f : 0.09f;
        const f32 dOmega = omega - omegaPeak;
        const f32 r = std::exp(-(dOmega * dOmega) / (2.0f * sigma * sigma * omegaPeak * omegaPeak));
        const f32 gamma = std::max(params.m_JonswapGamma, 1.0f);
        const f32 sOmega = pm * std::pow(gamma, r);

        // Convert the 1-D frequency density S(ω) to a 2-D wave-vector density:
        //   Ψ(k) = S(ω)·(dω/dk)·(1/k),  dω/dk = g/(2ω) (deep water).
        // The 1/k is the polar→cartesian Jacobian (dk dθ → dkx dkz) so the
        // energy spreads correctly across the (kx, kz) plane.
        const f32 dOmegaDk = g / (2.0f * omega);
        f32 spectrum = params.m_Amplitude * sOmega * dOmegaDk / kMag;

        // Directional term — identical to Phillips so the wind-direction and
        // directional-exponent controls behave the same across both spectra.
        const glm::vec2 windDir = glm::normalize(params.m_WindDirection + glm::vec2(1e-6f, 0.0f));
        const f32 kDotW = glm::dot(k / kMag, windDir);
        spectrum *= std::pow(std::abs(kDotW), params.m_DirectionalExponent);

        // Suppress sub-grid waves (Tessendorf's exp(-k²l²) term), same as Phillips.
        if (params.m_SmallWaveSuppression > 0.0f)
        {
            const f32 l = params.m_SmallWaveSuppression;
            spectrum *= std::exp(-kSqr * l * l);
        }

        return spectrum;
    }

    f32 SpectrumEnergy(const SpectrumParams& params, glm::vec2 k)
    {
        switch (params.m_SpectrumType)
        {
            case SpectrumType::JONSWAP:
                return JonswapSpectrum(params, k);
            case SpectrumType::Phillips:
            default:
                return PhillipsSpectrum(params, k);
        }
    }

    f32 Dispersion(f32 kMagnitude, f32 gravity)
    {
        return std::sqrt(std::max(gravity * kMagnitude, 0.0f));
    }

    std::vector<Complex> GenerateH0(const SpectrumParams& params)
    {
        const u32 N = params.m_Resolution;
        OLO_CORE_ASSERT(IsPowerOfTwo(N), "Ocean spectrum resolution must be a power of two");

        std::vector<Complex> h0(static_cast<sizet>(N) * N);

        std::mt19937 rng(params.m_Seed);
        std::normal_distribution<f32> gauss(0.0f, 1.0f);

        const f32 invSqrt2 = 0.70710678118654752440f;
        for (u32 m = 0u; m < N; ++m)
        {
            for (u32 n = 0u; n < N; ++n)
            {
                const glm::vec2 k = WaveVector(n, m, N, params.m_PatchSize);
                const f32 amp = std::sqrt(SpectrumEnergy(params, k));
                const f32 xr = gauss(rng);
                const f32 xi = gauss(rng);
                h0[static_cast<sizet>(m) * N + n] = invSqrt2 * Complex(xr, xi) * amp;
            }
        }
        return h0;
    }

    std::vector<Complex> ExtractBandLimitedH0(const std::vector<Complex>& h0, u32 resolution, u32 targetResolution)
    {
        const u32 N = resolution;
        const u32 Ns = targetResolution;
        OLO_CORE_ASSERT(IsPowerOfTwo(N) && IsPowerOfTwo(Ns), "ExtractBandLimitedH0: resolutions must be powers of two");
        OLO_CORE_ASSERT(h0.size() == static_cast<sizet>(N) * N, "ExtractBandLimitedH0: h0 size mismatch");

        if (Ns >= N)
            return h0;

        // FFT1D's inverse divides by the transform length, so the 2D inverse
        // carries 1/N² — a grid-size-dependent factor. The same coefficient
        // therefore comes out (N/Ns)² larger on the small grid; scale the
        // copied bins by (Ns/N)² so the small-grid IFFT lands on the SAME
        // spatial amplitudes (in metres) as the band-limited full surface.
        const f32 scale = (static_cast<f32>(Ns) / static_cast<f32>(N)) * (static_cast<f32>(Ns) / static_cast<f32>(N));

        std::vector<Complex> small(static_cast<sizet>(Ns) * Ns, Complex(0.0f, 0.0f));
        const i32 nyquist = static_cast<i32>(Ns / 2u);
        for (u32 m = 0u; m < Ns; ++m)
        {
            const i32 fm = SignedFrequency(m, Ns);
            if (fm == nyquist)
                continue; // small grid can't represent ±Ns/2 as distinct bins
            for (u32 n = 0u; n < Ns; ++n)
            {
                const i32 fn = SignedFrequency(n, Ns);
                if (fn == nyquist)
                    continue;

                // Same signed frequency ⇒ same wave vector (same patch size).
                const u32 srcN = static_cast<u32>((fn + static_cast<i32>(N)) % static_cast<i32>(N));
                const u32 srcM = static_cast<u32>((fm + static_cast<i32>(N)) % static_cast<i32>(N));
                small[static_cast<sizet>(m) * Ns + n] = scale * h0[static_cast<sizet>(srcM) * N + srcN];
            }
        }
        return small;
    }

    DisplacementField EvaluateField(const SpectrumParams& params, const std::vector<Complex>& h0, f32 time)
    {
        const u32 N = params.m_Resolution;
        OLO_CORE_ASSERT(IsPowerOfTwo(N), "Ocean spectrum resolution must be a power of two");
        OLO_CORE_ASSERT(h0.size() == static_cast<sizet>(N) * N, "h0 size mismatch with resolution");

        const sizet count = static_cast<sizet>(N) * N;

        // Frequency-domain buffers for the inverse transforms:
        //   hTilde       — animated height spectrum h̃(k,t)
        //   dispX/dispZ  — horizontal displacement (choppiness) spectra
        //   slopeX/slopeZ— slope spectra (for analytic normals)
        //   dxdx/dzdz/dxdz — displacement-gradient spectra (for the Jacobian)
        std::vector<Complex> hTilde(count);
        std::vector<Complex> dispX(count);
        std::vector<Complex> dispZ(count);
        std::vector<Complex> slopeX(count);
        std::vector<Complex> slopeZ(count);
        std::vector<Complex> dxdx(count);
        std::vector<Complex> dzdz(count);
        std::vector<Complex> dxdz(count);

        for (u32 m = 0u; m < N; ++m)
        {
            for (u32 n = 0u; n < N; ++n)
            {
                const sizet idx = static_cast<sizet>(m) * N + n;
                const glm::vec2 k = WaveVector(n, m, N, params.m_PatchSize);
                const f32 kMag = glm::length(k);

                // h̃(k,t) = h0(k) e^{iωt} + conj(h0(-k)) e^{-iωt}. This guarantees
                // h̃(-k) = conj(h̃(k)), so every inverse FFT below is real.
                const f32 omega = Dispersion(kMag, params.m_Gravity) * time;
                const Complex phasePlus(std::cos(omega), std::sin(omega));
                const Complex phaseMinus(std::cos(omega), -std::sin(omega));

                const u32 mn = (N - n) % N;
                const u32 mm = (N - m) % N;
                const Complex h0k = h0[idx];
                const Complex h0mk = h0[static_cast<sizet>(mm) * N + mn];

                const Complex h = h0k * phasePlus + std::conj(h0mk) * phaseMinus;
                hTilde[idx] = h;

                // Choppy horizontal displacement: D = IFFT(-i (k/|k|) h̃).
                // Slopes: ∂h/∂x = IFFT(i kx h̃), ∂h/∂z = IFFT(i kz h̃).
                // Displacement gradients (Jacobian): ∂Dx/∂x = IFFT(kx²/|k| h̃) etc.
                const Complex iH(-h.imag(), h.real()); // i * h
                if (kMag > 1e-6f)
                {
                    const f32 invK = 1.0f / kMag;
                    // -i (kx/|k|) h = (k/|k|) * (-i h); (-i h) = (h.imag(), -h.real())
                    const Complex miH(h.imag(), -h.real()); // -i * h
                    dispX[idx] = (k.x * invK) * miH;
                    dispZ[idx] = (k.y * invK) * miH;

                    slopeX[idx] = k.x * iH;
                    slopeZ[idx] = k.y * iH;

                    dxdx[idx] = (k.x * k.x * invK) * h;
                    dzdz[idx] = (k.y * k.y * invK) * h;
                    dxdz[idx] = (k.x * k.y * invK) * h;
                }
                else
                {
                    dispX[idx] = Complex(0.0f, 0.0f);
                    dispZ[idx] = Complex(0.0f, 0.0f);
                    slopeX[idx] = Complex(0.0f, 0.0f);
                    slopeZ[idx] = Complex(0.0f, 0.0f);
                    dxdx[idx] = Complex(0.0f, 0.0f);
                    dzdz[idx] = Complex(0.0f, 0.0f);
                    dxdz[idx] = Complex(0.0f, 0.0f);
                }
            }
        }

        FFT2D(hTilde, N, N, /*inverse=*/true);
        FFT2D(dispX, N, N, true);
        FFT2D(dispZ, N, N, true);
        FFT2D(slopeX, N, N, true);
        FFT2D(slopeZ, N, N, true);
        FFT2D(dxdx, N, N, true);
        FFT2D(dzdz, N, N, true);
        FFT2D(dxdz, N, N, true);

        DisplacementField field;
        field.m_Resolution = N;
        field.m_Height.resize(count);
        field.m_HorizontalDisplacement.resize(count);
        field.m_Normal.resize(count);
        field.m_Jacobian.resize(count);

        const f32 lambda = params.m_Choppiness;
        for (sizet i = 0; i < count; ++i)
        {
            field.m_Height[i] = hTilde[i].real();
            field.m_HorizontalDisplacement[i] = glm::vec2(lambda * dispX[i].real(), lambda * dispZ[i].real());

            // Analytic normal from the slope field.
            const f32 sx = slopeX[i].real();
            const f32 sz = slopeZ[i].real();
            field.m_Normal[i] = glm::normalize(glm::vec3(-sx, 1.0f, -sz));

            // Folding Jacobian of the horizontal displacement map. J < 1 marks
            // compression (wave crests folding over) — the foam source (§2.1).
            const f32 jxx = 1.0f + lambda * dxdx[i].real();
            const f32 jzz = 1.0f + lambda * dzdz[i].real();
            const f32 jxz = lambda * dxdz[i].real();
            field.m_Jacobian[i] = jxx * jzz - jxz * jxz;
        }

        return field;
    }

    f32 SampleHeightBilinear(const DisplacementField& field, f32 patchSize, glm::vec2 worldXZ)
    {
        if (!field.IsValid() || patchSize <= 0.0f)
            return 0.0f;

        const u32 N = field.m_Resolution;
        const f32 fN = static_cast<f32>(N);

        // Map world XZ → grid coordinates, wrapping by the patch period.
        f32 gx = worldXZ.x / patchSize * fN;
        f32 gz = worldXZ.y / patchSize * fN;
        gx -= std::floor(gx / fN) * fN;
        gz -= std::floor(gz / fN) * fN;

        const u32 x0 = static_cast<u32>(gx) % N;
        const u32 z0 = static_cast<u32>(gz) % N;
        const u32 x1 = (x0 + 1u) % N;
        const u32 z1 = (z0 + 1u) % N;
        const f32 tx = gx - std::floor(gx);
        const f32 tz = gz - std::floor(gz);

        const f32 h00 = field.m_Height[static_cast<sizet>(z0) * N + x0];
        const f32 h10 = field.m_Height[static_cast<sizet>(z0) * N + x1];
        const f32 h01 = field.m_Height[static_cast<sizet>(z1) * N + x0];
        const f32 h11 = field.m_Height[static_cast<sizet>(z1) * N + x1];

        const f32 a = glm::mix(h00, h10, tx);
        const f32 b = glm::mix(h01, h11, tx);
        return glm::mix(a, b, tz);
    }
} // namespace OloEngine::Ocean
