// Auto-generated by OloHeaderTool — DO NOT EDIT MANUALLY

namespace OloEngine
{
	public partial class AudioSoundGraphComponent : Component
	{
		public float Volume
		{
			get => InternalCalls.AudioSoundGraphComponent_GetVolume(Entity.ID);
			set => InternalCalls.AudioSoundGraphComponent_SetVolume(Entity.ID, value);
		}

		public float Pitch
		{
			get => InternalCalls.AudioSoundGraphComponent_GetPitch(Entity.ID);
			set => InternalCalls.AudioSoundGraphComponent_SetPitch(Entity.ID, value);
		}

		public bool Looping
		{
			get => InternalCalls.AudioSoundGraphComponent_GetLooping(Entity.ID);
			set => InternalCalls.AudioSoundGraphComponent_SetLooping(Entity.ID, value);
		}

		public bool PlayOnAwake
		{
			get => InternalCalls.AudioSoundGraphComponent_GetPlayOnAwake(Entity.ID);
			set => InternalCalls.AudioSoundGraphComponent_SetPlayOnAwake(Entity.ID, value);
		}

		public ulong SoundGraphHandle
		{
			get => InternalCalls.AudioSoundGraphComponent_GetSoundGraphHandle(Entity.ID);
			set => InternalCalls.AudioSoundGraphComponent_SetSoundGraphHandle(Entity.ID, value);
		}
	}

	public partial class AudioSourceComponent : Component
	{
		public float Volume
		{
			get => InternalCalls.AudioSourceComponent_GetVolume(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetVolume(Entity.ID, value);
		}

		public float Pitch
		{
			get => InternalCalls.AudioSourceComponent_GetPitch(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetPitch(Entity.ID, value);
		}

		public bool PlayOnAwake
		{
			get => InternalCalls.AudioSourceComponent_GetPlayOnAwake(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetPlayOnAwake(Entity.ID, value);
		}

		public bool Looping
		{
			get => InternalCalls.AudioSourceComponent_GetLooping(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetLooping(Entity.ID, value);
		}

		public bool Spatialization
		{
			get => InternalCalls.AudioSourceComponent_GetSpatialization(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetSpatialization(Entity.ID, value);
		}

		public int AttenuationModel
		{
			get => InternalCalls.AudioSourceComponent_GetAttenuationModel(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetAttenuationModel(Entity.ID, value);
		}

		public float RollOff
		{
			get => InternalCalls.AudioSourceComponent_GetRollOff(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetRollOff(Entity.ID, value);
		}

		public float MinGain
		{
			get => InternalCalls.AudioSourceComponent_GetMinGain(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetMinGain(Entity.ID, value);
		}

		public float MaxGain
		{
			get => InternalCalls.AudioSourceComponent_GetMaxGain(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetMaxGain(Entity.ID, value);
		}

		public float MinDistance
		{
			get => InternalCalls.AudioSourceComponent_GetMinDistance(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetMinDistance(Entity.ID, value);
		}

		public float MaxDistance
		{
			get => InternalCalls.AudioSourceComponent_GetMaxDistance(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetMaxDistance(Entity.ID, value);
		}

		public float ConeInnerAngle
		{
			get => InternalCalls.AudioSourceComponent_GetConeInnerAngle(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetConeInnerAngle(Entity.ID, value);
		}

		public float ConeOuterAngle
		{
			get => InternalCalls.AudioSourceComponent_GetConeOuterAngle(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetConeOuterAngle(Entity.ID, value);
		}

		public float ConeOuterGain
		{
			get => InternalCalls.AudioSourceComponent_GetConeOuterGain(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetConeOuterGain(Entity.ID, value);
		}

		public float DopplerFactor
		{
			get => InternalCalls.AudioSourceComponent_GetDopplerFactor(Entity.ID);
			set => InternalCalls.AudioSourceComponent_SetDopplerFactor(Entity.ID, value);
		}
	}

	public partial class BoxCollider2DComponent : Component
	{
		public Vector2 Offset
		{
			get
			{
				InternalCalls.BoxCollider2DComponent_GetOffset(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.BoxCollider2DComponent_SetOffset(Entity.ID, ref value);
		}

		public Vector2 Size
		{
			get
			{
				InternalCalls.BoxCollider2DComponent_GetSize(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.BoxCollider2DComponent_SetSize(Entity.ID, ref value);
		}

		public float Density
		{
			get => InternalCalls.BoxCollider2DComponent_GetDensity(Entity.ID);
			set => InternalCalls.BoxCollider2DComponent_SetDensity(Entity.ID, value);
		}

		public float Friction
		{
			get => InternalCalls.BoxCollider2DComponent_GetFriction(Entity.ID);
			set => InternalCalls.BoxCollider2DComponent_SetFriction(Entity.ID, value);
		}

		public float Restitution
		{
			get => InternalCalls.BoxCollider2DComponent_GetRestitution(Entity.ID);
			set => InternalCalls.BoxCollider2DComponent_SetRestitution(Entity.ID, value);
		}
	}

	public partial class BoxCollider3DComponent : Component
	{
		public Vector3 HalfExtents
		{
			get
			{
				InternalCalls.BoxCollider3DComponent_GetHalfExtents(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.BoxCollider3DComponent_SetHalfExtents(Entity.ID, ref value);
		}

		public Vector3 Offset
		{
			get
			{
				InternalCalls.BoxCollider3DComponent_GetOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.BoxCollider3DComponent_SetOffset(Entity.ID, ref value);
		}
	}

	public partial class CameraComponent : Component
	{
		public int ProjectionType
		{
			get => InternalCalls.CameraComponent_GetProjectionType(Entity.ID);
			set => InternalCalls.CameraComponent_SetProjectionType(Entity.ID, value);
		}

		public float PerspectiveFOV
		{
			get => InternalCalls.CameraComponent_GetPerspectiveFOV(Entity.ID);
			set => InternalCalls.CameraComponent_SetPerspectiveFOV(Entity.ID, value);
		}

		public float PerspectiveNearClip
		{
			get => InternalCalls.CameraComponent_GetPerspectiveNearClip(Entity.ID);
			set => InternalCalls.CameraComponent_SetPerspectiveNearClip(Entity.ID, value);
		}

		public float PerspectiveFarClip
		{
			get => InternalCalls.CameraComponent_GetPerspectiveFarClip(Entity.ID);
			set => InternalCalls.CameraComponent_SetPerspectiveFarClip(Entity.ID, value);
		}

		public float OrthographicSize
		{
			get => InternalCalls.CameraComponent_GetOrthographicSize(Entity.ID);
			set => InternalCalls.CameraComponent_SetOrthographicSize(Entity.ID, value);
		}

		public float OrthographicNearClip
		{
			get => InternalCalls.CameraComponent_GetOrthographicNearClip(Entity.ID);
			set => InternalCalls.CameraComponent_SetOrthographicNearClip(Entity.ID, value);
		}

		public float OrthographicFarClip
		{
			get => InternalCalls.CameraComponent_GetOrthographicFarClip(Entity.ID);
			set => InternalCalls.CameraComponent_SetOrthographicFarClip(Entity.ID, value);
		}

		public bool Primary
		{
			get => InternalCalls.CameraComponent_GetPrimary(Entity.ID);
			set => InternalCalls.CameraComponent_SetPrimary(Entity.ID, value);
		}

		public bool FixedAspectRatio
		{
			get => InternalCalls.CameraComponent_GetFixedAspectRatio(Entity.ID);
			set => InternalCalls.CameraComponent_SetFixedAspectRatio(Entity.ID, value);
		}
	}

	public partial class CapsuleCollider3DComponent : Component
	{
		public float Radius
		{
			get => InternalCalls.CapsuleCollider3DComponent_GetRadius(Entity.ID);
			set => InternalCalls.CapsuleCollider3DComponent_SetRadius(Entity.ID, value);
		}

		public float HalfHeight
		{
			get => InternalCalls.CapsuleCollider3DComponent_GetHalfHeight(Entity.ID);
			set => InternalCalls.CapsuleCollider3DComponent_SetHalfHeight(Entity.ID, value);
		}

		public Vector3 Offset
		{
			get
			{
				InternalCalls.CapsuleCollider3DComponent_GetOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.CapsuleCollider3DComponent_SetOffset(Entity.ID, ref value);
		}
	}

	public partial class CharacterController3DComponent : Component
	{
		public float SlopeLimit
		{
			get => InternalCalls.CharacterController3DComponent_GetSlopeLimit(Entity.ID);
			set => InternalCalls.CharacterController3DComponent_SetSlopeLimit(Entity.ID, value);
		}

		public float StepOffset
		{
			get => InternalCalls.CharacterController3DComponent_GetStepOffset(Entity.ID);
			set => InternalCalls.CharacterController3DComponent_SetStepOffset(Entity.ID, value);
		}

		public float JumpPower
		{
			get => InternalCalls.CharacterController3DComponent_GetJumpPower(Entity.ID);
			set => InternalCalls.CharacterController3DComponent_SetJumpPower(Entity.ID, value);
		}

		public bool DisableGravity
		{
			get => InternalCalls.CharacterController3DComponent_GetDisableGravity(Entity.ID);
			set => InternalCalls.CharacterController3DComponent_SetDisableGravity(Entity.ID, value);
		}
	}

	public partial class CinematicComponent : Component
	{
		public ulong Sequence
		{
			get => InternalCalls.CinematicComponent_GetSequence(Entity.ID);
			set => InternalCalls.CinematicComponent_SetSequence(Entity.ID, value);
		}

		public bool PlayOnStart
		{
			get => InternalCalls.CinematicComponent_GetPlayOnStart(Entity.ID);
			set => InternalCalls.CinematicComponent_SetPlayOnStart(Entity.ID, value);
		}

		public bool Loop
		{
			get => InternalCalls.CinematicComponent_GetLoop(Entity.ID);
			set => InternalCalls.CinematicComponent_SetLoop(Entity.ID, value);
		}

		public float PlaybackSpeed
		{
			get => InternalCalls.CinematicComponent_GetPlaybackSpeed(Entity.ID);
			set => InternalCalls.CinematicComponent_SetPlaybackSpeed(Entity.ID, value);
		}

		public bool Playing
		{
			get => InternalCalls.CinematicComponent_GetPlaying(Entity.ID);
			set => InternalCalls.CinematicComponent_SetPlaying(Entity.ID, value);
		}
	}

	public partial class CircleCollider2DComponent : Component
	{
		public Vector2 Offset
		{
			get
			{
				InternalCalls.CircleCollider2DComponent_GetOffset(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.CircleCollider2DComponent_SetOffset(Entity.ID, ref value);
		}

		public float Radius
		{
			get => InternalCalls.CircleCollider2DComponent_GetRadius(Entity.ID);
			set => InternalCalls.CircleCollider2DComponent_SetRadius(Entity.ID, value);
		}

		public float Density
		{
			get => InternalCalls.CircleCollider2DComponent_GetDensity(Entity.ID);
			set => InternalCalls.CircleCollider2DComponent_SetDensity(Entity.ID, value);
		}

		public float Friction
		{
			get => InternalCalls.CircleCollider2DComponent_GetFriction(Entity.ID);
			set => InternalCalls.CircleCollider2DComponent_SetFriction(Entity.ID, value);
		}

		public float Restitution
		{
			get => InternalCalls.CircleCollider2DComponent_GetRestitution(Entity.ID);
			set => InternalCalls.CircleCollider2DComponent_SetRestitution(Entity.ID, value);
		}
	}

	public partial class CircleRendererComponent : Component
	{
		public Vector4 Color
		{
			get
			{
				InternalCalls.CircleRendererComponent_GetColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.CircleRendererComponent_SetColor(Entity.ID, ref value);
		}

		public float Thickness
		{
			get => InternalCalls.CircleRendererComponent_GetThickness(Entity.ID);
			set => InternalCalls.CircleRendererComponent_SetThickness(Entity.ID, value);
		}

		public float Fade
		{
			get => InternalCalls.CircleRendererComponent_GetFade(Entity.ID);
			set => InternalCalls.CircleRendererComponent_SetFade(Entity.ID, value);
		}
	}

	public partial class DirectionalLightComponent : Component
	{
		public Vector3 Color
		{
			get
			{
				InternalCalls.DirectionalLightComponent_GetColor(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.DirectionalLightComponent_SetColor(Entity.ID, ref value);
		}

		public float Intensity
		{
			get => InternalCalls.DirectionalLightComponent_GetIntensity(Entity.ID);
			set => InternalCalls.DirectionalLightComponent_SetIntensity(Entity.ID, value);
		}

		public bool CastShadows
		{
			get => InternalCalls.DirectionalLightComponent_GetCastShadows(Entity.ID);
			set => InternalCalls.DirectionalLightComponent_SetCastShadows(Entity.ID, value);
		}
	}

	public partial class LightProbeComponent : Component
	{
		public float InfluenceRadius
		{
			get => InternalCalls.LightProbeComponent_GetInfluenceRadius(Entity.ID);
			set => InternalCalls.LightProbeComponent_SetInfluenceRadius(Entity.ID, value);
		}

		public float Intensity
		{
			get => InternalCalls.LightProbeComponent_GetIntensity(Entity.ID);
			set => InternalCalls.LightProbeComponent_SetIntensity(Entity.ID, value);
		}

		public bool Active
		{
			get => InternalCalls.LightProbeComponent_GetActive(Entity.ID);
			set => InternalCalls.LightProbeComponent_SetActive(Entity.ID, value);
		}
	}

	public partial class LightProbeVolumeComponent : Component
	{
		public Vector3 BoundsMin
		{
			get
			{
				InternalCalls.LightProbeVolumeComponent_GetBoundsMin(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.LightProbeVolumeComponent_SetBoundsMin(Entity.ID, ref value);
		}

		public Vector3 BoundsMax
		{
			get
			{
				InternalCalls.LightProbeVolumeComponent_GetBoundsMax(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.LightProbeVolumeComponent_SetBoundsMax(Entity.ID, ref value);
		}

		public float Spacing
		{
			get => InternalCalls.LightProbeVolumeComponent_GetSpacing(Entity.ID);
			set => InternalCalls.LightProbeVolumeComponent_SetSpacing(Entity.ID, value);
		}

		public float Intensity
		{
			get => InternalCalls.LightProbeVolumeComponent_GetIntensity(Entity.ID);
			set => InternalCalls.LightProbeVolumeComponent_SetIntensity(Entity.ID, value);
		}

		public bool Active
		{
			get => InternalCalls.LightProbeVolumeComponent_GetActive(Entity.ID);
			set => InternalCalls.LightProbeVolumeComponent_SetActive(Entity.ID, value);
		}
	}

	public partial class MaterialComponent : Component
	{
		public Vector4 AlbedoColor
		{
			get
			{
				InternalCalls.MaterialComponent_GetAlbedoColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.MaterialComponent_SetAlbedoColor(Entity.ID, ref value);
		}

		public float Metallic
		{
			get => InternalCalls.MaterialComponent_GetMetallic(Entity.ID);
			set => InternalCalls.MaterialComponent_SetMetallic(Entity.ID, value);
		}

		public float Roughness
		{
			get => InternalCalls.MaterialComponent_GetRoughness(Entity.ID);
			set => InternalCalls.MaterialComponent_SetRoughness(Entity.ID, value);
		}

		public Vector4 Emissive
		{
			get
			{
				InternalCalls.MaterialComponent_GetEmissive(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.MaterialComponent_SetEmissive(Entity.ID, ref value);
		}
	}

	public partial class NameplateComponent : Component
	{
		public bool Enabled
		{
			get => InternalCalls.NameplateComponent_GetEnabled(Entity.ID);
			set => InternalCalls.NameplateComponent_SetEnabled(Entity.ID, value);
		}

		public bool ShowHealthBar
		{
			get => InternalCalls.NameplateComponent_GetShowHealthBar(Entity.ID);
			set => InternalCalls.NameplateComponent_SetShowHealthBar(Entity.ID, value);
		}

		public bool ShowManaBar
		{
			get => InternalCalls.NameplateComponent_GetShowManaBar(Entity.ID);
			set => InternalCalls.NameplateComponent_SetShowManaBar(Entity.ID, value);
		}

		public Vector3 WorldOffset
		{
			get
			{
				InternalCalls.NameplateComponent_GetWorldOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.NameplateComponent_SetWorldOffset(Entity.ID, ref value);
		}

		public Vector2 BarSize
		{
			get
			{
				InternalCalls.NameplateComponent_GetBarSize(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.NameplateComponent_SetBarSize(Entity.ID, ref value);
		}

		public Vector4 HealthBarColor
		{
			get
			{
				InternalCalls.NameplateComponent_GetHealthBarColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.NameplateComponent_SetHealthBarColor(Entity.ID, ref value);
		}

		public Vector4 ManaBarColor
		{
			get
			{
				InternalCalls.NameplateComponent_GetManaBarColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.NameplateComponent_SetManaBarColor(Entity.ID, ref value);
		}

		public Vector4 BarBackgroundColor
		{
			get
			{
				InternalCalls.NameplateComponent_GetBarBackgroundColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.NameplateComponent_SetBarBackgroundColor(Entity.ID, ref value);
		}

		public float ManaBarGap
		{
			get => InternalCalls.NameplateComponent_GetManaBarGap(Entity.ID);
			set => InternalCalls.NameplateComponent_SetManaBarGap(Entity.ID, value);
		}
	}

	public partial class NavAgentComponent : Component
	{
		public float MaxSpeed
		{
			get => InternalCalls.NavAgentComponent_GetMaxSpeed(Entity.ID);
			set => InternalCalls.NavAgentComponent_SetMaxSpeed(Entity.ID, value);
		}

		public float Acceleration
		{
			get => InternalCalls.NavAgentComponent_GetAcceleration(Entity.ID);
			set => InternalCalls.NavAgentComponent_SetAcceleration(Entity.ID, value);
		}

		public float StoppingDistance
		{
			get => InternalCalls.NavAgentComponent_GetStoppingDistance(Entity.ID);
			set => InternalCalls.NavAgentComponent_SetStoppingDistance(Entity.ID, value);
		}

		public bool LockYAxis
		{
			get => InternalCalls.NavAgentComponent_GetLockYAxis(Entity.ID);
			set => InternalCalls.NavAgentComponent_SetLockYAxis(Entity.ID, value);
		}

		public Vector3 TargetPosition
		{
			get
			{
				InternalCalls.NavAgentComponent_GetTargetPosition(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.NavAgentComponent_SetTargetPosition(Entity.ID, ref value);
		}
	}

	public partial class NavMeshBoundsComponent : Component
	{
		public Vector3 Min
		{
			get
			{
				InternalCalls.NavMeshBoundsComponent_GetMin(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.NavMeshBoundsComponent_SetMin(Entity.ID, ref value);
		}

		public Vector3 Max
		{
			get
			{
				InternalCalls.NavMeshBoundsComponent_GetMax(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.NavMeshBoundsComponent_SetMax(Entity.ID, ref value);
		}
	}

	public partial class ParticleSystemComponent : Component
	{
		public bool Playing
		{
			get => InternalCalls.ParticleSystemComponent_GetPlaying(Entity.ID);
			set => InternalCalls.ParticleSystemComponent_SetPlaying(Entity.ID, value);
		}

		public bool Looping
		{
			get => InternalCalls.ParticleSystemComponent_GetLooping(Entity.ID);
			set => InternalCalls.ParticleSystemComponent_SetLooping(Entity.ID, value);
		}

		public float EmissionRate
		{
			get => InternalCalls.ParticleSystemComponent_GetEmissionRate(Entity.ID);
			set => InternalCalls.ParticleSystemComponent_SetEmissionRate(Entity.ID, value);
		}

		public float WindInfluence
		{
			get => InternalCalls.ParticleSystemComponent_GetWindInfluence(Entity.ID);
			set => InternalCalls.ParticleSystemComponent_SetWindInfluence(Entity.ID, value);
		}
	}

	public partial class PhysicsJoint3DComponent : Component
	{
		public int JointType
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetJointType(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetJointType(Entity.ID, value);
		}

		public Vector3 LocalAnchorA
		{
			get
			{
				InternalCalls.PhysicsJoint3DComponent_GetLocalAnchorA(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.PhysicsJoint3DComponent_SetLocalAnchorA(Entity.ID, ref value);
		}

		public Vector3 LocalAnchorB
		{
			get
			{
				InternalCalls.PhysicsJoint3DComponent_GetLocalAnchorB(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.PhysicsJoint3DComponent_SetLocalAnchorB(Entity.ID, ref value);
		}

		public Vector3 Axis
		{
			get
			{
				InternalCalls.PhysicsJoint3DComponent_GetAxis(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.PhysicsJoint3DComponent_SetAxis(Entity.ID, ref value);
		}

		public float MinDistance
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetMinDistance(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetMinDistance(Entity.ID, value);
		}

		public float MaxDistance
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetMaxDistance(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetMaxDistance(Entity.ID, value);
		}

		public float HingeMinAngleDeg
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMinAngleDeg(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMinAngleDeg(Entity.ID, value);
		}

		public float HingeMaxAngleDeg
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMaxAngleDeg(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMaxAngleDeg(Entity.ID, value);
		}

		public float SliderMinLimit
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMinLimit(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMinLimit(Entity.ID, value);
		}

		public float SliderMaxLimit
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMaxLimit(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMaxLimit(Entity.ID, value);
		}

		public float ConeHalfAngleDeg
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetConeHalfAngleDeg(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetConeHalfAngleDeg(Entity.ID, value);
		}

		public float BreakForce
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetBreakForce(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetBreakForce(Entity.ID, value);
		}

		public float BreakTorque
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetBreakTorque(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetBreakTorque(Entity.ID, value);
		}

		public int HingeMotorMode
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMotorMode(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMotorMode(Entity.ID, value);
		}

		public float HingeMotorTargetVelocityDeg
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMotorTargetVelocityDeg(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMotorTargetVelocityDeg(Entity.ID, value);
		}

		public float HingeMotorTargetAngleDeg
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMotorTargetAngleDeg(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMotorTargetAngleDeg(Entity.ID, value);
		}

		public float HingeMaxMotorTorque
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMaxMotorTorque(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMaxMotorTorque(Entity.ID, value);
		}

		public float HingeMaxFrictionTorque
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetHingeMaxFrictionTorque(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetHingeMaxFrictionTorque(Entity.ID, value);
		}

		public int SliderMotorMode
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMotorMode(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMotorMode(Entity.ID, value);
		}

		public float SliderMotorTargetVelocity
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMotorTargetVelocity(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMotorTargetVelocity(Entity.ID, value);
		}

		public float SliderMotorTargetPosition
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMotorTargetPosition(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMotorTargetPosition(Entity.ID, value);
		}

		public float SliderMaxMotorForce
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMaxMotorForce(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMaxMotorForce(Entity.ID, value);
		}

		public float SliderMaxFrictionForce
		{
			get => InternalCalls.PhysicsJoint3DComponent_GetSliderMaxFrictionForce(Entity.ID);
			set => InternalCalls.PhysicsJoint3DComponent_SetSliderMaxFrictionForce(Entity.ID, value);
		}
	}

	public partial class PointLightComponent : Component
	{
		public Vector3 Color
		{
			get
			{
				InternalCalls.PointLightComponent_GetColor(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.PointLightComponent_SetColor(Entity.ID, ref value);
		}

		public float Intensity
		{
			get => InternalCalls.PointLightComponent_GetIntensity(Entity.ID);
			set => InternalCalls.PointLightComponent_SetIntensity(Entity.ID, value);
		}

		public float Range
		{
			get => InternalCalls.PointLightComponent_GetRange(Entity.ID);
			set => InternalCalls.PointLightComponent_SetRange(Entity.ID, value);
		}

		public bool CastShadows
		{
			get => InternalCalls.PointLightComponent_GetCastShadows(Entity.ID);
			set => InternalCalls.PointLightComponent_SetCastShadows(Entity.ID, value);
		}
	}

	public partial class ProceduralSkyComponent : Component
	{
		public Vector3 SunDirection
		{
			get
			{
				InternalCalls.ProceduralSkyComponent_GetSunDirection(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.ProceduralSkyComponent_SetSunDirection(Entity.ID, ref value);
		}

		public float Turbidity
		{
			get => InternalCalls.ProceduralSkyComponent_GetTurbidity(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetTurbidity(Entity.ID, value);
		}

		public float Exposure
		{
			get => InternalCalls.ProceduralSkyComponent_GetExposure(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetExposure(Entity.ID, value);
		}

		public float SunIntensity
		{
			get => InternalCalls.ProceduralSkyComponent_GetSunIntensity(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetSunIntensity(Entity.ID, value);
		}

		public float SunDiskSize
		{
			get => InternalCalls.ProceduralSkyComponent_GetSunDiskSize(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetSunDiskSize(Entity.ID, value);
		}

		public bool ShowSunDisk
		{
			get => InternalCalls.ProceduralSkyComponent_GetShowSunDisk(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetShowSunDisk(Entity.ID, value);
		}

		public bool LinkSunToDirectionalLight
		{
			get => InternalCalls.ProceduralSkyComponent_GetLinkSunToDirectionalLight(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetLinkSunToDirectionalLight(Entity.ID, value);
		}

		public bool EnableSkybox
		{
			get => InternalCalls.ProceduralSkyComponent_GetEnableSkybox(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetEnableSkybox(Entity.ID, value);
		}

		public bool EnableIBL
		{
			get => InternalCalls.ProceduralSkyComponent_GetEnableIBL(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetEnableIBL(Entity.ID, value);
		}

		public float IBLIntensity
		{
			get => InternalCalls.ProceduralSkyComponent_GetIBLIntensity(Entity.ID);
			set => InternalCalls.ProceduralSkyComponent_SetIBLIntensity(Entity.ID, value);
		}
	}

	public partial class ReflectionProbeComponent : Component
	{
		public float InfluenceRadius
		{
			get => InternalCalls.ReflectionProbeComponent_GetInfluenceRadius(Entity.ID);
			set => InternalCalls.ReflectionProbeComponent_SetInfluenceRadius(Entity.ID, value);
		}

		public float BlendDistance
		{
			get => InternalCalls.ReflectionProbeComponent_GetBlendDistance(Entity.ID);
			set => InternalCalls.ReflectionProbeComponent_SetBlendDistance(Entity.ID, value);
		}

		public uint Resolution
		{
			get => InternalCalls.ReflectionProbeComponent_GetResolution(Entity.ID);
			set => InternalCalls.ReflectionProbeComponent_SetResolution(Entity.ID, value);
		}

		public float Intensity
		{
			get => InternalCalls.ReflectionProbeComponent_GetIntensity(Entity.ID);
			set => InternalCalls.ReflectionProbeComponent_SetIntensity(Entity.ID, value);
		}

		public bool Active
		{
			get => InternalCalls.ReflectionProbeComponent_GetActive(Entity.ID);
			set => InternalCalls.ReflectionProbeComponent_SetActive(Entity.ID, value);
		}
	}

	public partial class Rigidbody2DComponent : Component
	{
		public int Type
		{
			get => InternalCalls.Rigidbody2DComponent_GetType(Entity.ID);
			set => InternalCalls.Rigidbody2DComponent_SetType(Entity.ID, value);
		}

		public bool FixedRotation
		{
			get => InternalCalls.Rigidbody2DComponent_GetFixedRotation(Entity.ID);
			set => InternalCalls.Rigidbody2DComponent_SetFixedRotation(Entity.ID, value);
		}

		public Vector2 LinearVelocity
		{
			get
			{
				InternalCalls.Rigidbody2DComponent_GetLinearVelocity(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.Rigidbody2DComponent_SetLinearVelocity(Entity.ID, ref value);
		}

		public float AngularVelocity
		{
			get => InternalCalls.Rigidbody2DComponent_GetAngularVelocity(Entity.ID);
			set => InternalCalls.Rigidbody2DComponent_SetAngularVelocity(Entity.ID, value);
		}
	}

	public partial class Rigidbody3DComponent : Component
	{
		public int BodyType
		{
			get => InternalCalls.Rigidbody3DComponent_GetBodyType(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetBodyType(Entity.ID, value);
		}

		public float Mass
		{
			get => InternalCalls.Rigidbody3DComponent_GetMass(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetMass(Entity.ID, value);
		}

		public float LinearDrag
		{
			get => InternalCalls.Rigidbody3DComponent_GetLinearDrag(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetLinearDrag(Entity.ID, value);
		}

		public float AngularDrag
		{
			get => InternalCalls.Rigidbody3DComponent_GetAngularDrag(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetAngularDrag(Entity.ID, value);
		}

		public bool DisableGravity
		{
			get => InternalCalls.Rigidbody3DComponent_GetDisableGravity(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetDisableGravity(Entity.ID, value);
		}

		public bool IsTrigger
		{
			get => InternalCalls.Rigidbody3DComponent_GetIsTrigger(Entity.ID);
			set => InternalCalls.Rigidbody3DComponent_SetIsTrigger(Entity.ID, value);
		}
	}

	public partial class SphereAreaLightComponent : Component
	{
		public Vector3 Color
		{
			get
			{
				InternalCalls.SphereAreaLightComponent_GetColor(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.SphereAreaLightComponent_SetColor(Entity.ID, ref value);
		}

		public float Intensity
		{
			get => InternalCalls.SphereAreaLightComponent_GetIntensity(Entity.ID);
			set => InternalCalls.SphereAreaLightComponent_SetIntensity(Entity.ID, value);
		}

		public float Radius
		{
			get => InternalCalls.SphereAreaLightComponent_GetRadius(Entity.ID);
			set => InternalCalls.SphereAreaLightComponent_SetRadius(Entity.ID, value);
		}

		public float Range
		{
			get => InternalCalls.SphereAreaLightComponent_GetRange(Entity.ID);
			set => InternalCalls.SphereAreaLightComponent_SetRange(Entity.ID, value);
		}

		public bool CastShadows
		{
			get => InternalCalls.SphereAreaLightComponent_GetCastShadows(Entity.ID);
			set => InternalCalls.SphereAreaLightComponent_SetCastShadows(Entity.ID, value);
		}
	}

	public partial class SphereCollider3DComponent : Component
	{
		public float Radius
		{
			get => InternalCalls.SphereCollider3DComponent_GetRadius(Entity.ID);
			set => InternalCalls.SphereCollider3DComponent_SetRadius(Entity.ID, value);
		}

		public Vector3 Offset
		{
			get
			{
				InternalCalls.SphereCollider3DComponent_GetOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.SphereCollider3DComponent_SetOffset(Entity.ID, ref value);
		}
	}

	public partial class SpotLightComponent : Component
	{
		public Vector3 Color
		{
			get
			{
				InternalCalls.SpotLightComponent_GetColor(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.SpotLightComponent_SetColor(Entity.ID, ref value);
		}

		public float Intensity
		{
			get => InternalCalls.SpotLightComponent_GetIntensity(Entity.ID);
			set => InternalCalls.SpotLightComponent_SetIntensity(Entity.ID, value);
		}

		public float Range
		{
			get => InternalCalls.SpotLightComponent_GetRange(Entity.ID);
			set => InternalCalls.SpotLightComponent_SetRange(Entity.ID, value);
		}

		public float InnerCutoff
		{
			get => InternalCalls.SpotLightComponent_GetInnerCutoff(Entity.ID);
			set => InternalCalls.SpotLightComponent_SetInnerCutoff(Entity.ID, value);
		}

		public float OuterCutoff
		{
			get => InternalCalls.SpotLightComponent_GetOuterCutoff(Entity.ID);
			set => InternalCalls.SpotLightComponent_SetOuterCutoff(Entity.ID, value);
		}

		public bool CastShadows
		{
			get => InternalCalls.SpotLightComponent_GetCastShadows(Entity.ID);
			set => InternalCalls.SpotLightComponent_SetCastShadows(Entity.ID, value);
		}
	}

	public partial class SpriteRendererComponent : Component
	{
		public Vector4 Color
		{
			get
			{
				InternalCalls.SpriteRendererComponent_GetColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.SpriteRendererComponent_SetColor(Entity.ID, ref value);
		}

		public float TilingFactor
		{
			get => InternalCalls.SpriteRendererComponent_GetTilingFactor(Entity.ID);
			set => InternalCalls.SpriteRendererComponent_SetTilingFactor(Entity.ID, value);
		}
	}

	public partial class StarNestSkyComponent : Component
	{
		public Vector3 Offset
		{
			get
			{
				InternalCalls.StarNestSkyComponent_GetOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.StarNestSkyComponent_SetOffset(Entity.ID, ref value);
		}

		public float Rotation1
		{
			get => InternalCalls.StarNestSkyComponent_GetRotation1(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetRotation1(Entity.ID, value);
		}

		public float Rotation2
		{
			get => InternalCalls.StarNestSkyComponent_GetRotation2(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetRotation2(Entity.ID, value);
		}

		public float Formuparam
		{
			get => InternalCalls.StarNestSkyComponent_GetFormuparam(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetFormuparam(Entity.ID, value);
		}

		public float StepSize
		{
			get => InternalCalls.StarNestSkyComponent_GetStepSize(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetStepSize(Entity.ID, value);
		}

		public float Tile
		{
			get => InternalCalls.StarNestSkyComponent_GetTile(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetTile(Entity.ID, value);
		}

		public float Brightness
		{
			get => InternalCalls.StarNestSkyComponent_GetBrightness(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetBrightness(Entity.ID, value);
		}

		public float DarkMatter
		{
			get => InternalCalls.StarNestSkyComponent_GetDarkMatter(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetDarkMatter(Entity.ID, value);
		}

		public float DistFading
		{
			get => InternalCalls.StarNestSkyComponent_GetDistFading(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetDistFading(Entity.ID, value);
		}

		public float Saturation
		{
			get => InternalCalls.StarNestSkyComponent_GetSaturation(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetSaturation(Entity.ID, value);
		}

		public float Intensity
		{
			get => InternalCalls.StarNestSkyComponent_GetIntensity(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetIntensity(Entity.ID, value);
		}

		public int Iterations
		{
			get => InternalCalls.StarNestSkyComponent_GetIterations(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetIterations(Entity.ID, value);
		}

		public int VolSteps
		{
			get => InternalCalls.StarNestSkyComponent_GetVolSteps(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetVolSteps(Entity.ID, value);
		}

		public bool EnableSkybox
		{
			get => InternalCalls.StarNestSkyComponent_GetEnableSkybox(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetEnableSkybox(Entity.ID, value);
		}

		public bool EnableIBL
		{
			get => InternalCalls.StarNestSkyComponent_GetEnableIBL(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetEnableIBL(Entity.ID, value);
		}

		public float IBLIntensity
		{
			get => InternalCalls.StarNestSkyComponent_GetIBLIntensity(Entity.ID);
			set => InternalCalls.StarNestSkyComponent_SetIBLIntensity(Entity.ID, value);
		}
	}

	public partial class StreamingVolumeComponent : Component
	{
		public float LoadRadius
		{
			get => InternalCalls.StreamingVolumeComponent_GetLoadRadius(Entity.ID);
			set => InternalCalls.StreamingVolumeComponent_SetLoadRadius(Entity.ID, value);
		}

		public float UnloadRadius
		{
			get => InternalCalls.StreamingVolumeComponent_GetUnloadRadius(Entity.ID);
			set => InternalCalls.StreamingVolumeComponent_SetUnloadRadius(Entity.ID, value);
		}
	}

	public partial class TerrainComponent : Component
	{
		public float WorldSizeX
		{
			get => InternalCalls.TerrainComponent_GetWorldSizeX(Entity.ID);
			set => InternalCalls.TerrainComponent_SetWorldSizeX(Entity.ID, value);
		}

		public float WorldSizeZ
		{
			get => InternalCalls.TerrainComponent_GetWorldSizeZ(Entity.ID);
			set => InternalCalls.TerrainComponent_SetWorldSizeZ(Entity.ID, value);
		}

		public float HeightScale
		{
			get => InternalCalls.TerrainComponent_GetHeightScale(Entity.ID);
			set => InternalCalls.TerrainComponent_SetHeightScale(Entity.ID, value);
		}

		public bool ProceduralEnabled
		{
			get => InternalCalls.TerrainComponent_GetProceduralEnabled(Entity.ID);
			set => InternalCalls.TerrainComponent_SetProceduralEnabled(Entity.ID, value);
		}

		public int Seed
		{
			get => InternalCalls.TerrainComponent_GetSeed(Entity.ID);
			set => InternalCalls.TerrainComponent_SetSeed(Entity.ID, value);
		}

		public uint Resolution
		{
			get => InternalCalls.TerrainComponent_GetResolution(Entity.ID);
			set => InternalCalls.TerrainComponent_SetResolution(Entity.ID, value);
		}

		public uint Octaves
		{
			get => InternalCalls.TerrainComponent_GetOctaves(Entity.ID);
			set => InternalCalls.TerrainComponent_SetOctaves(Entity.ID, value);
		}

		public float Frequency
		{
			get => InternalCalls.TerrainComponent_GetFrequency(Entity.ID);
			set => InternalCalls.TerrainComponent_SetFrequency(Entity.ID, value);
		}

		public float Lacunarity
		{
			get => InternalCalls.TerrainComponent_GetLacunarity(Entity.ID);
			set => InternalCalls.TerrainComponent_SetLacunarity(Entity.ID, value);
		}

		public float Persistence
		{
			get => InternalCalls.TerrainComponent_GetPersistence(Entity.ID);
			set => InternalCalls.TerrainComponent_SetPersistence(Entity.ID, value);
		}

		public float RidgeBlend
		{
			get => InternalCalls.TerrainComponent_GetRidgeBlend(Entity.ID);
			set => InternalCalls.TerrainComponent_SetRidgeBlend(Entity.ID, value);
		}

		public float WarpStrength
		{
			get => InternalCalls.TerrainComponent_GetWarpStrength(Entity.ID);
			set => InternalCalls.TerrainComponent_SetWarpStrength(Entity.ID, value);
		}

		public float WarpFrequency
		{
			get => InternalCalls.TerrainComponent_GetWarpFrequency(Entity.ID);
			set => InternalCalls.TerrainComponent_SetWarpFrequency(Entity.ID, value);
		}

		public uint TerraceSteps
		{
			get => InternalCalls.TerrainComponent_GetTerraceSteps(Entity.ID);
			set => InternalCalls.TerrainComponent_SetTerraceSteps(Entity.ID, value);
		}

		public float TerraceSharpness
		{
			get => InternalCalls.TerrainComponent_GetTerraceSharpness(Entity.ID);
			set => InternalCalls.TerrainComponent_SetTerraceSharpness(Entity.ID, value);
		}

		public float HeightExponent
		{
			get => InternalCalls.TerrainComponent_GetHeightExponent(Entity.ID);
			set => InternalCalls.TerrainComponent_SetHeightExponent(Entity.ID, value);
		}

		public bool AutoMaterial
		{
			get => InternalCalls.TerrainComponent_GetAutoMaterial(Entity.ID);
			set => InternalCalls.TerrainComponent_SetAutoMaterial(Entity.ID, value);
		}

		public uint SplatmapGenResolution
		{
			get => InternalCalls.TerrainComponent_GetSplatmapGenResolution(Entity.ID);
			set => InternalCalls.TerrainComponent_SetSplatmapGenResolution(Entity.ID, value);
		}
	}

	public partial class TextComponent : Component
	{
		public string Text
		{
			get => InternalCalls.TextComponent_GetText(Entity.ID);
			set => InternalCalls.TextComponent_SetText(Entity.ID, value);
		}

		public Vector4 Color
		{
			get
			{
				InternalCalls.TextComponent_GetColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.TextComponent_SetColor(Entity.ID, ref value);
		}

		public float Kerning
		{
			get => InternalCalls.TextComponent_GetKerning(Entity.ID);
			set => InternalCalls.TextComponent_SetKerning(Entity.ID, value);
		}

		public float LineSpacing
		{
			get => InternalCalls.TextComponent_GetLineSpacing(Entity.ID);
			set => InternalCalls.TextComponent_SetLineSpacing(Entity.ID, value);
		}
	}

	public partial class TransformComponent : Component
	{
		public Vector3 Translation
		{
			get
			{
				InternalCalls.TransformComponent_GetTranslation(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.TransformComponent_SetTranslation(Entity.ID, ref value);
		}

		public Vector3 Scale
		{
			get
			{
				InternalCalls.TransformComponent_GetScale(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.TransformComponent_SetScale(Entity.ID, ref value);
		}

		public Vector3 Rotation
		{
			get
			{
				InternalCalls.TransformComponent_GetRotation(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.TransformComponent_SetRotation(Entity.ID, ref value);
		}
	}

	public partial class UIButtonComponent : Component
	{
		public Vector4 NormalColor
		{
			get
			{
				InternalCalls.UIButtonComponent_GetNormalColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIButtonComponent_SetNormalColor(Entity.ID, ref value);
		}

		public Vector4 HoveredColor
		{
			get
			{
				InternalCalls.UIButtonComponent_GetHoveredColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIButtonComponent_SetHoveredColor(Entity.ID, ref value);
		}

		public Vector4 PressedColor
		{
			get
			{
				InternalCalls.UIButtonComponent_GetPressedColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIButtonComponent_SetPressedColor(Entity.ID, ref value);
		}

		public Vector4 DisabledColor
		{
			get
			{
				InternalCalls.UIButtonComponent_GetDisabledColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIButtonComponent_SetDisabledColor(Entity.ID, ref value);
		}

		public bool Interactable
		{
			get => InternalCalls.UIButtonComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UIButtonComponent_SetInteractable(Entity.ID, value);
		}

		public int State
		{
			get => InternalCalls.UIButtonComponent_GetState(Entity.ID);
			set => InternalCalls.UIButtonComponent_SetState(Entity.ID, value);
		}
	}

	public partial class UICanvasComponent : Component
	{
		public int SortOrder
		{
			get => InternalCalls.UICanvasComponent_GetSortOrder(Entity.ID);
			set => InternalCalls.UICanvasComponent_SetSortOrder(Entity.ID, value);
		}
	}

	public partial class UICheckboxComponent : Component
	{
		public bool IsChecked
		{
			get => InternalCalls.UICheckboxComponent_GetIsChecked(Entity.ID);
			set => InternalCalls.UICheckboxComponent_SetIsChecked(Entity.ID, value);
		}

		public bool Interactable
		{
			get => InternalCalls.UICheckboxComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UICheckboxComponent_SetInteractable(Entity.ID, value);
		}
	}

	public partial class UIDropdownComponent : Component
	{
		public int SelectedIndex
		{
			get => InternalCalls.UIDropdownComponent_GetSelectedIndex(Entity.ID);
			set => InternalCalls.UIDropdownComponent_SetSelectedIndex(Entity.ID, value);
		}

		public bool Interactable
		{
			get => InternalCalls.UIDropdownComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UIDropdownComponent_SetInteractable(Entity.ID, value);
		}
	}

	public partial class UIGridLayoutComponent : Component
	{
		public Vector2 CellSize
		{
			get
			{
				InternalCalls.UIGridLayoutComponent_GetCellSize(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIGridLayoutComponent_SetCellSize(Entity.ID, ref value);
		}

		public Vector2 Spacing
		{
			get
			{
				InternalCalls.UIGridLayoutComponent_GetSpacing(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIGridLayoutComponent_SetSpacing(Entity.ID, ref value);
		}

		public int ConstraintCount
		{
			get => InternalCalls.UIGridLayoutComponent_GetConstraintCount(Entity.ID);
			set => InternalCalls.UIGridLayoutComponent_SetConstraintCount(Entity.ID, value);
		}
	}

	public partial class UIImageComponent : Component
	{
		public Vector4 Color
		{
			get
			{
				InternalCalls.UIImageComponent_GetColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIImageComponent_SetColor(Entity.ID, ref value);
		}
	}

	public partial class UIInputFieldComponent : Component
	{
		public string Text
		{
			get => InternalCalls.UIInputFieldComponent_GetText(Entity.ID);
			set => InternalCalls.UIInputFieldComponent_SetText(Entity.ID, value);
		}

		public string Placeholder
		{
			get => InternalCalls.UIInputFieldComponent_GetPlaceholder(Entity.ID);
			set => InternalCalls.UIInputFieldComponent_SetPlaceholder(Entity.ID, value);
		}

		public float FontSize
		{
			get => InternalCalls.UIInputFieldComponent_GetFontSize(Entity.ID);
			set => InternalCalls.UIInputFieldComponent_SetFontSize(Entity.ID, value);
		}

		public Vector4 TextColor
		{
			get
			{
				InternalCalls.UIInputFieldComponent_GetTextColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIInputFieldComponent_SetTextColor(Entity.ID, ref value);
		}

		public bool Interactable
		{
			get => InternalCalls.UIInputFieldComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UIInputFieldComponent_SetInteractable(Entity.ID, value);
		}
	}

	public partial class UIPanelComponent : Component
	{
		public Vector4 BackgroundColor
		{
			get
			{
				InternalCalls.UIPanelComponent_GetBackgroundColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UIPanelComponent_SetBackgroundColor(Entity.ID, ref value);
		}
	}

	public partial class UIProgressBarComponent : Component
	{
		public float Value
		{
			get => InternalCalls.UIProgressBarComponent_GetValue(Entity.ID);
			set => InternalCalls.UIProgressBarComponent_SetValue(Entity.ID, value);
		}

		public float MinValue
		{
			get => InternalCalls.UIProgressBarComponent_GetMinValue(Entity.ID);
			set => InternalCalls.UIProgressBarComponent_SetMinValue(Entity.ID, value);
		}

		public float MaxValue
		{
			get => InternalCalls.UIProgressBarComponent_GetMaxValue(Entity.ID);
			set => InternalCalls.UIProgressBarComponent_SetMaxValue(Entity.ID, value);
		}
	}

	public partial class UIRectTransformComponent : Component
	{
		public Vector2 AnchorMin
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetAnchorMin(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetAnchorMin(Entity.ID, ref value);
		}

		public Vector2 AnchorMax
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetAnchorMax(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetAnchorMax(Entity.ID, ref value);
		}

		public Vector2 AnchoredPosition
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetAnchoredPosition(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetAnchoredPosition(Entity.ID, ref value);
		}

		public Vector2 SizeDelta
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetSizeDelta(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetSizeDelta(Entity.ID, ref value);
		}

		public Vector2 Pivot
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetPivot(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetPivot(Entity.ID, ref value);
		}

		public float Rotation
		{
			get => InternalCalls.UIRectTransformComponent_GetRotation(Entity.ID);
			set => InternalCalls.UIRectTransformComponent_SetRotation(Entity.ID, value);
		}

		public Vector2 Scale
		{
			get
			{
				InternalCalls.UIRectTransformComponent_GetScale(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIRectTransformComponent_SetScale(Entity.ID, ref value);
		}
	}

	public partial class UIScrollViewComponent : Component
	{
		public Vector2 ScrollPosition
		{
			get
			{
				InternalCalls.UIScrollViewComponent_GetScrollPosition(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIScrollViewComponent_SetScrollPosition(Entity.ID, ref value);
		}

		public Vector2 ContentSize
		{
			get
			{
				InternalCalls.UIScrollViewComponent_GetContentSize(Entity.ID, out Vector2 value);
				return value;
			}
			set => InternalCalls.UIScrollViewComponent_SetContentSize(Entity.ID, ref value);
		}

		public float ScrollSpeed
		{
			get => InternalCalls.UIScrollViewComponent_GetScrollSpeed(Entity.ID);
			set => InternalCalls.UIScrollViewComponent_SetScrollSpeed(Entity.ID, value);
		}
	}

	public partial class UISliderComponent : Component
	{
		public float Value
		{
			get => InternalCalls.UISliderComponent_GetValue(Entity.ID);
			set => InternalCalls.UISliderComponent_SetValue(Entity.ID, value);
		}

		public float MinValue
		{
			get => InternalCalls.UISliderComponent_GetMinValue(Entity.ID);
			set => InternalCalls.UISliderComponent_SetMinValue(Entity.ID, value);
		}

		public float MaxValue
		{
			get => InternalCalls.UISliderComponent_GetMaxValue(Entity.ID);
			set => InternalCalls.UISliderComponent_SetMaxValue(Entity.ID, value);
		}

		public bool Interactable
		{
			get => InternalCalls.UISliderComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UISliderComponent_SetInteractable(Entity.ID, value);
		}
	}

	public partial class UITextComponent : Component
	{
		public string Text
		{
			get => InternalCalls.UITextComponent_GetText(Entity.ID);
			set => InternalCalls.UITextComponent_SetText(Entity.ID, value);
		}

		public float FontSize
		{
			get => InternalCalls.UITextComponent_GetFontSize(Entity.ID);
			set => InternalCalls.UITextComponent_SetFontSize(Entity.ID, value);
		}

		public Vector4 Color
		{
			get
			{
				InternalCalls.UITextComponent_GetColor(Entity.ID, out Vector4 value);
				return value;
			}
			set => InternalCalls.UITextComponent_SetColor(Entity.ID, ref value);
		}

		public float Kerning
		{
			get => InternalCalls.UITextComponent_GetKerning(Entity.ID);
			set => InternalCalls.UITextComponent_SetKerning(Entity.ID, value);
		}

		public float LineSpacing
		{
			get => InternalCalls.UITextComponent_GetLineSpacing(Entity.ID);
			set => InternalCalls.UITextComponent_SetLineSpacing(Entity.ID, value);
		}
	}

	public partial class UIToggleComponent : Component
	{
		public bool IsOn
		{
			get => InternalCalls.UIToggleComponent_GetIsOn(Entity.ID);
			set => InternalCalls.UIToggleComponent_SetIsOn(Entity.ID, value);
		}

		public bool Interactable
		{
			get => InternalCalls.UIToggleComponent_GetInteractable(Entity.ID);
			set => InternalCalls.UIToggleComponent_SetInteractable(Entity.ID, value);
		}
	}

	public partial class UIWorldAnchorComponent : Component
	{
		public Vector3 WorldOffset
		{
			get
			{
				InternalCalls.UIWorldAnchorComponent_GetWorldOffset(Entity.ID, out Vector3 value);
				return value;
			}
			set => InternalCalls.UIWorldAnchorComponent_SetWorldOffset(Entity.ID, ref value);
		}
	}

	public partial class VideoOverlayComponent : Component
	{
		public bool PlayOnStart
		{
			get => InternalCalls.VideoOverlayComponent_GetPlayOnStart(Entity.ID);
			set => InternalCalls.VideoOverlayComponent_SetPlayOnStart(Entity.ID, value);
		}

		public bool SkipOnInput
		{
			get => InternalCalls.VideoOverlayComponent_GetSkipOnInput(Entity.ID);
			set => InternalCalls.VideoOverlayComponent_SetSkipOnInput(Entity.ID, value);
		}

		public bool Looping
		{
			get => InternalCalls.VideoOverlayComponent_GetLooping(Entity.ID);
			set => InternalCalls.VideoOverlayComponent_SetLooping(Entity.ID, value);
		}

		public float Volume
		{
			get => InternalCalls.VideoOverlayComponent_GetVolume(Entity.ID);
			set => InternalCalls.VideoOverlayComponent_SetVolume(Entity.ID, value);
		}

		public string VideoPath
		{
			get => InternalCalls.VideoOverlayComponent_GetVideoPath(Entity.ID);
			set => InternalCalls.VideoOverlayComponent_SetVideoPath(Entity.ID, value);
		}
	}

	public partial class VideoSurfaceComponent : Component
	{
		public bool AutoPlay
		{
			get => InternalCalls.VideoSurfaceComponent_GetAutoPlay(Entity.ID);
			set => InternalCalls.VideoSurfaceComponent_SetAutoPlay(Entity.ID, value);
		}

		public bool Looping
		{
			get => InternalCalls.VideoSurfaceComponent_GetLooping(Entity.ID);
			set => InternalCalls.VideoSurfaceComponent_SetLooping(Entity.ID, value);
		}

		public float Volume
		{
			get => InternalCalls.VideoSurfaceComponent_GetVolume(Entity.ID);
			set => InternalCalls.VideoSurfaceComponent_SetVolume(Entity.ID, value);
		}

		public string VideoPath
		{
			get => InternalCalls.VideoSurfaceComponent_GetVideoPath(Entity.ID);
			set => InternalCalls.VideoSurfaceComponent_SetVideoPath(Entity.ID, value);
		}
	}

}
