// OLO_TEST_LAYER: L1
// =============================================================================
// GaussianSplatPipelineTest.cpp — CPU contracts for the Gaussian-splat spike
// (issue #971).
//
// Everything a splat cloud can get quietly WRONG lives on the CPU: the trainer
// stores opacity as a logit, scale as a logarithm, colour as an SH coefficient
// and rotation as a quaternion in (w, x, y, z) order, and every one of those is
// a decode where a plausible-looking cloud comes out of a wrong constant. A
// screenshot cannot tell a correctly decoded cloud from one whose quaternion
// components are rotated by one -- both look like a cloud of blobs. So the
// decode, the packing, the ordering and the LOD are pinned here, on the CPU,
// where a wrong answer is a failed assertion.
//
// The fixture is OloEditor/assets/tests/splat/fixture_discs.ply, generated by
// tools/splat/make_splat_fixture.py in the real INRIA property layout. The
// tests that check decoded VALUES check them against the generator's own inputs
// (0.90 opacity, 0.055 disc sigma, the three disc colours), which is what makes
// them a round-trip rather than a restatement of the implementation.
//
// No GPU: this file runs everywhere, including headless CI.
// =============================================================================

#include "OloEnginePCH.h"

#include <gtest/gtest.h>

#include "OloEngine/Renderer/Splat/GaussianSplatCloud.h"
#include "OloEngine/Renderer/Splat/GaussianSplatView.h"

#include <glm/gtc/constants.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <limits>
#include <numeric>
#include <random>
#include <string>
#include <utility>
#include <vector>

namespace OloEngine::Tests
{
    namespace fs = std::filesystem;
    using namespace OloEngine::GaussianSplat;

    namespace
    {
        // The suite runs from the repo root for most tests and from OloEditor/
        // for the GPU ones, so the fixture is looked up along both, plus a walk
        // up from the working directory for an out-of-tree runner.
        [[nodiscard]] fs::path FixturePath()
        {
            static constexpr const char* kRelative = "assets/tests/splat/fixture_discs.ply";
            const std::array<fs::path, 2> candidates{ fs::path("OloEditor") / kRelative, fs::path(kRelative) };
            for (const fs::path& candidate : candidates)
            {
                if (fs::exists(candidate))
                    return candidate;
            }
            fs::path dir = fs::current_path();
            for (int i = 0; i < 6 && !dir.empty(); ++i)
            {
                if (const fs::path candidate = dir / "OloEditor" / kRelative; fs::exists(candidate))
                    return candidate;
                dir = dir.parent_path();
            }
            return {};
        }

        // Minimal well-formed PLY for the negative cases, built property by
        // property so a test can remove exactly one thing and assert on that.
        //
        // `Types` is empty for the usual all-float case. When it is set it must
        // be parallel to `Properties`, and Build() both declares and ENCODES
        // each column in its declared type -- which is what lets a test prove
        // the reader decodes an integer column rather than memcpy-ing four
        // bytes out of it and calling the result a float.
        struct PlyBuilder
        {
            std::string Format = "binary_little_endian";
            std::vector<std::string> Properties;
            std::vector<std::string> Types;
            std::vector<std::vector<f32>> Rows;

            static PlyBuilder Minimal()
            {
                PlyBuilder builder;
                builder.Properties = { "x", "y", "z", "f_dc_0", "f_dc_1", "f_dc_2",
                                       "opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1",
                                       "rot_2", "rot_3" };
                builder.Rows.push_back({ 1.0f, 2.0f, 3.0f, 0.0f, 0.0f, 0.0f, 0.0f, -3.0f, -3.0f, -3.0f, 1.0f, 0.0f,
                                         0.0f, 0.0f });
                return builder;
            }

            [[nodiscard]] std::string TypeOf(sizet column) const
            {
                return Types.empty() ? std::string("float") : Types[column];
            }

            static void AppendTyped(std::vector<u8>& out, const std::string& type, f32 value)
            {
                const auto push = [&out](const void* data, sizet size)
                {
                    const auto* raw = static_cast<const u8*>(data);
                    out.insert(out.end(), raw, raw + size);
                };
                if (type == "double")
                {
                    const f64 v = value;
                    push(&v, sizeof(v));
                }
                else if (type == "int" || type == "int32")
                {
                    const i32 v = static_cast<i32>(value);
                    push(&v, sizeof(v));
                }
                else if (type == "uint" || type == "uint32")
                {
                    const u32 v = static_cast<u32>(value);
                    push(&v, sizeof(v));
                }
                else if (type == "short" || type == "int16")
                {
                    const i16 v = static_cast<i16>(value);
                    push(&v, sizeof(v));
                }
                else if (type == "ushort" || type == "uint16")
                {
                    const u16 v = static_cast<u16>(value);
                    push(&v, sizeof(v));
                }
                else if (type == "uchar" || type == "uint8")
                {
                    const u8 v = static_cast<u8>(value);
                    push(&v, sizeof(v));
                }
                else if (type == "char" || type == "int8")
                {
                    const i8 v = static_cast<i8>(value);
                    push(&v, sizeof(v));
                }
                else
                {
                    push(&value, sizeof(value));
                }
            }

            [[nodiscard]] std::vector<u8> Build() const
            {
                std::string header = "ply\nformat " + Format + " 1.0\nelement vertex " +
                                     std::to_string(Rows.size()) + "\n";
                for (sizet i = 0; i < Properties.size(); ++i)
                    header += "property " + TypeOf(i) + " " + Properties[i] + "\n";
                header += "end_header\n";

                std::vector<u8> bytes(header.begin(), header.end());
                if (Format == "ascii")
                {
                    std::string body;
                    for (const std::vector<f32>& row : Rows)
                    {
                        for (sizet i = 0; i < row.size(); ++i)
                            body += (i ? " " : "") + std::to_string(row[i]);
                        body += "\n";
                    }
                    bytes.insert(bytes.end(), body.begin(), body.end());
                }
                else
                {
                    for (const std::vector<f32>& row : Rows)
                    {
                        for (sizet i = 0; i < row.size(); ++i)
                            AppendTyped(bytes, TypeOf(i), row[i]);
                    }
                }
                return bytes;
            }
        };

        [[nodiscard]] f32 Logit(f32 p)
        {
            return std::log(p / (1.0f - p));
        }
    } // namespace

    // -------------------------------------------------------------------------
    // Decode contracts. Each expected value comes from the definition in the
    // 3DGS paper / reference implementation, not from running this code.
    // -------------------------------------------------------------------------

    TEST(GaussianSplatDecode, OpacityIsTheLogisticOfTheStoredLogit)
    {
        EXPECT_NEAR(SigmoidOpacity(0.0f), 0.5f, 1e-6f);
        EXPECT_NEAR(SigmoidOpacity(Logit(0.90f)), 0.90f, 1e-5f);
        EXPECT_NEAR(SigmoidOpacity(Logit(0.30f)), 0.30f, 1e-5f);

        // Saturation, not inf/NaN: the property is external data.
        EXPECT_TRUE(std::isfinite(SigmoidOpacity(1e30f)));
        EXPECT_TRUE(std::isfinite(SigmoidOpacity(-1e30f)));
        EXPECT_NEAR(SigmoidOpacity(1e30f), 1.0f, 1e-6f);
        EXPECT_NEAR(SigmoidOpacity(-1e30f), 0.0f, 1e-6f);
    }

    TEST(GaussianSplatDecode, ShBandZeroReproducesTheAuthoredColour)
    {
        // colour = 0.5 + C0 * f_dc, so f_dc = (colour - 0.5) / C0 must return
        // the colour. C0 = 0.5 * sqrt(1/pi) is the band-0 SH basis value.
        EXPECT_NEAR(kShC0, 0.5f * std::sqrt(1.0f / glm::pi<f32>()), 1e-7f);

        const glm::vec3 authored(0.90f, 0.20f, 0.18f);
        const glm::vec3 dc = (authored - 0.5f) / kShC0;
        const glm::vec3 decoded = ShDcToColor(dc);
        EXPECT_NEAR(decoded.r, authored.r, 1e-5f);
        EXPECT_NEAR(decoded.g, authored.g, 1e-5f);
        EXPECT_NEAR(decoded.b, authored.b, 1e-5f);
    }

    TEST(GaussianSplatDecode, IdentityRotationGivesADiagonalCovariance)
    {
        const glm::vec3 sigmas(0.2f, 0.05f, 0.01f);
        const std::array<f32, 6> cov =
            CovarianceFromScaleRotation(glm::log(sigmas), glm::vec4(1.0f, 0.0f, 0.0f, 0.0f));

        EXPECT_NEAR(cov[0], sigmas.x * sigmas.x, 1e-6f); // xx
        EXPECT_NEAR(cov[3], sigmas.y * sigmas.y, 1e-8f); // yy
        EXPECT_NEAR(cov[5], sigmas.z * sigmas.z, 1e-9f); // zz
        EXPECT_NEAR(cov[1], 0.0f, 1e-9f);                // xy
        EXPECT_NEAR(cov[2], 0.0f, 1e-9f);                // xz
        EXPECT_NEAR(cov[4], 0.0f, 1e-9f);                // yz
    }

    TEST(GaussianSplatDecode, QuaternionIsReadAsWXYZ)
    {
        // A 90-degree rotation about Z carries the x axis onto y, so the
        // largest variance must move from xx to yy. Reading the quaternion as
        // (x, y, z, w) instead leaves it in xx -- which is exactly the bug this
        // pins, and which no screenshot would reveal.
        const glm::vec3 sigmas(0.2f, 0.01f, 0.01f);
        const f32 halfAngle = glm::quarter_pi<f32>();
        const glm::vec4 quatWXYZ(std::cos(halfAngle), 0.0f, 0.0f, std::sin(halfAngle));

        const std::array<f32, 6> cov = CovarianceFromScaleRotation(glm::log(sigmas), quatWXYZ);
        EXPECT_NEAR(cov[3], sigmas.x * sigmas.x, 1e-5f); // yy now holds the long axis
        EXPECT_NEAR(cov[0], sigmas.y * sigmas.y, 1e-5f);
        EXPECT_NEAR(cov[5], sigmas.z * sigmas.z, 1e-8f);
    }

    TEST(GaussianSplatDecode, AnUnnormalisedOrDegenerateQuaternionStaysFinite)
    {
        const glm::vec3 logScale = glm::log(glm::vec3(0.1f));

        // Trainers do not normalise on write.
        const std::array<f32, 6> scaled = CovarianceFromScaleRotation(logScale, glm::vec4(7.0f, 0.0f, 0.0f, 0.0f));
        EXPECT_NEAR(scaled[0], 0.01f, 1e-6f);

        // All-zero is not a rotation; identity is the only safe reading.
        const std::array<f32, 6> zero = CovarianceFromScaleRotation(logScale, glm::vec4(0.0f));
        for (f32 term : zero)
            EXPECT_TRUE(std::isfinite(term));
        EXPECT_NEAR(zero[0], 0.01f, 1e-6f);

        // A huge log-scale must clamp rather than produce inf.
        const std::array<f32, 6> huge =
            CovarianceFromScaleRotation(glm::vec3(1000.0f), glm::vec4(1.0f, 0.0f, 0.0f, 0.0f));
        for (f32 term : huge)
            EXPECT_TRUE(std::isfinite(term));
    }

    // -------------------------------------------------------------------------
    // Packing. The GPU record is 32 bytes, so both the colour and the covariance
    // are lossy; what matters is that the loss is bounded and stated.
    // -------------------------------------------------------------------------

    TEST(GaussianSplatPacking, ColourAndOpacitySurviveWithinOneQuantisationStep)
    {
        // One 8-bit step, not half a step: round-to-nearest lands exactly on
        // the half-step boundary for any value that is an odd multiple of
        // 1/510 (0.5 is the first), so a half-step bound is not attainable.
        constexpr f32 kStep = 1.0f / 255.0f;
        for (f32 v = 0.0f; v <= 1.0f; v += 1.0f / 32.0f)
        {
            const glm::vec4 back = UnpackColorOpacity(PackColorOpacity(glm::vec3(v, 1.0f - v, 0.25f), v));
            EXPECT_NEAR(back.r, v, kStep);
            EXPECT_NEAR(back.g, 1.0f - v, kStep);
            EXPECT_NEAR(back.a, v, kStep);
        }
    }

    TEST(GaussianSplatPacking, HalfCovarianceDegradesPredictablyForSmallSplats)
    {
        // The record stores the six covariance terms as HALVES, and a
        // covariance term is a squared length. Half's smallest normal is
        // 6.1e-5, so every splat whose sigma is below about 7.8 mm has its
        // covariance stored as a DENORMAL, where the spacing is a flat
        // 5.96e-8 and precision stops scaling with the value.
        //
        // That is survivable and it is not free, so the size of the effect is
        // measured here rather than asserted in prose. Error is reported on
        // SIGMA (a length, which is what a viewer sees as a splat's size), not
        // on the covariance term, so it is half the relative error of the
        // stored quantity.
        struct Case
        {
            f32 Sigma;
            f32 ToleranceOnSigma;
        };
        // 10 m down to 1 mm: the range a metre-scale scan actually occupies.
        // 0.25 mm is included to pin where the packing gives up.
        for (const Case testCase : { Case{ 10.0f, 0.005f }, Case{ 1.0f, 0.005f }, Case{ 0.1f, 0.005f },
                                     Case{ 0.01f, 0.005f }, Case{ 0.001f, 0.02f }, Case{ 0.00025f, 0.25f } })
        {
            const std::array<f32, 6> cov = CovarianceFromScaleRotation(glm::log(glm::vec3(testCase.Sigma)),
                                                                       glm::vec4(1.0f, 0.0f, 0.0f, 0.0f));
            u32 a = 0;
            u32 b = 0;
            u32 c = 0;
            PackCovariance(cov, a, b, c);
            const std::array<f32, 6> back = UnpackCovariance(a, b, c);

            ASSERT_TRUE(std::isfinite(back[0])) << "sigma = " << testCase.Sigma;
            ASSERT_TRUE(std::isfinite(ConservativeSigma(GpuSplat{ glm::vec3(0.0f), 0u, a, b, c, 0u })))
                << "sigma = " << testCase.Sigma;
            ASSERT_GT(back[0], 0.0f) << "sigma = " << testCase.Sigma << " underflowed to zero";
            const f32 recovered = std::sqrt(back[0]);
            const f32 relative = std::abs(recovered - testCase.Sigma) / testCase.Sigma;
            EXPECT_LE(relative, testCase.ToleranceOnSigma)
                << "sigma = " << testCase.Sigma << " came back as " << recovered;
        }
    }

    TEST(GaussianSplatPacking, AnAbsurdlyLargeSplatClampsInsteadOfBecomingInfinite)
    {
        // sqrt(65504) is a sigma of about 256 world units, above which the
        // covariance term overflows the half range. Unclamped it becomes +inf,
        // ConservativeSigma returns inf, `depth - radius` is -inf, and the
        // splat is dropped by EVERY camera with nothing logged anywhere -- the
        // worst kind of failure: silent, total and invisible to a screenshot.
        const std::array<f32, 6> cov =
            CovarianceFromScaleRotation(glm::log(glm::vec3(5000.0f)), glm::vec4(1.0f, 0.0f, 0.0f, 0.0f));
        EXPECT_TRUE(std::isfinite(cov[0])) << "the covariance itself should still be finite in f32";

        u32 a = 0;
        u32 b = 0;
        u32 c = 0;
        PackCovariance(cov, a, b, c);
        for (const f32 term : UnpackCovariance(a, b, c))
            EXPECT_TRUE(std::isfinite(term));

        const GpuSplat splat{ glm::vec3(0.0f), 0u, a, b, c, 0u };
        EXPECT_TRUE(std::isfinite(ConservativeSigma(splat)));
        EXPECT_GT(ConservativeSigma(splat), 0.0f);
    }

    // -------------------------------------------------------------------------
    // The importer.
    // -------------------------------------------------------------------------

    TEST(GaussianSplatImport, ReadsTheCheckedInFixture)
    {
        const fs::path path = FixturePath();
        ASSERT_FALSE(path.empty()) << "fixture_discs.ply not found from " << fs::current_path().string();

        SplatCloud cloud;
        const LoadResult result = cloud.LoadPly(path);
        ASSERT_TRUE(result.Ok) << result.Error;
        EXPECT_EQ(result.SplatsRead, 4096u);
        EXPECT_EQ(cloud.Count(), 4096u);

        // Generator geometry: three unit-radius discs inside a 1.6-radius shell.
        const BoundingBox bounds = cloud.Bounds();
        EXPECT_NEAR(bounds.Min.x, -1.6f, 0.05f);
        EXPECT_NEAR(bounds.Max.x, 1.6f, 0.05f);
        EXPECT_NEAR(bounds.Min.z, -1.6f, 0.05f);
        EXPECT_NEAR(bounds.Max.z, 1.6f, 0.05f);

        // The generator writes 45 f_rest_* and 3 normal properties this
        // representation drops: 48 floats of 62 per splat.
        EXPECT_EQ(result.DiscardedSourceBytes, static_cast<sizet>(48) * sizeof(f32) * 4096u);
        EXPECT_EQ(cloud.GpuBytes(), static_cast<sizet>(32) * 4096u);
    }

    TEST(GaussianSplatImport, FixtureDecodesToTheAuthoredColoursAndOpacities)
    {
        const fs::path path = FixturePath();
        ASSERT_FALSE(path.empty());
        SplatCloud cloud;
        ASSERT_TRUE(cloud.LoadPly(path).Ok);

        // The generator lays out 832 splats per disc, then 1600 shell splats.
        const glm::vec4 firstDisc = UnpackColorOpacity(cloud.Splats()[0].ColorOpacity);
        EXPECT_NEAR(firstDisc.r, 0.90f, 1.0f / 255.0f);
        EXPECT_NEAR(firstDisc.g, 0.20f, 1.0f / 255.0f);
        EXPECT_NEAR(firstDisc.b, 0.18f, 1.0f / 255.0f);
        EXPECT_NEAR(firstDisc.a, 0.90f, 1.0f / 255.0f);

        const glm::vec4 shell = UnpackColorOpacity(cloud.Splats()[2496].ColorOpacity);
        EXPECT_NEAR(shell.a, 0.30f, 1.0f / 255.0f);

        // Disc splats are oblate: one sigma an order of magnitude below the
        // other two. A cloud read with the covariance terms in the wrong order
        // loses that and renders as round blobs.
        const std::array<f32, 6> cov =
            UnpackCovariance(cloud.Splats()[0].CovXXXY, cloud.Splats()[0].CovXZYY, cloud.Splats()[0].CovYZZZ);
        const f32 trace = cov[0] + cov[3] + cov[5];
        const f32 smallest = std::min({ cov[0], cov[3], cov[5] });
        EXPECT_LT(smallest * 50.0f, trace) << "the flat axis of a disc splat is missing";
    }

    TEST(GaussianSplatImport, AsciiAndBinaryAgree)
    {
        PlyBuilder binary = PlyBuilder::Minimal();
        binary.Rows.push_back({ -4.0f, 0.5f, 9.0f, 1.0f, -1.0f, 0.25f, 2.0f, -2.0f, -3.0f, -4.0f, 0.7f, 0.1f, 0.2f,
                                0.3f });
        PlyBuilder ascii = binary;
        ascii.Format = "ascii";

        SplatCloud fromBinary;
        SplatCloud fromAscii;
        const std::vector<u8> binaryBytes = binary.Build();
        const std::vector<u8> asciiBytes = ascii.Build();
        ASSERT_TRUE(fromBinary.LoadPlyFromMemory(binaryBytes, "binary").Ok);
        ASSERT_TRUE(fromAscii.LoadPlyFromMemory(asciiBytes, "ascii").Ok);

        ASSERT_EQ(fromBinary.Count(), fromAscii.Count());
        for (u32 i = 0; i < fromBinary.Count(); ++i)
        {
            const GpuSplat& a = fromBinary.Splats()[i];
            const GpuSplat& b = fromAscii.Splats()[i];
            // std::to_string gives 6 decimals, so positions agree to ~1e-6 and
            // the packed fields (8-bit colour, half covariance) agree exactly.
            EXPECT_NEAR(a.Position.x, b.Position.x, 1e-5f);
            EXPECT_NEAR(a.Position.y, b.Position.y, 1e-5f);
            EXPECT_NEAR(a.Position.z, b.Position.z, 1e-5f);
            EXPECT_EQ(a.ColorOpacity, b.ColorOpacity);
            EXPECT_EQ(a.CovXXXY, b.CovXXXY);
        }
    }

    TEST(GaussianSplatImport, RejectsRatherThanHalfLoads)
    {
        const auto expectFailure = [](const std::vector<u8>& bytes, std::string_view expectedSubstring)
        {
            SplatCloud cloud;
            const LoadResult result = cloud.LoadPlyFromMemory(bytes, "case");
            EXPECT_FALSE(result.Ok) << "accepted a file it should have rejected";
            EXPECT_TRUE(result.Error.find(expectedSubstring) != std::string::npos)
                << "error was: " << result.Error << "\nexpected it to mention: " << expectedSubstring;
            EXPECT_EQ(cloud.Count(), 0u) << "a rejected load must leave the cloud empty";
        };

        {
            const std::string notPly = "OBJ file, actually\n";
            expectFailure({ notPly.begin(), notPly.end() }, "not a PLY");
        }
        {
            PlyBuilder big = PlyBuilder::Minimal();
            big.Format = "binary_big_endian";
            expectFailure(big.Build(), "unsupported PLY format");
        }
        {
            PlyBuilder missing = PlyBuilder::Minimal();
            missing.Properties.erase(missing.Properties.begin() + 6); // opacity
            for (std::vector<f32>& row : missing.Rows)
                row.erase(row.begin() + 6);
            expectFailure(missing.Build(), "opacity");
        }
        {
            std::vector<u8> truncated = PlyBuilder::Minimal().Build();
            truncated.resize(truncated.size() - 8);
            expectFailure(truncated, "truncated");
        }
        {
            PlyBuilder infinite = PlyBuilder::Minimal();
            infinite.Rows[0][0] = std::numeric_limits<f32>::infinity();
            expectFailure(infinite.Build(), "non-finite");
        }
        {
            // An element before `vertex` shifts the payload; refusing is the
            // only safe answer because the alternative renders a wrong cloud.
            std::string header = "ply\nformat ascii 1.0\nelement camera 1\nproperty float cx\nelement vertex 1\n";
            expectFailure({ header.begin(), header.end() }, "precedes 'vertex'");
        }
        {
            // A LYING COUNT MUST NOT BE BELIEVED FAR ENOUGH TO ALLOCATE ON.
            // 4294967295 vertices at 56 bytes each is 240 GB; sizing the
            // per-property arrays from the header before checking the file
            // length would throw std::bad_alloc where the contract promises a
            // LoadResult. A test that only shortened the payload by a few bytes
            // would not have caught it -- the allocation has to be the thing
            // that would blow up.
            PlyBuilder liar = PlyBuilder::Minimal();
            std::vector<u8> bytes = liar.Build();
            const std::string header(reinterpret_cast<const char*>(bytes.data()), bytes.size());
            const sizet pos = header.find("element vertex 1");
            ASSERT_NE(pos, std::string::npos);
            std::string patched = header;
            patched.replace(pos, std::string("element vertex 1").size(), "element vertex 4294967295");
            expectFailure({ patched.begin(), patched.end() }, "truncated");
        }
    }

    TEST(GaussianSplatImport, DecodesEveryIntegerTypeItAgreesToStrideOver)
    {
        // THE BUG THIS PINS reads correctly and produces nonsense. `PlyTypeSize`
        // accepts short/ushort/int/uint so their columns can be strided over,
        // and an earlier `ReadScalar` fell through to a 4-byte float memcpy for
        // all of them. Two failures follow: a 2-byte column is read two bytes
        // past its own slot -- past the end of the buffer if it is the last
        // property of the last record -- and a 4-byte integer is reinterpreted
        // as a float bit pattern, which for small integers is a denormal that
        // sails through the finiteness check.
        //
        // So a required property is declared as each accepted integer type in
        // turn and its decoded value is checked, rather than merely checking
        // that the file loads.
        for (const char* type : { "short", "ushort", "int", "uint", "uchar", "char", "double" })
        {
            PlyBuilder typed = PlyBuilder::Minimal();
            typed.Types.assign(typed.Properties.size(), "float");
            // `x` carries the integer; a value no float bit pattern coincides
            // with, and small enough for every type above to hold.
            const sizet xColumn = 0;
            typed.Types[xColumn] = type;
            typed.Rows[0][xColumn] = 7.0f;

            SplatCloud cloud;
            const std::vector<u8> bytes = typed.Build();
            const LoadResult result = cloud.LoadPlyFromMemory(bytes, type);
            ASSERT_TRUE(result.Ok) << type << ": " << result.Error;
            ASSERT_EQ(cloud.Count(), 1u) << type;
            EXPECT_NEAR(cloud.Splats()[0].Position.x, 7.0f, 1e-5f) << "property declared as " << type;

            // The rest of the record must still land where the stride says, or
            // the mis-sized read has quietly shifted everything after it.
            EXPECT_NEAR(cloud.Splats()[0].Position.y, 2.0f, 1e-5f) << "stride broke after a " << type;
            EXPECT_NEAR(cloud.Splats()[0].Position.z, 3.0f, 1e-5f) << "stride broke after a " << type;
        }
    }

    TEST(GaussianSplatImport, AnIntegerColumnAtTheEndOfTheRecordIsNotOverread)
    {
        // The out-of-bounds half of the same bug, isolated: a 2-byte property as
        // the LAST column of the LAST record has only two bytes behind it, so a
        // 4-byte read runs off the end of the file image. It is the case a
        // sanitizer would catch and a normal run would not.
        PlyBuilder tail = PlyBuilder::Minimal();
        tail.Properties.push_back("confidence");
        tail.Types.assign(tail.Properties.size(), "float");
        tail.Types.back() = "ushort";
        tail.Rows[0].push_back(42.0f);

        SplatCloud cloud;
        const std::vector<u8> bytes = tail.Build();
        const LoadResult result = cloud.LoadPlyFromMemory(bytes, "trailing-ushort");
        ASSERT_TRUE(result.Ok) << result.Error;
        EXPECT_EQ(cloud.Count(), 1u);
        EXPECT_NEAR(cloud.Splats()[0].Position.x, 1.0f, 1e-5f);
        // Two bytes of the record are not this representation's, so they are
        // counted as discarded rather than silently absorbed.
        EXPECT_EQ(result.DiscardedSourceBytes, 2u);
    }

    TEST(GaussianSplatImport, ToleratesExtraPropertiesAndReordering)
    {
        // Exporters differ. The reader matches by name, so an unknown column in
        // the middle and a different block order must both still work.
        PlyBuilder shuffled;
        shuffled.Properties = { "rot_0", "rot_1", "rot_2", "rot_3", "confidence", "x", "y",
                                "z", "junk", "f_dc_0", "f_dc_1", "f_dc_2", "scale_0", "scale_1",
                                "scale_2", "opacity" };
        shuffled.Rows.push_back({ 1.0f, 0.0f, 0.0f, 0.0f, 42.0f, 5.0f, 6.0f, 7.0f, -1.0f, 0.0f, 0.0f, 0.0f, -3.0f,
                                  -3.0f, -3.0f, 0.0f });

        SplatCloud cloud;
        const std::vector<u8> bytes = shuffled.Build();
        const LoadResult result = cloud.LoadPlyFromMemory(bytes, "shuffled");
        ASSERT_TRUE(result.Ok) << result.Error;
        ASSERT_EQ(cloud.Count(), 1u);
        EXPECT_NEAR(cloud.Splats()[0].Position.x, 5.0f, 1e-6f);
        EXPECT_NEAR(cloud.Splats()[0].Position.z, 7.0f, 1e-6f);
        EXPECT_NEAR(UnpackColorOpacity(cloud.Splats()[0].ColorOpacity).a, 0.5f, 1.0f / 255.0f);
        // Two extra float columns per splat that this representation drops.
        EXPECT_EQ(result.DiscardedSourceBytes, 2u * sizeof(f32));
    }

    // -------------------------------------------------------------------------
    // Ordering.
    // -------------------------------------------------------------------------

    TEST(GaussianSplatOrdering, DepthKeyIsMonotonicInDepth)
    {
        f32 previous = 0.0f;
        u32 previousKey = 0;
        for (const f32 depth : { 1e-4f, 0.05f, 0.5f, 1.0f, 7.5f, 1000.0f, 1e6f })
        {
            const u32 key = DepthSortKey(depth);
            EXPECT_GT(key, previousKey) << "depth " << depth << " after " << previous;
            previous = depth;
            previousKey = key;
        }
        // A non-positive or NaN depth sorts to the FAR end of the descending
        // order (the largest key), so a degenerate splat is drawn first and
        // painted over. Key 0 would be the near end and would paint over the
        // whole frame instead.
        EXPECT_EQ(DepthSortKey(-1.0f), 0xFFFFFFFFu);
        EXPECT_EQ(DepthSortKey(0.0f), 0xFFFFFFFFu);
        EXPECT_EQ(DepthSortKey(std::numeric_limits<f32>::quiet_NaN()), 0xFFFFFFFFu);
        EXPECT_LT(DepthSortKey(1e30f), 0xFFFFFFFFu) << "a real depth must never collide with the sentinel";
    }

    TEST(GaussianSplatOrdering, RadixSortMatchesAStableStdSort)
    {
        std::mt19937 rng(971);
        // Duplicate-heavy and all-equal inputs on purpose: a radix pass that is
        // skipped as uniform is where a descending sort implemented by
        // reversing the last pass silently returns ascending order.
        for (const u32 modulus : { 4u, 256u, 65536u, 0xFFFFFFFFu, 1u })
        {
            for (const sizet count : { sizet{ 0 }, sizet{ 1 }, sizet{ 2 }, sizet{ 1000 }, sizet{ 4097 } })
            {
                std::vector<u32> keys(count);
                std::vector<u32> indices(count);
                std::iota(indices.begin(), indices.end(), 0u);
                for (u32& key : keys)
                    key = (modulus == 1u) ? 12345u : (rng() % modulus);

                std::vector<std::pair<u32, u32>> reference(count);
                for (sizet i = 0; i < count; ++i)
                    reference[i] = { keys[i], indices[i] };
                std::stable_sort(reference.begin(), reference.end(),
                                 [](const auto& a, const auto& b)
                                 { return a.first > b.first; });

                std::vector<u32> keyScratch;
                std::vector<u32> indexScratch;
                RadixSortDescending(keys, indices, keyScratch, indexScratch);

                for (sizet i = 0; i < count; ++i)
                {
                    ASSERT_EQ(keys[i], reference[i].first) << "modulus " << modulus << " count " << count << " at " << i;
                    ASSERT_EQ(indices[i], reference[i].second)
                        << "unstable at modulus " << modulus << " count " << count << " index " << i;
                }
            }
        }
    }

    TEST(GaussianSplatOrdering, FixtureIsOrderedFarToNearAndIsDeterministic)
    {
        const fs::path path = FixturePath();
        ASSERT_FALSE(path.empty());
        SplatCloud cloud;
        ASSERT_TRUE(cloud.LoadPly(path).Ok);

        const glm::mat4 view = glm::lookAt(glm::vec3(0.0f, 1.0f, 7.0f), glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        const glm::mat4 projection = glm::perspective(glm::radians(45.0f), 16.0f / 9.0f, 0.05f, 100.0f);
        const glm::vec2 viewport(1280.0f, 720.0f);

        ViewOrdering ordering;
        BuildViewOrdering(cloud, view, projection, viewport, ViewSettings{}, ordering);

        ASSERT_GT(ordering.Stats.Drawn, 3000u) << "most of the fixture should be visible from this pose";
        EXPECT_EQ(ordering.Indices.size(), ordering.Stats.Drawn);

        const glm::vec3 forward(-view[0][2], -view[1][2], -view[2][2]);
        const f32 forwardOffset = -view[3][2];
        f32 previousDepth = std::numeric_limits<f32>::max();
        for (const u32 index : ordering.Indices)
        {
            const f32 depth = glm::dot(forward, cloud.Splats()[index].Position) + forwardOffset;
            EXPECT_LE(depth, previousDepth + 1e-4f) << "draw order is not far-to-near";
            previousDepth = depth;
        }

        ViewOrdering again;
        BuildViewOrdering(cloud, view, projection, viewport, ViewSettings{}, again);
        EXPECT_EQ(ordering.Indices, again.Indices) << "the same camera must produce the same order";
    }

    TEST(GaussianSplatOrdering, CullsWhatIsBehindTheCameraAndOutsideTheFrustum)
    {
        const fs::path path = FixturePath();
        ASSERT_FALSE(path.empty());
        SplatCloud cloud;
        ASSERT_TRUE(cloud.LoadPly(path).Ok);

        const glm::mat4 projection = glm::perspective(glm::radians(45.0f), 16.0f / 9.0f, 0.05f, 100.0f);
        const glm::vec2 viewport(1280.0f, 720.0f);

        // Camera looking AWAY from the cloud: nothing may be drawn.
        const glm::mat4 away =
            glm::lookAt(glm::vec3(0.0f, 0.0f, 6.0f), glm::vec3(0.0f, 0.0f, 12.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        ViewOrdering behind;
        BuildViewOrdering(cloud, away, projection, viewport, ViewSettings{}, behind);
        EXPECT_EQ(behind.Stats.Drawn, 0u);
        EXPECT_EQ(behind.Stats.BehindNearPlane + behind.Stats.FrustumCulled, cloud.Count());

        // Camera INSIDE the cloud: the shell behind the eye must be dropped
        // while the shell in front survives.
        const glm::mat4 inside =
            glm::lookAt(glm::vec3(0.0f), glm::vec3(0.0f, 0.0f, -1.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        ViewOrdering within;
        BuildViewOrdering(cloud, inside, projection, viewport, ViewSettings{}, within);
        EXPECT_GT(within.Stats.BehindNearPlane, 0u);
        EXPECT_GT(within.Stats.Drawn, 0u);
        EXPECT_LT(within.Stats.Drawn, cloud.Count());
    }

    TEST(GaussianSplatLod, DistanceDropsSubPixelSplatsAndTheBudgetIsAHardCeiling)
    {
        const fs::path path = FixturePath();
        ASSERT_FALSE(path.empty());
        SplatCloud cloud;
        ASSERT_TRUE(cloud.LoadPly(path).Ok);

        const glm::mat4 projection = glm::perspective(glm::radians(45.0f), 16.0f / 9.0f, 0.05f, 1000.0f);
        const glm::vec2 viewport(1280.0f, 720.0f);

        // Monotone in distance: the further the camera, the fewer splats clear
        // the minimum screen extent. This is the "bounded LOD" claim.
        ViewSettings settings;
        settings.MinScreenExtentPixels = 2.0f;
        u32 previousDrawn = std::numeric_limits<u32>::max();
        for (const f32 distance : { 5.0f, 20.0f, 80.0f, 320.0f })
        {
            const glm::mat4 view =
                glm::lookAt(glm::vec3(0.0f, 0.0f, distance), glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));
            ViewOrdering ordering;
            BuildViewOrdering(cloud, view, projection, viewport, settings, ordering);
            EXPECT_LE(ordering.Stats.Drawn, previousDrawn) << "distance " << distance;
            previousDrawn = ordering.Stats.Drawn;
        }
        EXPECT_LT(previousDrawn, cloud.Count() / 4u) << "LOD did nothing at 320 units";

        // The budget is a ceiling regardless of what survived the other tests.
        const glm::mat4 close =
            glm::lookAt(glm::vec3(0.0f, 0.0f, 5.0f), glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        ViewSettings capped;
        capped.MaxSplats = 500;
        ViewOrdering ordering;
        BuildViewOrdering(cloud, close, projection, viewport, capped, ordering);
        EXPECT_EQ(ordering.Stats.Drawn, 500u);
        EXPECT_GT(ordering.Stats.OverBudget, 0u);

        // Still deterministic, and still ordered, under the cap.
        ViewOrdering again;
        BuildViewOrdering(cloud, close, projection, viewport, capped, again);
        EXPECT_EQ(ordering.Indices, again.Indices);
    }
} // namespace OloEngine::Tests
