// OLO_TEST_LAYER: unit
// =============================================================================
// Persistence for issue #1238, across all three surfaces the feature reaches:
//
//   * scene YAML — FoliageInteractionComponent (generated by OloHeaderTool from
//     the struct, so this test is what proves the generation actually happened
//     and that the Clamp annotations bite) and FoliageLayer::InteractionResponse
//     (hand-written, next to the wind keys);
//   * the ASSET PACK / binary scene reader, which the same annotations feed;
//   * save games — a hand-written Serialize overload plus its RegisterAll
//     registration, neither of which any coverage test guards.
//
// And the back-compat question this feature answers differently from its
// neighbours: the response DEFAULTS TO 1, not 0, because the off switch is the
// absence of an influence SOURCE. A v36 save has no FoliageInteractionComponent
// in it at all, so a response of 1 multiplies an empty set and that save
// renders exactly as it did.
#include "OloEnginePCH.h"
#include "OloEngine/SaveGame/SaveGameComponentSerializer.h"
#include "OloEngine/SaveGame/SaveGameTypes.h"
#include "OloEngine/SaveGame/SaveGameFile.h"
#include "OloEngine/Scene/Components.h"
#include "OloEngine/Scene/Entity.h"
#include "OloEngine/Scene/Scene.h"
#include "OloEngine/Scene/SceneSerializer.h"
#include "OloEngine/Serialization/Archive.h"
#include "OloEngine/Serialization/ArchiveExtensions.h"
#include "OloEngine/Terrain/Foliage/FoliageInteraction.h"
#include "OloEngine/Asset/AssetSerializer.h"
#include "OloEngine/Asset/AssetManager.h"
#include "OloEngine/Asset/AssetManager/RuntimeAssetManager.h"
#include "OloEngine/Project/Project.h"
#include "OloEngine/Serialization/FileStream.h"
#include "../TestTempDir.h"
#include <gtest/gtest.h>
#include <cmath>
#include <limits>
#include <string>

namespace OloEngine::Tests
{
    namespace
    {
        Entity FindByTag(Scene& scene, const char* tag)
        {
            for (auto e : scene.GetAllEntitiesWith<TagComponent>())
            {
                Entity ent{ e, &scene };
                if (ent.GetComponent<TagComponent>().Tag == tag)
                    return ent;
            }
            return {};
        }

        // Every field distinct from its default, and none of them a round
        // number a lower-precision lane would survive by luck.
        FoliageInteractionComponent MakeAuthoredSource()
        {
            FoliageInteractionComponent source;
            source.m_Radius = 2.6875f;
            source.m_Height = 1.8125f;
            source.m_Strength = 0.84375f; // inside the 1.0 cap, and not a round number
            source.m_Falloff = 3.3125f;
            source.m_RecoverySeconds = 0.71875f;
            source.m_TrailSpacing = 0.40625f;
            source.m_Enabled = false;
            return source;
        }

        void ExpectSourceEqual(const FoliageInteractionComponent& got, const FoliageInteractionComponent& want)
        {
            EXPECT_TRUE(Math::BitwiseEqual(got.m_Radius, want.m_Radius));
            EXPECT_TRUE(Math::BitwiseEqual(got.m_Height, want.m_Height));
            EXPECT_TRUE(Math::BitwiseEqual(got.m_Strength, want.m_Strength));
            EXPECT_TRUE(Math::BitwiseEqual(got.m_Falloff, want.m_Falloff));
            EXPECT_TRUE(Math::BitwiseEqual(got.m_RecoverySeconds, want.m_RecoverySeconds));
            EXPECT_TRUE(Math::BitwiseEqual(got.m_TrailSpacing, want.m_TrailSpacing));
            EXPECT_EQ(got.m_Enabled, want.m_Enabled);
        }
    } // namespace

    TEST(FoliageInteractionSaveLoad, SceneYamlRoundTripsTheSourceAndTheLayerResponse)
    {
        const auto authored = MakeAuthoredSource();
        FoliageLayer layer;
        layer.Name = "Meadow";
        layer.InteractionResponse = 2.15625f;

        std::string yaml;
        {
            auto scene = Scene::Create();
            Entity actor = scene->CreateEntity("Runner");
            actor.AddComponent<FoliageInteractionComponent>(authored);
            Entity ground = scene->CreateEntity("Meadow");
            ground.AddComponent<TerrainComponent>();
            ground.AddComponent<FoliageComponent>().m_Layers.push_back(layer);
            yaml = SceneSerializer(scene).SerializeToYAML();
        }
        ASSERT_FALSE(yaml.empty());

        auto reloaded = Scene::Create();
        ASSERT_TRUE(SceneSerializer(reloaded).DeserializeFromYAML(yaml));

        Entity restoredActor = FindByTag(*reloaded, "Runner");
        ASSERT_TRUE(static_cast<bool>(restoredActor));
        ASSERT_TRUE(restoredActor.HasComponent<FoliageInteractionComponent>())
            << "the generated scene serializer dropped FoliageInteractionComponent entirely";
        ExpectSourceEqual(restoredActor.GetComponent<FoliageInteractionComponent>(), authored);

        Entity restoredGround = FindByTag(*reloaded, "Meadow");
        ASSERT_TRUE(static_cast<bool>(restoredGround));
        ASSERT_TRUE(restoredGround.HasComponent<FoliageComponent>());
        const auto& foliage = restoredGround.GetComponent<FoliageComponent>();
        ASSERT_EQ(foliage.m_Layers.size(), 1u);
        EXPECT_TRUE(Math::BitwiseEqual(foliage.m_Layers[0].InteractionResponse, layer.InteractionResponse));
        // And undo equality sees it, or an inspector edit is unrevertable.
        FoliageLayer mutated = foliage.m_Layers[0];
        mutated.InteractionResponse += 0.5f;
        EXPECT_FALSE(mutated == foliage.m_Layers[0]);
    }

    // The COOKED cell. The loose .olo path above and this one are written by
    // two different emitters (the YAML writer and the binary one), and the
    // annotations feed both — so a component that round-trips loose can still
    // be dropped from a shipped pack. Exercises the real cook writer and the
    // real runtime scene reader, not a re-serialization.
    TEST(FoliageInteractionSaveLoad, TheAssetPackCarriesTheSourceAndTheLayerResponse)
    {
        const auto authored = MakeAuthoredSource();
        FoliageLayer layer;
        layer.Name = "Meadow";
        layer.InteractionResponse = 0.65625f;

        auto scene = Scene::Create();
        {
            Entity actor = scene->CreateEntity("Runner");
            actor.AddComponent<FoliageInteractionComponent>(authored);
            Entity ground = scene->CreateEntity("Meadow");
            ground.AddComponent<TerrainComponent>();
            ground.AddComponent<FoliageComponent>().m_Layers.push_back(layer);
        }
        const auto yaml = SceneSerializer(scene).SerializeToYAML();
        ASSERT_FALSE(yaml.empty());

        ASSERT_TRUE(Project::HasAssetManager() || !Project::GetActive());
        struct AssetManagerRestore
        {
            Ref<AssetManagerBase> Previous;
            ~AssetManagerRestore()
            {
                if (Previous)
                    Project::SetAssetManager(Previous);
                else
                    Project::Unload();
            }
        } restore{ Project::HasAssetManager() ? Project::GetAssetManager() : nullptr };
        auto manager = Ref<RuntimeAssetManager>::Create(false);
        Project::SetAssetManager(manager);
        const auto handle = AssetManager::AddMemoryOnlyAsset(scene);
        ASSERT_TRUE(handle);

        const auto path = TempFile("foliage-interaction-scene.bin");
        SceneAssetSerializer serializer;
        AssetSerializationInfo cooked{};
        {
            FileStreamWriter writer(path);
            ASSERT_TRUE(writer.IsStreamGood());
            ASSERT_TRUE(serializer.SerializeToAssetPack(handle, writer, cooked));
        }
        FileStreamReader reader(path);
        AssetPackFile::SceneInfo info;
        info.Handle = handle;
        info.PackedOffset = cooked.Offset;
        info.PackedSize = cooked.Size;
        auto packed = serializer.DeserializeSceneFromAssetPack(reader, info);
        ASSERT_TRUE(packed);

        sizet sources = 0;
        for (auto id : packed->GetAllEntitiesWith<FoliageInteractionComponent>())
        {
            Entity e{ id, packed.get() };
            ExpectSourceEqual(e.GetComponent<FoliageInteractionComponent>(), authored);
            ++sources;
        }
        EXPECT_EQ(sources, 1u) << "the cooked pack dropped the influence source";

        sizet meadows = 0;
        for (auto id : packed->GetAllEntitiesWith<FoliageComponent>())
        {
            Entity e{ id, packed.get() };
            const auto& layers = e.GetComponent<FoliageComponent>().m_Layers;
            ASSERT_EQ(layers.size(), 1u);
            EXPECT_TRUE(Math::BitwiseEqual(layers[0].InteractionResponse, layer.InteractionResponse));
            ++meadows;
        }
        EXPECT_EQ(meadows, 1u);
    }

    TEST(FoliageInteractionSaveLoad, ASceneWithoutTheKeysLoadsWithTheFeatureInert)
    {
        // A .olo written before #1238: no FoliageInteractionComponent anywhere,
        // and no InteractionResponse key on the layer. It must come back with a
        // response of 1 — NOT 0 — and with nothing that emits an influence, so
        // its foliage renders exactly as it rendered.
        const std::string priorYaml = R"(Scene: Prior
Entities:
  - Entity: 12345678901234567891
    TagComponent:
      Tag: Meadow
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    FoliageComponent:
      Enabled: true
      Layers:
        - Name: Grass
          Density: 1.5
          WindStrength: 0.4
          Enabled: true
)";
        auto reloaded = Scene::Create();
        ASSERT_TRUE(SceneSerializer(reloaded).DeserializeFromYAML(priorYaml));
        Entity restored = FindByTag(*reloaded, "Meadow");
        ASSERT_TRUE(static_cast<bool>(restored));
        const auto& foliage = restored.GetComponent<FoliageComponent>();
        ASSERT_EQ(foliage.m_Layers.size(), 1u);
        EXPECT_FLOAT_EQ(foliage.m_Layers[0].InteractionResponse, 1.0f);
        // The keys it DID carry are intact, so this measures the new key's
        // absence rather than a load that failed quietly.
        EXPECT_FLOAT_EQ(foliage.m_Layers[0].Density, 1.5f);
        EXPECT_FLOAT_EQ(foliage.m_Layers[0].WindStrength, 0.4f);
        EXPECT_FALSE(restored.HasComponent<FoliageInteractionComponent>());
    }

    TEST(FoliageInteractionSaveLoad, HostileSceneValuesAreBounded)
    {
        // Every one of these reaches the field: a pow() exponent, a divisor in
        // the spring's angular frequency, a radius the shader divides by. A NaN
        // here is not a wrong-looking bend — it is a bend that never recovers,
        // because NaN compares false against the retire threshold.
        const std::string hostileYaml = R"(Scene: Hostile
Entities:
  - Entity: 12345678901234567891
    TagComponent:
      Tag: Runner
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    FoliageInteractionComponent:
      Radius: .nan
      Height: -8
      Strength: 900
      Falloff: 0.001
      RecoverySeconds: .inf
      TrailSpacing: -3
      Enabled: true
  - Entity: 12345678901234567892
    TagComponent:
      Tag: Meadow
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    FoliageComponent:
      Enabled: true
      Layers:
        - Name: Grass
          InteractionResponse: .nan
          Enabled: true
        - Name: Weeds
          InteractionResponse: 400
          Enabled: true
)";
        auto reloaded = Scene::Create();
        ASSERT_TRUE(SceneSerializer(reloaded).DeserializeFromYAML(hostileYaml));

        Entity actor = FindByTag(*reloaded, "Runner");
        ASSERT_TRUE(static_cast<bool>(actor));
        ASSERT_TRUE(actor.HasComponent<FoliageInteractionComponent>());
        const auto& source = actor.GetComponent<FoliageInteractionComponent>();
        EXPECT_TRUE(std::isfinite(source.m_Radius));
        EXPECT_GE(source.m_Radius, 0.05f);
        EXPECT_GE(source.m_Height, 0.0f);
        EXPECT_LE(source.m_Strength, kFoliageInteractionMaxStrength);
        EXPECT_GE(source.m_Falloff, 0.25f);
        EXPECT_TRUE(std::isfinite(source.m_RecoverySeconds));
        EXPECT_LE(source.m_RecoverySeconds, kFoliageInteractionMaxRecovery);
        EXPECT_GE(source.m_TrailSpacing, 0.0f);

        Entity ground = FindByTag(*reloaded, "Meadow");
        ASSERT_TRUE(static_cast<bool>(ground));
        const auto& foliage = ground.GetComponent<FoliageComponent>();
        ASSERT_EQ(foliage.m_Layers.size(), 2u);
        EXPECT_TRUE(std::isfinite(foliage.m_Layers[0].InteractionResponse));
        EXPECT_LE(foliage.m_Layers[1].InteractionResponse, 8.0f);
        // And the bound derived from it stays finite, which is what the
        // instance AABB is padded by.
        for (const auto& l : foliage.m_Layers)
            EXPECT_TRUE(std::isfinite(FoliageInteractionMaximumDisplacement(l.InteractionResponse)));
    }

    TEST(FoliageInteractionSaveLoad, SaveGameRoundTripsTheSourceAndSanitizesHostileBytes)
    {
        const auto authored = MakeAuthoredSource();
        std::vector<u8> bytes;
        {
            auto copy = authored;
            FMemoryWriter writer(bytes);
            writer.SetArchiveVersion(kSaveGameFormatVersion);
            SaveGameComponentSerializer::Serialize(writer, copy);
        }
        {
            FoliageInteractionComponent loaded;
            FMemoryReader reader(bytes);
            reader.SetArchiveVersion(kSaveGameFormatVersion);
            SaveGameComponentSerializer::Serialize(reader, loaded);
            EXPECT_FALSE(reader.IsError());
            EXPECT_TRUE(reader.AtEnd()) << "the overload wrote more bytes than it reads back";
            ExpectSourceEqual(loaded, authored);
        }

        // A corrupted save is no more trusted than a corrupted .olo, and the
        // OLO_SERIALIZE(Clamp) annotations do NOT reach this path — the
        // overload applies the bounds itself, which is the thing most likely to
        // be forgotten when a field is added.
        FoliageInteractionComponent hostile;
        hostile.m_Radius = std::numeric_limits<f32>::quiet_NaN();
        hostile.m_Height = std::numeric_limits<f32>::infinity();
        hostile.m_Strength = 5000.0f;
        hostile.m_Falloff = -2.0f;
        hostile.m_RecoverySeconds = std::numeric_limits<f32>::quiet_NaN();
        hostile.m_TrailSpacing = -17.0f;
        std::vector<u8> poison;
        {
            FMemoryWriter writer(poison);
            writer.SetArchiveVersion(kSaveGameFormatVersion);
            SaveGameComponentSerializer::Serialize(writer, hostile);
        }
        FoliageInteractionComponent recovered;
        FMemoryReader reader(poison);
        reader.SetArchiveVersion(kSaveGameFormatVersion);
        SaveGameComponentSerializer::Serialize(reader, recovered);
        EXPECT_TRUE(std::isfinite(recovered.m_Radius));
        EXPECT_GE(recovered.m_Radius, 0.05f);
        EXPECT_TRUE(std::isfinite(recovered.m_Height));
        EXPECT_LE(recovered.m_Strength, kFoliageInteractionMaxStrength);
        EXPECT_GE(recovered.m_Falloff, 0.25f);
        EXPECT_TRUE(std::isfinite(recovered.m_RecoverySeconds));
        EXPECT_GE(recovered.m_RecoverySeconds, kFoliageInteractionMinRecovery);
        EXPECT_GE(recovered.m_TrailSpacing, 0.0f);
    }

    TEST(FoliageInteractionSaveLoad, AV36SaveKeepsAResponseOfOneAndConsumesItsExactPayload)
    {
        // The old positional layout, written independently of the production
        // writer — so this is a test of the reader's version gate rather than a
        // test of the writer agreeing with itself.
        std::vector<u8> bytes;
        {
            FMemoryWriter ar(bytes);
            FoliageLayer l;
            l.WindStiffness = 0.25f;
            u32 count = 1;
            ar << count;
            ar << l.Name << l.MeshPath << l.AlbedoPath;
            ar << l.Density << l.SplatmapChannel << l.MinSlopeAngle << l.MaxSlopeAngle;
            ar << l.MinScale << l.MaxScale << l.MinHeight << l.MaxHeight << l.RandomRotation;
            ar << l.ViewDistance << l.FadeStartDistance << l.WindStrength << l.WindSpeed;
            ar << l.BaseColor << l.Roughness << l.AlphaCutoff << l.Enabled;
            ar << l.UseImpostor << l.ImpostorStartDistance << l.ImpostorTransitionBand;
            ar << l.ImpostorFramesPerAxis << l.ImpostorAtlasResolution << l.ImpostorHemiOctahedral;
            ar << l.UseAuthoredMesh << l.MeshViewDistance << l.MeshFadeStartDistance;
            ar << l.NormalMapPath << l.RoughnessMapPath << l.ThicknessMapPath;
            ar << l.NormalStrength << l.TransmissionStrength << l.TransmissionColor << l.Thickness;
            ar << l.TransmissionDistortion << l.TransmissionPower << l.TransmissionWrap << l.TransmissionAmbient;
            ar << l.SlopeFeather;
            ar << l.UseAltitudeBand << l.MinAltitude << l.MaxAltitude << l.AltitudeFeather;
            ar << l.UseMoisture << l.MinMoisture << l.MaxMoisture << l.MoistureFeather;
            ar << l.ExclusionSplatmapChannel << l.ExclusionThreshold;
            ar << l.ClumpStrength << l.ClumpScale << l.ClumpFalloff << l.ClumpScaleInfluence;
            ar << l.ClumpGroup;
            ar << l.GroundOffset << l.SlopeSinkFactor;
            ar << l.DecorrelatedVariation;
            ar << l.WindStiffness << l.WindBranchWeight << l.WindLeafWeight << l.WindDebugDisplacement;
            bool enabled = true;
            ar << enabled;
        }

        FoliageComponent loaded;
        FMemoryReader reader(bytes);
        reader.SetArchiveVersion(36);
        SaveGameComponentSerializer::Serialize(reader, loaded);
        EXPECT_FALSE(reader.IsError());
        EXPECT_TRUE(reader.AtEnd()) << "the v37 band consumed bytes a v36 save does not contain";
        ASSERT_EQ(loaded.m_Layers.size(), 1u);
        EXPECT_FLOAT_EQ(loaded.m_Layers[0].InteractionResponse, 1.0f);
        EXPECT_FLOAT_EQ(loaded.m_Layers[0].WindStiffness, 0.25f);
        EXPECT_TRUE(loaded.m_Enabled);
    }
} // namespace OloEngine::Tests
