// =============================================================================
// SaveGameComponentSerializerCoverageTest.cpp
//
// Meta-test: every component registered via `REGISTER_SAVE_COMPONENT(...)` in
// `SaveGame/SaveGameComponentSerializer.cpp` must also be enumerated in BOTH
// per-entity loops — the `SAVE_COMPONENT(...)` capture list and the
// `TRY_LOAD_COMPONENT(...)` restore list — and vice versa.
//
// Those two lists are NO LONGER hand-written in SaveGameSerializer.cpp: as of
// the #380 codegen slice they are generated by OloHeaderTool into
// `SaveGame/Generated/SaveGameComponent{Capture,Restore}.Generated.inl` (from
// every `struct *Component` with a save serializer, minus the generator's
// kComponentsNotInSaveGame set) and #include'd by SaveGameSerializer.cpp. So
// this test now parses the GENERATED .inl files, not the .cpp — repointing the
// grep is the documented gotcha when a touch-point moves into a generated file
// (CLAUDE.md). RegisterAll() in SaveGameComponentSerializer.cpp stays hand-
// written, so the registered-vs-generated comparison is the live guard:
// regenerate (build GenerateBindings) after editing RegisterAll or this fails.
//
// Catches the silent "registered but never captured" bug class (issue #325):
// `RegisterAll()` registers a `Serialize()` overload, but a component missing
// from either generated list round-trips fine through scene YAML yet silently
// vanishes through save-games — inventory/quest/ability progress lost, no
// error, no warning.
//
// Sibling of ComponentSerializerCoverageTest.cpp, which pins the equivalent
// contract for the scene-YAML path (Components.h ↔ SceneSerializer.cpp).
// =============================================================================

#include "OloEnginePCH.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#ifndef OLO_TEST_EDITOR_ROOT
#error "OLO_TEST_EDITOR_ROOT must be defined by the test target's CMake — see OloEngine/tests/CMakeLists.txt"
#endif

namespace OloEngine::Tests
{
    namespace
    {
        namespace fs = std::filesystem;

        fs::path RepoRoot()
        {
            return fs::path{ OLO_TEST_EDITOR_ROOT }.parent_path();
        }

        fs::path SaveGameDir()
        {
            return RepoRoot() / "OloEngine" / "src" / "OloEngine" / "SaveGame";
        }

        // OloHeaderTool-generated SAVE_COMPONENT / TRY_LOAD_COMPONENT lists live here.
        fs::path GeneratedDir()
        {
            return SaveGameDir() / "Generated";
        }

        fs::path CaptureListFile()
        {
            return GeneratedDir() / "SaveGameComponentCapture.Generated.inl";
        }

        fs::path RestoreListFile()
        {
            return GeneratedDir() / "SaveGameComponentRestore.Generated.inl";
        }

        std::string ReadFile(const fs::path& path)
        {
            std::ifstream f(path, std::ios::binary);
            std::ostringstream buf;
            buf << f.rdbuf();
            return buf.str();
        }

        std::set<std::string> Matches(const std::string& src, const std::regex& pat)
        {
            std::set<std::string> out;
            for (auto it = std::sregex_iterator(src.begin(), src.end(), pat);
                 it != std::sregex_iterator(); ++it)
            {
                out.insert((*it)[1].str());
            }
            return out;
        }

        // The `;` in the pattern requires a macro *invocation*, so the
        // `#define REGISTER_SAVE_COMPONENT(ComponentType) ...` line (which ends
        // with the macro body, no trailing `;`) never matches.
        std::set<std::string> RegisteredComponents()
        {
            const std::string src = ReadFile(SaveGameDir() / "SaveGameComponentSerializer.cpp");
            return Matches(src, std::regex{ R"(REGISTER_SAVE_COMPONENT\((\w+)\);)" });
        }

        // Capture list — the generated SAVE_COMPONENT(...) enumeration #include'd
        // by CaptureSceneState. Reads the generated .inl, NOT SaveGameSerializer.cpp.
        std::set<std::string> SavedComponents()
        {
            const std::string src = ReadFile(CaptureListFile());
            return Matches(src, std::regex{ R"(SAVE_COMPONENT\((\w+), entity, writer\);)" });
        }

        // Restore list — the generated TRY_LOAD_COMPONENT(...) enumeration
        // #include'd by DeserializeEntitiesInto. The generated list is uniform
        // (every entry, IDComponent included, is a TRY_LOAD_COMPONENT — the old
        // bare-first LOAD_COMPONENT(IDComponent) special case is gone now that
        // codegen emits the list), so a single pattern covers it.
        std::set<std::string> LoadedComponents()
        {
            const std::string src = ReadFile(RestoreListFile());
            return Matches(src, std::regex{ R"(TRY_LOAD_COMPONENT\((\w+)\);)" });
        }

        void ExpectSubset(const std::set<std::string>& names,
                          const std::set<std::string>& allowed,
                          const char* missingFrom, const char* fixHint)
        {
            std::vector<std::string> missing;
            for (const auto& name : names)
            {
                if (!allowed.contains(name))
                    missing.push_back(name);
            }
            if (!missing.empty())
            {
                std::ostringstream oss;
                oss << missing.size() << " component type(s) missing from " << missingFrom << ":\n";
                for (const auto& n : missing)
                    oss << "  - " << n << "\n";
                oss << "\n"
                    << fixHint << "\n";
                FAIL() << oss.str();
            }
        }
    } // namespace

    // Forward: a registered serializer that the capture/restore loops never
    // invoke is dead code AND a data-loss bug — the component silently
    // vanishes through save-games.
    TEST(SaveGameComponentSerializerCoverage, EveryRegisteredComponentIsCapturedAndRestored)
    {
        ASSERT_TRUE(fs::exists(CaptureListFile()))
            << "Generated capture list missing: " << CaptureListFile().string()
            << " — run `cmake --build build --target GenerateBindings`.";
        ASSERT_TRUE(fs::exists(RestoreListFile()))
            << "Generated restore list missing: " << RestoreListFile().string()
            << " — run `cmake --build build --target GenerateBindings`.";

        const std::set<std::string> registered = RegisteredComponents();
        ASSERT_FALSE(registered.empty())
            << "REGISTER_SAVE_COMPONENT scan produced no matches — "
               "SaveGameComponentSerializer.cpp format changed and this test needs updating.";

        const std::set<std::string> saved = SavedComponents();
        const std::set<std::string> loaded = LoadedComponents();
        ASSERT_FALSE(saved.empty()) << "SAVE_COMPONENT scan produced no matches in the generated capture list.";
        ASSERT_FALSE(loaded.empty()) << "TRY_LOAD_COMPONENT scan produced no matches in the generated restore list.";

        ExpectSubset(registered, saved,
                     "the generated SAVE_COMPONENT(...) capture list (SaveGameComponentCapture.Generated.inl)",
                     "A registered component is absent from the generated capture loop. Normally the "
                     "generator adds it automatically — rebuild GenerateBindings. If it is excluded on "
                     "purpose (no save serializer), it must NOT have a REGISTER_SAVE_COMPONENT entry; add "
                     "it to kComponentsNotInSaveGame in tools/OloHeaderTool/main.cpp if it slipped in.");
        ExpectSubset(registered, loaded,
                     "the generated TRY_LOAD_COMPONENT(...) restore list (SaveGameComponentRestore.Generated.inl)",
                     "A registered component is absent from the generated restore loop — rebuild "
                     "GenerateBindings (a component saved but never restored is silently dropped on load).");
    }

    // Inverse: an enumerated component with no registered serializer would fail
    // to compile (SAVE_COMPONENT calls the Serialize overload directly), so in
    // practice this guards the generator's kComponentsNotInSaveGame set — if it
    // wrongly *keeps* a component that lost its REGISTER_SAVE_COMPONENT entry,
    // the generated lists would contain an unregistered name. The three lists
    // must stay in lock-step.
    TEST(SaveGameComponentSerializerCoverage, EveryCapturedAndRestoredComponentIsRegistered)
    {
        const std::set<std::string> registered = RegisteredComponents();
        ASSERT_FALSE(registered.empty());

        const std::set<std::string> saved = SavedComponents();
        const std::set<std::string> loaded = LoadedComponents();
        ASSERT_FALSE(saved.empty());
        ASSERT_FALSE(loaded.empty());

        ExpectSubset(saved, registered,
                     "RegisterAll() in SaveGameComponentSerializer.cpp (referenced by the generated SAVE_COMPONENT list)",
                     "Add a REGISTER_SAVE_COMPONENT(<Name>); entry to RegisterAll(), or add <Name> to "
                     "kComponentsNotInSaveGame in tools/OloHeaderTool/main.cpp and rebuild GenerateBindings.");
        ExpectSubset(loaded, registered,
                     "RegisterAll() in SaveGameComponentSerializer.cpp (referenced by the generated TRY_LOAD_COMPONENT list)",
                     "Add a REGISTER_SAVE_COMPONENT(<Name>); entry to RegisterAll(), or add <Name> to "
                     "kComponentsNotInSaveGame in tools/OloHeaderTool/main.cpp and rebuild GenerateBindings.");

        // Symmetry between the two enumeration lists follows from both being
        // subsets of `registered` plus the forward test's superset checks,
        // but assert it directly for a clearer failure message.
        EXPECT_EQ(saved, loaded)
            << "SAVE_COMPONENT and TRY_LOAD_COMPONENT lists have drifted apart — "
               "a component saved but not loaded (or vice versa) is silently dropped.";
    }
} // namespace OloEngine::Tests
