#!/usr/bin/env python3
"""Generate the Gaussian-splat test fixture (issue #971).

Writes a `binary_little_endian` PLY in the exact property layout the INRIA
"3D Gaussian Splatting for Real-Time Radiance Field Rendering" trainer emits,
so the importer under test is reading a real-shaped file rather than one shaped
to suit it:

    x y z  nx ny nz  f_dc_0..2  f_rest_0..44  opacity  scale_0..2  rot_0..3

62 float32 properties, 248 bytes per splat. `nx ny nz` are written as zero,
which is what the trainer does; `f_rest_*` carries the SH bands the importer
deliberately drops.

The cloud is a teaching figure, not a scan: three mutually orthogonal coloured
discs of flat (oblate) Gaussians inside a faint white sphere shell. That shape
was chosen because it makes the two things this spike has to demonstrate
visible by eye:

  * ANISOTROPY -- a disc read as a cloud of round blobs means the covariance
    was built wrong (a wrong quaternion component order does exactly that);
  * ORDERING -- the shell is semi-transparent, so a back-to-front failure shows
    up as the shell washing out the discs, or as discs punching through it.

Deterministic: same seed, byte-identical file. Regenerate with

    python tools/splat/make_splat_fixture.py OloEditor/assets/tests/splat/fixture_discs.ply
"""

from __future__ import annotations

import argparse
import math
import random
import struct
import sys

SH_C0 = 0.28209479177387814
SH_REST = 45


def logit(p: float) -> float:
    return math.log(p / (1.0 - p))


def color_to_dc(rgb: tuple[float, float, float]) -> tuple[float, float, float]:
    return tuple((c - 0.5) / SH_C0 for c in rgb)


def quat_from_axis_angle(axis: tuple[float, float, float], angle: float):
    """Returns (w, x, y, z), the order the PLY stores rot_0..rot_3 in."""
    norm = math.sqrt(sum(a * a for a in axis)) or 1.0
    ax, ay, az = (a / norm for a in axis)
    s = math.sin(angle * 0.5)
    return (math.cos(angle * 0.5), ax * s, ay * s, az * s)


def disc(rng: random.Random, count: int, normal_axis: int, color, radius: float):
    """Oblate splats on a disc perpendicular to `normal_axis`."""
    # The splat's local z is its thin axis, so the disc's plane normal is what
    # local z must be rotated onto.
    rotations = {
        0: quat_from_axis_angle((0.0, 1.0, 0.0), math.pi * 0.5),  # z -> x
        1: quat_from_axis_angle((1.0, 0.0, 0.0), -math.pi * 0.5),  # z -> y
        2: (1.0, 0.0, 0.0, 0.0),  # z -> z
    }
    rot = rotations[normal_axis]
    dc = color_to_dc(color)
    out = []
    for _ in range(count):
        # sqrt keeps the samples area-uniform rather than clustered at the hub.
        r = radius * math.sqrt(rng.random())
        theta = rng.uniform(0.0, 2.0 * math.pi)
        a, b = r * math.cos(theta), r * math.sin(theta)
        pos = [0.0, 0.0, 0.0]
        plane = [i for i in range(3) if i != normal_axis]
        pos[plane[0]] = a
        pos[plane[1]] = b
        out.append(
            dict(
                pos=tuple(pos),
                dc=dc,
                opacity=logit(0.90),
                scale=(math.log(0.055), math.log(0.055), math.log(0.006)),
                rot=rot,
            )
        )
    return out


def shell(rng: random.Random, count: int, radius: float):
    dc = color_to_dc((0.85, 0.86, 0.90))
    out = []
    for _ in range(count):
        # Marsaglia: uniform on the sphere, so the shell has no pole clustering
        # that would read as a rendering artefact.
        while True:
            x1, x2 = rng.uniform(-1, 1), rng.uniform(-1, 1)
            s = x1 * x1 + x2 * x2
            if s < 1.0:
                break
        f = math.sqrt(1.0 - s)
        direction = (2.0 * x1 * f, 2.0 * x2 * f, 1.0 - 2.0 * s)
        out.append(
            dict(
                pos=tuple(radius * d for d in direction),
                dc=dc,
                opacity=logit(0.30),
                scale=(math.log(0.045),) * 3,
                rot=(1.0, 0.0, 0.0, 0.0),
            )
        )
    return out


def build(seed: int):
    rng = random.Random(seed)
    splats = []
    splats += disc(rng, 832, 0, (0.90, 0.20, 0.18), 1.00)
    splats += disc(rng, 832, 1, (0.22, 0.80, 0.28), 1.00)
    splats += disc(rng, 832, 2, (0.20, 0.35, 0.95), 1.00)
    splats += shell(rng, 1600, 1.60)
    return splats


def write_ply(path: str, splats) -> None:
    names = ["x", "y", "z", "nx", "ny", "nz"]
    names += [f"f_dc_{i}" for i in range(3)]
    names += [f"f_rest_{i}" for i in range(SH_REST)]
    names += ["opacity"]
    names += [f"scale_{i}" for i in range(3)]
    names += [f"rot_{i}" for i in range(4)]
    assert len(names) == 62, len(names)

    header = "ply\nformat binary_little_endian 1.0\n"
    header += f"comment generated by tools/splat/make_splat_fixture.py for issue #971\n"
    header += f"element vertex {len(splats)}\n"
    header += "".join(f"property float {n}\n" for n in names)
    header += "end_header\n"

    with open(path, "wb") as handle:
        handle.write(header.encode("ascii"))
        for s in splats:
            values = list(s["pos"]) + [0.0, 0.0, 0.0] + list(s["dc"]) + [0.0] * SH_REST
            values += [s["opacity"]] + list(s["scale"]) + list(s["rot"])
            assert len(values) == 62
            handle.write(struct.pack("<62f", *values))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output")
    parser.add_argument("--seed", type=int, default=971)
    args = parser.parse_args()

    splats = build(args.seed)
    write_ply(args.output, splats)
    print(f"{args.output}: {len(splats)} splats, {len(splats) * 62 * 4 + 0} bytes of payload")
    return 0


if __name__ == "__main__":
    sys.exit(main())
