#pragma once

#include "OloEngine/Core/Base.h"
#include "OloEngine/Scene/Entity.h"
#include "OloEngine/Scripting/VisualScript/VisualScriptTypes.h"

#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace OloEngine::VisualScript
{
    //==============================================================================
    /// The engine-side component-field registry behind the `Component.GetField` /
    /// `Component.SetField` nodes (issue #793).
    ///
    /// A graph addresses a field by two runtime strings — a component name and a
    /// field key — and this table is what turns that pair into real typed code.
    /// The entries are GENERATED by OloHeaderTool from the same full data-member
    /// scan that drives the scene serializer, so a component becomes graph-readable
    /// the moment it compiles, with no hand-maintained list to rot.
    ///
    /// **Why this exists next to the MCP field registry rather than reusing it.**
    /// `McpFieldRegistry.Generated.inl` is the same idea, but it lives under
    /// `OloEditor/`. A graph runs in `OloRuntime` and `OloServer`, neither of which
    /// links the editor, so the editor's registry cannot serve a runtime node. The
    /// two are generated from one scan with one exclusion set and one clamp table
    /// (see `tools/OloHeaderTool/main.cpp`), which is what keeps them from drifting
    /// even though they are compiled into different binaries.
    ///
    /// **What is not in here.** A field the scan drops (non-public,
    /// `OLO_SERIALIZE(Skip)`, or a type with no `PinType` shape — `u64`, `ivec*`,
    /// `quat`, `mat*`, `Ref<T>`, any container) and every field of a component in
    /// the generator's `kComponentsNotFieldEditable` set (per-tick runtime state and
    /// entity identity). Absence is reported to the graph as an error, never
    /// silently ignored.
    //==============================================================================

    /// A clamp bound. Absent means unbounded on that side.
    struct FieldBound
    {
        bool m_Present = false;
        f64 m_Value = 0.0;
    };

    /// The load-time range the scene serializer enforces on a field, re-declared so
    /// a graph write lands in the same set of values a scene load could produce.
    /// Empty for the majority of fields, which carry no annotation.
    struct FieldBounds
    {
        FieldBound m_Min;
        FieldBound m_Max;

        [[nodiscard]] bool IsBounded() const noexcept
        {
            return m_Min.m_Present || m_Max.m_Present;
        }
    };

    /// What a write did. `Rejected` exists because the alternative is a silent
    /// no-op: a graph can compute a NaN (0/0 is not an error in a Float node) and
    /// storing one into a component poisons every consumer downstream of it,
    /// frames later and far from the graph that produced it. The node reports a
    /// rejection as a runtime error on the instance.
    enum class FieldWriteResult : u8
    {
        Changed = 0,
        /// The value was already what was asked for. Not an error.
        Unchanged,
        /// A non-finite float component. Nothing was stored.
        Rejected,
    };

    //==============================================================================
    /// One addressable (component, field) pair, type-erased over the field's C++
    /// type. The function pointers are stateless — the component type, the member
    /// access chain and the pin kind are all baked in as template arguments — so
    /// the ~1.5k-entry table costs three pointers per row and no allocation, unlike
    /// the editor registry's `std::function` rows.
    struct ComponentFieldEntry
    {
        /// The struct's own name, e.g. "TransformComponent". This is also its scene
        /// YAML key and its MCP component name, so the three never disagree.
        std::string m_Component;
        /// The `m_`-stripped field key, dotted for a field inside a nested record
        /// ("Translation", "HeightShaping.IslandFalloff").
        std::string m_Field;
        PinType m_Type = PinType::Any;
        FieldBounds m_Bounds;

        bool (*m_Has)(Entity) = nullptr;
        PinValue (*m_Read)(Entity) = nullptr;
        FieldWriteResult (*m_Write)(Entity, const PinValue&, const FieldBounds&) = nullptr;

        [[nodiscard]] bool Has(Entity entity) const
        {
            return m_Has(entity);
        }
        /// The field's current value. Precondition: `Has(entity)`.
        [[nodiscard]] PinValue Read(Entity entity) const
        {
            return m_Read(entity);
        }
        /// Coerce, clamp to `m_Bounds`, and store. Precondition: `Has(entity)`.
        FieldWriteResult Write(Entity entity, const PinValue& value) const
        {
            return m_Write(entity, value, m_Bounds);
        }
    };

    //==============================================================================
    /// Process-wide lookup over the generated table. Built once, on first use.
    class ComponentFieldRegistry
    {
      public:
        /// Every entry, sorted by component then field — the order the editor's
        /// field pickers present, and a stable order for tests.
        [[nodiscard]] static std::span<const ComponentFieldEntry> All();

        /// The entry for `component`.`field`, or null.
        ///
        /// `component` accepts BOTH the struct name ("TransformComponent") and the
        /// short name the existing `Entity.AddComponent` / `Entity.HasComponent`
        /// nodes already take ("Transform"). Those nodes shipped with a curated
        /// short-name table in #634 and a graph author has no reason to expect the
        /// new nodes to spell the same component differently; a bare name that
        /// misses is retried with "Component" appended.
        [[nodiscard]] static const ComponentFieldEntry* Find(std::string_view component, std::string_view field);

        /// Distinct component names, struct-spelled, sorted. For the editor's
        /// component picker.
        [[nodiscard]] static const std::vector<std::string>& ComponentNames();

        /// The fields of one component, or empty when the name is unknown.
        /// Accepts the same two spellings as `Find`.
        [[nodiscard]] static std::vector<const ComponentFieldEntry*> FieldsOf(std::string_view component);
    };

} // namespace OloEngine::VisualScript
