"""Regenerate #1257 workloads from existing assets without modifying source fixtures.

PyYAML is required. The animal source is a scheduling fixture with unbound coats;
the derived scenes retain that limitation and do not claim finished animal art.
"""
import copy
import importlib.util
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
EDITOR = ROOT / 'OloEditor'
SCENES = EDITOR / 'SandboxProject/Assets/Scenes/Benchmark'
MANIFESTS = EDITOR / 'assets/benchmark/manifests'
_spec = importlib.util.spec_from_file_location(
    'reference_assets', ROOT / 'tools/benchmark/reference_assets.py')
reference_assets = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(reference_assets)


class FixtureLoader(yaml.SafeLoader):
    # Manifest tokens such as Normalize: on are strings, not YAML 1.1 booleans.
    yaml_implicit_resolvers = copy.deepcopy(yaml.SafeLoader.yaml_implicit_resolvers)


for _first, _resolvers in FixtureLoader.yaml_implicit_resolvers.items():
    FixtureLoader.yaml_implicit_resolvers[_first] = [entry for entry in _resolvers
        if entry[0] != 'tag:yaml.org,2002:bool']
FixtureLoader.add_implicit_resolver('tag:yaml.org,2002:bool',
    re.compile(r'^(?:true|True|TRUE|false|False|FALSE)$'), list('tTfF'))


class FixtureDumper(yaml.SafeDumper):
    def ignore_aliases(self, value):
        return True


def read(path):
    return yaml.load(path.read_text(encoding='utf-8'), Loader=FixtureLoader)


def write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('# Generated by scripts/perf/generate-streaming-residency-fixtures.py\n' +
                    yaml.dump(value, Dumper=FixtureDumper, sort_keys=False, width=100), encoding='utf-8')


def main():
    for family, source, manifest, near, crossing, speed in (
        ('Groom', 'AnimalPopulation', 'animal-population.diagnostic.yaml',
         [0, 3.4, 16], [0, 3, 22], [0, 0, -5]),
        ('Vegetation', 'Woodland', 'woodland.diagnostic.yaml',
         [0, 9, 20], [0, 9, 80], [0, 0, -9])):
        resident_budget = 128 if family == 'Vegetation' else 64
        upload_budget = 32 if family == 'Vegetation' else 8
        scene = read(SCENES / f'{source}.olo')
        base = read(MANIFESTS / manifest)
        # Keep the source's exact assets/provenance, refresh content hashes to
        # the committed files used by these workload variants.
        for asset in base['Assets']:
            asset['Sha256'] = reference_assets.sha256_of(EDITOR / asset['Path'])
        for pressure in (False, True):
            name = f'Streaming{family}' + ('Pressure' if pressure else '')
            budget_description = ('forced low resident budget' if pressure else
                                  f'{resident_budget} MiB optional GPU budget')
            variant = copy.deepcopy(scene)
            variant['Scene'] = name
            variant['StreamingSettings'] = {
                'Enabled': False,
                'RepresentationResidentMegabytes': .001 if pressure else resident_budget,
                'RepresentationUploadMegabytesPerFrame': upload_budget,
                'RepresentationStagingMegabytes': 128}
            write(SCENES / f'{name}.olo', variant)
            for path, label in (('Forward', 'forward'), ('ForwardPlus', 'forward-plus'),
                                ('Deferred', 'deferred')):
                capture = copy.deepcopy(base)
                capture['Id'] = f'streaming-{family.lower()}-{label}' + ('-pressure' if pressure else '')
                capture['Scene'] = f'Scenes/Benchmark/{name}.olo'
                capture['Description'] = (
                    f'{family} optional representation streaming; '
                    f'{budget_description}; '
                    f'{upload_budget} MiB upload and 128 MiB CPU staging budgets. '
                    'Camera traversal is a representation-demand transition, not a region-file load. '
                    'Region and cooked-pack acceptance require separately recorded runtime evidence.')
                def camera(identifier, position, velocity=None, yaw_rate=0):
                    result = {'Id': identifier, 'Position': position, 'YawDegrees': 0,
                              'PitchDegrees': 5 if family == 'Groom' else 1, 'FovDegrees': 55,
                              'Near': .05, 'Far': 2000, 'WarmupFrames': 64}
                    if velocity is not None:
                        result['Motion'] = {'VelocityPerSecond': velocity,
                                            'YawRateDegreesPerSecond': yaw_rate,
                                            'PitchRateDegreesPerSecond': 0}
                    return result
                capture['Cameras'] = [camera('steady', near),
                                      camera('rapid-turn', near, [0, 0, 0], 180),
                                      camera('traversal', crossing, speed)]
                capture['RendererSettings']['Path'] = path
                # Beauty/velocity/depth exist on every path. G-buffer-only AOVs
                # would make a forward workload fail before collecting tails.
                capture['Attachments'] = [a for a in capture['Attachments']
                                          if a['Name'] in ('Beauty', 'Velocity', 'SceneDepth')]
                capture['Backends']['Features']['vulkan']['UnsupportedAttachments'] = []
                capture['Measurement'] = {'Frames': 1000, 'DeadlineMs': 16.666667}
                capture['Tolerance']['RepeatRmse'] = 0
                write(MANIFESTS / f'{capture["Id"]}.yaml', capture)

        # Real region loads: content lives in .oloregion files, not in the root
        # scene. These workloads require the capture host to initialize the
        # editor streamer, or runtime play, before the camera sequence starts.
        regional = copy.deepcopy(scene)
        regional['Scene'] = f'Streaming{family}Regions'
        content = [e for e in regional['Entities']
                   if ('GroomComponent' in e if family == 'Groom' else 'TerrainComponent' in e)]
        regional['Entities'] = [e for e in regional['Entities'] if e not in content]
        region_dir = SCENES / f'Streaming{family}Regions'
        load_radius, unload_radius = (45, 55) if family == 'Groom' else (125, 135)
        regional['StreamingSettings'] = {
            'Enabled': True, 'DefaultLoadRadius': load_radius, 'DefaultUnloadRadius': unload_radius,
            'MaxLoadedRegions': 2,
            'RegionDirectory': f'SandboxProject/Assets/Scenes/Benchmark/Streaming{family}Regions',
            'RepresentationResidentMegabytes': resident_budget,
            'RepresentationUploadMegabytesPerFrame': upload_budget,
            'RepresentationStagingMegabytes': 128}
        for side in range(2):
            if family == 'Groom':
                entities = [e for e in content
                            if (e['TransformComponent']['Translation'][2] < -40) == bool(side)]
                bounds_min = [-40, -10, -120 if side else -40]
                bounds_max = [40, 30, -40 if side else 30]
            else:
                entities = copy.deepcopy(content)
                for entity in entities:
                    entity['Entity'] += 1257000000000000 + side
                    entity['TransformComponent']['Translation'][2] += -96 if side else 96
                    entity['TagComponent']['Tag'] += f' Region {side}'
                bounds_min = [-96, -10, -192 if side else 0]
                bounds_max = [96, 50, 0 if side else 192]
            region_id = 1257000000000100 + (10 if family == 'Vegetation' else 0) + side
            # Discovery records metadata only. Proximity activation requires a
            # root-scene volume; its radius uses point distance, not AABB distance.
            regional['Entities'].append({
                'Entity': 1257000000010000 + (10 if family == 'Vegetation' else 0) + side,
                'TagComponent': {'Tag': f'{family} Region {side} Activation'},
                'TransformComponent': {
                    'Translation': [(a + b) / 2 for a, b in zip(bounds_min, bounds_max)],
                    'Rotation': [0, 0, 0], 'Scale': [1, 1, 1]},
                'StreamingVolumeComponent': {
                    'RegionAssetHandle': region_id, 'ActivationMode': 0,
                    'LoadRadius': load_radius, 'UnloadRadius': unload_radius}})
            write(region_dir / f'region-{side}.oloregion', {
                'Region': f'{family} Region {side}',
                'RegionID': region_id,
                'BoundsMin': bounds_min, 'BoundsMax': bounds_max, 'Entities': entities})
        write(SCENES / f'Streaming{family}Regions.olo', regional)
        for label in ('forward', 'forward-plus', 'deferred'):
            capture = read(MANIFESTS / f'streaming-{family.lower()}-{label}.yaml')
            capture['Id'] += '-regions'
            capture['Scene'] = f'Scenes/Benchmark/Streaming{family}Regions.olo'
            capture['Description'] = (
                f'{family} content in two real .oloregion files; camera traversal crosses their '
                f'load and unload bounds; {resident_budget} MiB optional GPU, {upload_budget} MiB '
                'upload and 128 MiB CPU staging budgets. Require observed admitted/loaded/unloaded counts; an '
                'editor host that does not initialize the SceneStreamer has not exercised this workload.')
            if family == 'Vegetation':
                for camera_spec in capture['Cameras']:
                    camera_spec['Position'] = [0, 9, 120]
                capture['Cameras'][2]['Position'] = [0, 9, 120]
                capture['Cameras'][2]['Motion']['VelocityPerSecond'] = [0, 0, -14.4]
            write(MANIFESTS / f'{capture["Id"]}.yaml', capture)


if __name__ == '__main__':
    main()
